FROM chb-reviewer:machine-v1
LABEL org.chb.verifier.version="2026-10-07-readability-v4"
COPY verify.cjs /tests/verify.cjs
COPY readability.cjs /tests/readability.cjs
COPY readability-check.cjs /tests/readability-check.cjs
COPY readability.test.cjs /tests/readability.test.cjs
COPY fixtures /tests/fixtures
