import {Details} from './ui';

export function BenchmarkMethods(){return <div className="guide-content">
  <section className="reading-copy"><h2>先问“这是什么分”，再看数字</h2><p>截图中的百分比、Elo 和指数不是同一单位。任务、工具、执行预算和判分器不同，不能把不同榜单直接相加。本工作台把原题程序验收、项目质量、人工体验与用量分别记录。</p></section>
  <div className="guide-two-column"><section><h2>已有工程的基准任务</h2><p>DeepSWE、Terminal-Bench 等按固定题目与验收器计算单次成功率。DeepSWE 以提交补丁后的程序验证为主；本机仅有少量 Windows 适配，未接通的题没有原题通过分。AI 质量评价单列。</p></section><section><h2>开放需求的真实交付</h2><p>先把产品目标写成可观察的必要验收条目，再检查实际产物、运行证据和人工体验。允许多种合理实现。缺少运行或界面证据时留空，不把其余项目放大成总分。</p></section></div>
  <section className="reading-copy"><h2>别人怎样评，我们借鉴哪一部分？</h2><p>开源评测没有一个通用的“Harness 好用分”。任务成功、对话质量和过程失误通常用不同办法测；本项目需要把它们放到同模型对照中，才能回答你的规则是否有帮助。</p></section>
  <div className="guide-two-column"><section><h3><a href="https://docs.harborframework.com/core-concepts/tasks/overview" target="_blank" rel="noreferrer">Harbor：让任务自己声明验收器 ↗</a></h3><p>每题的检查器生成 reward，再按数据集协议汇总。它能验证任务结果，但没有自动解决“回答绕弯”和“设计是否多余”。其默认缺失按零的聚合方式也不同于本站的未知状态。</p></section><section><h3><a href="https://github.com/sierra-research/tau2-bench/blob/main/docs/evaluation.md" target="_blank" rel="noreferrer">τ-bench：做到了，也要告诉用户 ↗</a></h3><p>常见域将终态检查与必要告知相乘；告知检查基于指定字符串。我们借鉴结果与沟通分开验证，但字串出现不等于表达清楚，也不要求复制唯一工具路径。</p></section><section><h3><a href="https://github.com/tatsu-lab/alpaca_eval" target="_blank" rel="noreferrer">AlpacaEval：比较回答，检查长度偏差 ↗</a></h3><p>同题成对比较，随机呈现顺序，另有长度控制的胜率方法。适合借鉴匿名偏好与偏差校验，不能直接当作长期工程协作的成绩。</p></section><section><h3><a href="https://github.com/microsoft/AgentRx" target="_blank" rel="noreferrer">AgentRx：从轨迹找到哪里跑偏 ↗</a></h3><p>检查执行中的约束与违规证据，定位关键失败步骤。对我们有用的是“哪次回答或改动出了问题”，而不是再加一个笼统能力分；自动归因也需要核验。</p></section></div>
  <Details title="怎样量化这几个小变量，而不是继续泛泛打分？"><p>切题、纠正后的回答与不必要打断已经接入回收和现有裁判，逐回合列出符合、偏离、未知、不适用及引用。下面是完整测量目标；代码落实、复发、范围扩张与匿名表达偏好仍未自动接通。先冻结同样的任务、用户信息与纠正条件，记录本题的可见消息、改动和运行结果，再由新会话的裁判查看匿名材料。对话是待审数据，不是裁判指令；不需要隐藏思维链。</p><ul className="guide-facts"><li>答到点：首次命中数 / 可判定请求数，同时显示未知和覆盖率。</li><li>接受纠正：已落实纠正 / 可判定纠正，另列同一意图额外提醒次数。</li><li>合作负担：不必要打断、范围外改动、同缺陷复发和文案混入内部指令的事件数，各附回合或位置。</li><li>表达清楚：匿名 A/B 胜、平、负与无法判断；交换呈现顺序检查偏差，不把短答案直接当好答案。</li></ul><p>示意而非实测：同样20个请求，首次命中由12次到17次，是本批增加25个百分点；还必须检查交付质量、未知与重复波动。不能据此声称所有场景都提高25%。</p></Details>
  <Details title="提示词要怎么改，才不会越修越重？"><p>一次验证一个假设，例如“先回答核心问题，再解释必要细节”，或“用户纠正后修正同类问题，并检查是否复发”。用不同任务里的好、坏和合理替代例检验，连同误杀、漏检、复评与顺序偏差一起记录。没有收益的规则回退或删掉；必要澄清、必要解释和合理抽象不能被一刀切惩罚。</p><p>少量独立人工标注用于校准与抽查，而不是让每位用户逐题打分。当前已接通前三项文本观察，尚未完成独立语义校准，不能将旧雷达的“协作与交付”读作“很会与你沟通”。</p></Details>
  <Details title="截图中的榜单分别怎么算"><ul className="guide-facts">
    <li><strong>DeepSWE / Terminal-Bench / SWE-Atlas-QnA：</strong>按各自固定题目判整题通过与否，重复运行后估计 pass@1。DeepSWE 看补丁的程序验收；QnA 用逐条标准判答案。</li>
    <li><strong>GDPval-AA / AA-Briefcase / Code Arena WebDev：</strong>比较同题两份交付的质量，再把成对胜负汇总为相对 Elo/BT 尺度。分数不是百分比。</li>
    <li><strong>AutomationBench-AA：</strong>检查跨应用任务终态：完成多少目标，以及是否违反约束；违反守则的任务该项为零。它与“全部目标完成的任务比例”是两个指标。</li>
    <li><strong>Artificial Analysis Intelligence Index：</strong>按公开权重汇总十项不同评测，是该机构定义的综合指数；与单独软件工程榜单的百分比不同。价格和 Token 另列，不算进能力分。</li>
  </ul><p><a href="https://artificialanalysis.ai/methodology/coding-agents-benchmarking" target="_blank" rel="noreferrer">Coding Agent Index 方法 ↗</a> · <a href="https://artificialanalysis.ai/methodology/intelligence-benchmarking" target="_blank" rel="noreferrer">Intelligence Index 方法 ↗</a> · <a href="https://arena.ai/blog/webdev-arena" target="_blank" rel="noreferrer">WebDev Arena 方法 ↗</a></p></Details>
  <Details title="项目经理式任务怎样设指标"><ol className="guide-steps"><li><strong>先写结果和边界</strong><p>用户是谁、完成什么流程、输入输出是什么、哪些限制绝不能违反。</p></li><li><strong>冻结必要验收</strong><p>把关键流程、错误恢复和交付物列成可观察条目；能自动测的用程序测，不能测的指定操作和证据。</p></li><li><strong>只启用适用维度</strong><p>默认从需求完成、验证与回归、健壮性、规则遵守、交互、交付和可维护性起步。无界面题自动排除交互；性能、安全在题目需要时加入。</p></li><li><strong>分数带覆盖率</strong><p>所有适用项有证据即可看到暂定单题分；交付结束后还须有独立任务验收，才能进入配置对比。程序通过率与 AI 质量分分别显示；未验证不作零分，也不能只用已评分的 5% 冒充总分。</p></li></ol></Details>
  <Details title="配置历史怎样阅读"><p>开放项目同题多次有效评分先取均值，再按已验证题目等权显示质量参考均分。公开基准题另列本机程序通过数；AI 意见不混入通过率。它们描述已测样本，不自动推断全部任务的能力。比较两套配置仍要对齐同题同版本、模型、起点、环境和裁判协议。</p></Details>
  <p className="score-notice">公开题目与任务链接在“题库与公开来源”中，可直接选择题目进入评测。榜单分数只在各自协议内解释；本机 Windows 适配不等同官方 Linux 成绩。</p>
</div>;}
