import {useEffect,useState} from 'react';
import type {Act,Config} from './types';
import {request} from './api';
import {Field,Details,Dialog} from './ui';
import {applicationStatus,applicationErrorHelp} from './applicationStatus';
type Receipt={id:string;configId:string;configName:string;status:string;message:string;home:string;configRevision:number;filesMatch?:boolean;settingsMatch?:boolean;canPreserveChanges?:boolean;fileChecks?:{path:string;matches:boolean;managedMatches:boolean}[]};
type Host={model?:string;reasoning?:string;serviceTier?:string;home:string;instructionsFile:string;connections:Record<string,{id:string;enabled:boolean}[]>;applications:Receipt[]};

export function CodexApply({config,act,save,hasUnsavedChanges=false,trialRoute,disabled=false,compact=false}:{config:Config;act:Act;save?:()=>Promise<Config>;hasUnsavedChanges?:boolean;trialRoute?:string;disabled?:boolean;compact?:boolean}){
  const [expanded,setExpanded]=useState(false);const [host,setHost]=useState<Host|null>(null);const [error,setError]=useState('');const [result,setResult]=useState('');const [pending,setPending]=useState(false);
  const refresh=()=>request<Host>('/codex/status',{}).then(setHost);
  useEffect(()=>{let live=true;request<Host>('/codex/status',{}).then(h=>{if(live)setHost(h);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
  const active=host?.applications.find(r=>['applying','applied','restore_failed'].includes(r.status));
  const speed=config.serviceTier==='fast'?'Fast':config.serviceTier==='standard'?'标准速度':'沿用宿主速度（未固定）';
  const fileMismatch=!!host&&(host.model!==config.baseModel||(config.reasoning?host.reasoning!==config.reasoning:!!host.reasoning)||(config.serviceTier&&host.serviceTier!==config.serviceTier));
  const readbackUnconfirmed=!!result&&!!error;
  const status=readbackUnconfirmed?{label:'操作已提交，文件状态待核实',detail:'请先核对当前文件；不要重复应用或撤销。',ready:false}:applicationStatus(active,config,hasUnsavedChanges,!!fileMismatch);
  const alreadyApplied=!trialRoute&&status.ready;
  const apply=async()=>{setPending(true);setError('');setResult('');try{const c=save?await save():config;const r=await act<Receipt>(trialRoute||'/codex/switch',{configId:c.id,revision:c.revision},{localError:true,silentSuccess:true});setResult(r.message);await refresh();}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{setPending(false);}};
  const undo=async(preserveUnrelated=false)=>{setPending(true);setError('');setResult('');try{const r=await act<Receipt>('/codex/restore',{applicationId:active?.id,preserveUnrelated},{localError:true,silentSuccess:true});setResult(r.message);await refresh();}catch(e){setError((e as Error).message);await refresh().catch(()=>{});}finally{setPending(false);}};
  const content=<section className="codex-apply space-y-3"><h3 className="font-semibold">Codex 配置应用</h3>
    <dl className="config-facts"><dt>目标模型</dt><dd>{config.baseModel}</dd><dt>目标思考档位</dt><dd>{config.reasoning||'模型默认（未固定）'}</dd><dt>目标速度</dt><dd>{speed}</dd><dt>Skills</dt><dd>{config.skills.length} 个已选技能</dd></dl>
    <ol className="application-steps"><li className={status.ready?'is-ready':''}><strong>1 · {host?status.label:'正在读取文件状态'}</strong><p>{status.detail}</p></li><li><strong>2 · 桌面对话待核实</strong><p>打开新题后，在 Codex 顶部核对模型、思考档位和速度；有不同就手动调整，再发送提示词。执行页会用本题日志核对已记录的模型与档位。</p></li></ol>
    {error&&<div role="alert" className="application-feedback alert-error"><strong>{readbackUnconfirmed?'操作已提交，文件核对未完成':'操作未完成'}</strong><p>{readbackUnconfirmed?'服务已返回操作回执，但最新文件状态未能读回。请先点“核对当前文件”，不要重复提交。':applicationErrorHelp(error)}</p><Details title="错误详情"><p>{error}</p></Details></div>}
    {result&&!active&&!error&&<p role="status" className="application-feedback">{result}</p>}
    <div className="run-actions"><button type="button" className="btn-primary" disabled={disabled||pending||!host||(!save&&!config.id)||alreadyApplied} onClick={()=>void apply()}>{pending?'正在处理…':hasUnsavedChanges?'保存修改并应用':alreadyApplied?'文件已应用':trialRoute&&status.ready?'确认用于本题':active?'应用所选配置':'应用到全局默认值'}</button>{active&&<button type="button" className="btn-secondary" disabled={disabled||pending} onClick={()=>void undo(active.filesMatch===false&&active.canPreserveChanges===true)}>撤销上次应用</button>}<button type="button" disabled={pending} className="btn-secondary" onClick={()=>{setError('');setResult('');void refresh().catch(e=>setError(e.message));}}>核对当前文件</button></div>
    <Details title="写入位置与详细回执"><p>应用会备份并写入全局默认值，不能强制切换 Codex 当前对话。独立工作区的项目设置和桌面选择可能覆盖全局值；未核实条件的成绩不宜用于配置比较。</p><p>当前全局文件：{host?.model||'默认模型'} · {host?.reasoning||'默认档位'} · {host?.serviceTier==='fast'?'Fast':host?.serviceTier==='standard'?'标准速度':'沿用默认速度'}。</p>{active&&<p>{active.configName} · v{active.configRevision} · {active.status}</p>}<p className="break-all">{host?.home||'读取中…'}</p><p className="break-all">规则来源：{host?.instructionsFile||'读取中…'}。使用 AGENTS.override.md 时，Codex 个性化页会提示原 AGENTS.md 被覆盖；这是文件优先级提示。</p><p>模型、速度与原生设置写入 config.toml；规则写入 AGENTS.override.md；选定技能放入 skills。文件匹配只能确认落盘，项目覆盖、任务选择及桌面重载仍影响实际值。</p>{active?.fileChecks?.map(f=><p className="break-all" key={f.path}>{f.path} · {f.matches?'与应用回执一致':f.managedMatches?'文件有其他变化，本配置写入的设置一致':'本配置写入的设置已变化或缺失'}</p>)}{result&&<p role="status">{result}</p>}</Details>
  </section>;
  return compact?<><div className="config-apply-entry"><button className="btn-secondary" onClick={()=>setExpanded(true)}>查看 Codex 配置</button>{error?<button className="run-status-warning" onClick={()=>setExpanded(true)}>状态读取失败</button>:fileMismatch?<button className="run-status-warning" onClick={()=>setExpanded(true)}>模型 / 档位 / 速度待核对</button>:active&&<button className={active.settingsMatch===false||active.status!=='applied'?'run-status-warning':'btn-ghost'} onClick={()=>setExpanded(true)}>{active.status!=='applied'?'应用待核对':active.settingsMatch===false?'所选设置已变化':'全局文件已应用'}</button>}</div><Dialog title="Codex 配置应用" open={expanded} onClose={()=>setExpanded(false)}>{content}{disabled&&<p className="muted">本试次已开始或已归档，不能在这里更换已保存的配置版本。</p>}</Dialog></>:content;
}

export function NativeConfigFields({config,change}:{config:Config;change:(patch:Partial<Config>)=>void}){
  const [host,setHost]=useState<Host|null>(null);const [error,setError]=useState('');
  useEffect(()=>{let live=true;request<Host>('/codex/status',{}).then(h=>{if(live)setHost(h);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
  const fields:[string,string,string[]][]=[['web_search','联网搜索',['disabled','cached','live']],['model_verbosity','输出详细程度',['low','medium','high']],['model_reasoning_summary','推理摘要',['auto','concise','detailed','none']]];
  return <section className="space-y-4"><h3 className="font-semibold">Codex 原生配置</h3><div className="grid md:grid-cols-3 gap-4">{fields.map(([key,label,values])=><Field key={key} label={label}><select value={config.nativeSettings?.[key]||''} onChange={e=>{const next={...config.nativeSettings};if(e.target.value)next[key]=e.target.value;else delete next[key];change({nativeSettings:next});}}><option value="">保持宿主设置</option>{values.map(v=><option key={v}>{v}</option>)}</select></Field>)}</div>
    <h3 className="font-semibold">工具与插件</h3><p className="muted">这里按打开页面时读到的本机 config.toml 列出已配置的 MCP 连接与插件开关；内容随你的配置文件变化，不是固定清单，也不会在后台替你更新插件。安装、授权和插件版本由 Codex 管理。</p><button type="button" className="btn-ghost" onClick={()=>void request<Host>('/codex/status',{}).then(setHost).catch(e=>setError(e.message))}>刷新本机清单</button>
    {error&&<p role="alert" className="alert-error">{error}</p>}{['mcp_servers','plugins'].map(group=><div className="native-group" key={group}><h4 className="text-sm font-medium">{group==='plugins'?'已配置的插件':'MCP 工具连接'}</h4>{host?.connections[group]?.length?host.connections[group].map(item=><Field key={item.id} label={item.id}><select value={config.integrations?.[group]?.[item.id]===undefined?'inherit':String(config.integrations[group][item.id])} onChange={e=>{const next={...config.integrations?.[group]};if(e.target.value==='inherit')delete next[item.id];else next[item.id]=e.target.value==='true';change({integrations:{...config.integrations,[group]:next}});}}><option value="inherit">保持当前（{item.enabled?'启用':'停用'}）</option><option value="true">启用</option><option value="false">停用</option></select></Field>):<p className="muted">config.toml 中未发现此类配置。其他安装来源状态未知，不代表未安装。</p>}</div>)}
    <p className="muted">权限/沙箱、Hooks、记忆、子代理和项目规则同样属于运行条件；本轮保留宿主值，尚不提供迁移。密钥与认证不会导入工作台。</p>
  </section>;
}
