import {useRef,useState} from 'react';
import type {Act,Task,ProjectSpec,Criterion,Review} from './types';
import {Field,Details,Panel,Json} from './ui';
import {request} from './api';

const sections={userStories:'用户故事',apiEndpoints:'接口约定',dataModel:'数据模型',acceptanceCriteria:'验收标准'} as const;
const emptySpec=():ProjectSpec=>({userStories:[],apiEndpoints:[],dataModel:[],acceptanceCriteria:[],techStack:''});
export const verdicts:Record<string,string>={met:'已满足',partial:'部分满足',unmet:'未满足',unverified:'未核实',not_applicable:'不适用',not_met:'未通过',needs_review:'必要项被标为不适用，需复审',not_configured:'未指定必要项',legacy_unavailable:'旧记录未配置逐项验收',in_progress:'已核实条目，交付尚未结束'};
export const channels:Record<string,string>={'frontend-ui':'应用与界面','deepswe-core':'功能与工程','architecture-constraint':'架构与约束','interactive-confirm':'协作与多轮'};
const scopes:Record<string,string>={'frontend-only':'仅前端','fullstack-node':'前后端（Node）','fullstack-sqlite':'前后端与 SQLite','frontend-mockapi':'前端与模拟 API'};
export function matchTask(t:Task,kind:string,query:string,channel:string,difficulty:string){return (kind==='repository'?!!t.baselineId||!!t.requiresBaseline||t.taskParadigm==='deterministic-bugfix':kind==='open-ended-project'?t.taskParadigm===kind&&!t.requiresBaseline&&!t.baselineId:t.taskParadigm===kind)&&(!channel||t.channel===channel)&&(!difficulty||t.difficulty?.toLowerCase()===difficulty)&&[t.title,t.description,t.inputPrompt].some(v=>v?.toLowerCase().includes(query.trim().toLowerCase()));}
export function TaskFilters({channel,difficulty,onChannel,onDifficulty}:{channel:string;difficulty:string;onChannel:(v:string)=>void;onDifficulty:(v:string)=>void}){return <div className="task-secondary-filters"><Field label="任务方向"><select value={channel} onChange={e=>onChannel(e.target.value)}><option value="">全部方向</option>{Object.entries(channels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="难度"><select value={difficulty} onChange={e=>onDifficulty(e.target.value)}><option value="">全部难度</option>{['Easy','Medium','Hard','Nightmare'].map(v=><option key={v} value={v.toLowerCase()}>{v}</option>)}</select></Field></div>;}

export function ContractView({task}:{task:Task}){return <div className="space-y-4">
  {task.fullstackScope&&<p className="text-sm">项目范围：{scopes[task.fullstackScope]||task.fullstackScope}</p>}
  {task.projectSpec?.techStack&&<div><h3 className="font-semibold text-sm">技术边界</h3><p className="whitespace-pre-wrap text-sm">{task.projectSpec.techStack}</p></div>}
  {Object.entries(sections).map(([key,label])=>{const rows=task.projectSpec?.[key as keyof typeof sections];return !!rows?.length&&<div key={key}><h3 className="font-semibold text-sm">{label}</h3><ul className="list-disc pl-5 text-sm space-y-2">{rows.map((r,i)=><li className="whitespace-pre-wrap" key={i}>{r}</li>)}</ul></div>;})}
  {!!task.criteria?.length&&<div><h3 className="font-semibold text-sm">逐项验收</h3>{task.criteria.map(c=><div key={c.id} className="panel-subtle p-3 mt-2"><p className="text-sm">{c.required?'必要项':'观察项'} · {c.label}</p>{c.description&&<p className="text-sm whitespace-pre-wrap">{c.description}</p>}<small className="muted break-all">{c.id} · 来源 {c.source}</small></div>)}</div>}
  {!task.projectSpec&&!task.criteria?.length&&<p className="muted">此版本没有结构化项目契约，按题面与已声明检查复审。</p>}
  <Details title="原题评分说明（保留来源，不自动计分）"><Json value={{customChecklist:task.customChecklist,evaluationRubric:task.evaluationRubric,rubrics:task.rubrics}}/></Details>
</div>;}

export function ContractEditor({task,onChange,rubrics}:{task:Task;onChange:(patch:Partial<Task>)=>void;rubrics:Record<string,{label:string;description:string}>}){
  const spec=task.projectSpec||emptySpec();const criteria=task.criteria||[];
  const changeSpec=(patch:Partial<ProjectSpec>)=>onChange({projectSpec:{...spec,...patch}});
  const changeCriterion=(id:string,patch:Partial<Criterion>)=>onChange({criteria:criteria.map(c=>c.id===id?{...c,...patch}:c)});
  const addFromSpec=()=>{const labels=new Set(criteria.map(c=>c.label.trim()));const added:Criterion[]=[];for(const [source,rows] of [['projectSpec.userStories',spec.userStories],['projectSpec.acceptanceCriteria',spec.acceptanceCriteria]] as const){for(const label of rows){if(label.trim()&&!labels.has(label.trim())){labels.add(label.trim());added.push({id:'criterion-'+crypto.randomUUID(),label,description:'',required:false,dimension:'intent',source});}}}onChange({criteria:[...criteria,...added]});};
  return <><Details title="项目契约：用户故事、接口、数据与验收" open={!!task.projectSpec}>
    {task.contractUpgradePending&&<p className="muted">旧题已在此显示兼容转换。保存或准备新评测时冻结新版契约，旧评测不变。转换条目默认是观察项，请明确勾选必要项。</p>}
    <Field label="项目范围"><select value={task.fullstackScope||''} onChange={e=>onChange({fullstackScope:e.target.value||undefined})}><option value="">由题目说明</option>{Object.entries(scopes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
    <Field label="技术边界" hint="写明必须使用、禁止使用与允许自主选择的技术。"><textarea rows={3} value={spec.techStack} onChange={e=>changeSpec({techStack:e.target.value})}/></Field>
    {Object.entries(sections).map(([key,label])=>{const k=key as keyof typeof sections;return <div className="space-y-2" key={k}><h3 className="text-sm font-semibold">{label}</h3>{spec[k].map((row,i)=><div className="flex gap-2 items-start" key={i}><textarea aria-label={`${label} ${i+1}`} required value={row} onChange={e=>changeSpec({[k]:spec[k].map((v,j)=>j===i?e.target.value:v)})}/><button type="button" className="btn-ghost" onClick={()=>changeSpec({[k]:spec[k].filter((_,j)=>j!==i)})}>移除</button></div>)}<button type="button" className="btn-secondary" onClick={()=>changeSpec({[k]:[...spec[k],'']})}>添加{label}</button></div>;})}
  </Details><Details title={`逐项验收约定 · ${criteria.length} 项`}>
    <p className="muted">必要项单独给出验收结论，不能用高分抵销。项目契约与条目分别维护；修改需求后请核对对应条目，补充按钮只添加缺少的文字，不覆盖已有裁定。</p>
    {criteria.map(c=><div key={c.id} className="panel-subtle p-3 space-y-3"><Field label="验收条目"><input required value={c.label} onChange={e=>changeCriterion(c.id,{label:e.target.value})}/></Field><Field label="验收说明"><textarea value={c.description} onChange={e=>changeCriterion(c.id,{description:e.target.value})}/></Field><div className="flex flex-wrap gap-3"><label className="check-row"><input type="checkbox" checked={c.required} onChange={e=>changeCriterion(c.id,{required:e.target.checked})}/>必要项</label><select aria-label="验收分类（不自动计分）" value={c.dimension} onChange={e=>changeCriterion(c.id,{dimension:e.target.value})}>{Object.entries(rubrics).map(([v,item])=><option key={v} value={v}>{item.label}</option>)}</select><button type="button" className="btn-ghost" onClick={()=>onChange({criteria:criteria.filter(v=>v.id!==c.id),checks:task.checks.map(v=>({...v,criterionIds:v.criterionIds?.filter(id=>id!==c.id)}))})}>移除条目与检查关联</button></div><small className="muted break-all">{c.id} · {c.source}</small></div>)}
    <div className="flex gap-3 flex-wrap"><button type="button" className="btn-secondary" onClick={addFromSpec}>从用户故事与验收标准补充条目</button><button type="button" className="btn-secondary" onClick={()=>onChange({criteria:[...criteria,{id:'criterion-'+crypto.randomUUID(),label:'',description:'',required:false,dimension:'intent',source:'user-authored'}]})}>手动添加验收条目</button></div>
  </Details></>;
}

type ImportPreview={valid:boolean;tasks:Task[];errors:{index:number;message:string}[];warnings:string[];fingerprint:string|null};
export function TaskImport({act,onImported}:{act:Act;onImported:(task:Task)=>void}){
  const [preview,setPreview]=useState<ImportPreview|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const pending=useRef<{document:unknown;requestId:string}|null>(null);
  return <Panel title="导入 JSON 题包"><p className="muted">选择单个题目、题目数组或包含 tasks 的版本1/2题包。先预览全部校验结果，再整体创建新副本；不会覆盖同名题或自动下载起点。</p><Field label="选择题包 JSON"><input type="file" accept=".json,application/json" disabled={loading} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError('');setPreview(null);pending.current=null;setLoading(true);try{if(f.size>900000)throw new Error('题包超过900 KB，请拆分。');const document=JSON.parse(await f.text());const p=await request<ImportPreview>('/tasks/import-preview',{document});pending.current={document,requestId:crypto.randomUUID()};setPreview(p);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}}/></Field>
    {loading&&<p role="status" className="muted">正在校验题包…</p>}{error&&<p role="alert" className="alert-error">{error}</p>}{preview&&<div className="space-y-3">{preview.errors.map(e=><p role="alert" className="alert-error" key={e.index}>第 {e.index} 题：{e.message}</p>)}{preview.warnings.map(w=><p className="muted" key={w}>{w}</p>)}{preview.tasks.map((t,i)=><Details key={i} title={`预览 ${i+1}：${t.title}`}><pre className="source">{t.inputPrompt}</pre><ContractView task={t}/><p className="muted">来源：{t.sourceNote||'未声明'} · 许可：{t.license||'未声明'} · {t.checks.length} 项检查</p></Details>)}<button className="btn-primary" disabled={!preview.valid||loading} onClick={async()=>{if(!pending.current)return;try{const r=await act<{imported:Task[]}>('/tasks/import',{...pending.current,fingerprint:preview.fingerprint});setPreview(null);pending.current=null;onImported(r.imported[0]);}catch{/* Global error; preserve ID for retry. */}}}>导入 {preview.tasks.length} 道新题</button></div>}
  </Panel>;
}

export function ReviewItems({task,review}:{task:Task;review:Review}){return <div className="space-y-3">{task.criteria?.map(c=>{const item=review.criteria?.[c.id];return <div key={c.id} className="panel-subtle p-3"><p className="text-sm font-medium">{c.required?'必要项':'观察项'} · {c.label} · {verdicts[item?.status||'unverified']}</p><p className="text-sm whitespace-pre-wrap">{item?.notes||'无验收依据'}</p>{item?.filePath&&<p className="muted break-all">文件：{item.filePath} · {item.fileSha256?.slice(0,12)}</p>}{item?.checkId&&<p className="muted">检查：{item.checkEvidence?.label||item.checkId} · 提交时 {item.checkEvidence?.status}</p>}</div>;})}<Json value={{scores:review.scores,readiness:review.readiness,constraints:review.constraints,constraintNotes:review.constraintNotes,notes:review.notes,revisionReason:review.revisionReason,dimensionEvidence:review.dimensionEvidence}}/></div>;}
