import {InitialConfig} from './InitialConfig';
import {CodexApply,NativeConfigFields} from './Codex';
import {PublicTaskSources} from './PublicTaskSources';
import {useEffect,useState} from 'react';
import type {State,Act,Config,Task,Check,Imported} from './types';
import {SkillPicker,ProjectConfigImport} from './Skills';
import {Field,Panel,Details,Empty,ModelSelect,Dialog} from './ui';
import {TaskEnvironment,canStartTask,needsBaseline} from './TaskEnvironment';
import {ContractEditor,ContractView,TaskFilters,TaskImport,matchTask} from './Contracts';
import {configResults} from './configResults';
import {DeleteConfig} from './DeleteConfig';

const newConfig=():Config=>({id:'',revision:0,name:'',agentsPrompt:'',baseModel:'gpt-6-astra',reasoning:'medium',serviceTier:'standard',interactiveMode:'adaptive',skills:[],customConstraints:[]});
export function ConfigManager({state,act,onUse,initialConfigId}:{state:State;act:Act;onUse:(id:string)=>void;initialConfigId?:string|null}){
  const [draft,setDraft]=useState<Config>(structuredClone(state.configs.find(c=>c.id===initialConfigId)||state.configs[0]||newConfig()));
  const [section,setSection]=useState('rules');const [query,setQuery]=useState('');
  const [dialog,setDialog]=useState<'import'|'trash'|'delete'|null>(null);
  const scores=new Map(configResults(state).map(group=>[group.key,group]));
  const modelInfo=state.models.find(m=>m.id===draft.baseModel);const efforts=modelInfo?.reasoningLevels||[];
  const change=(patch:Partial<Config>)=>setDraft(current=>({...current,...patch}));
  const save=async(copy=false)=>{try{const c=await act<Config>('/configs/save',{...draft,...(copy?{id:undefined,revision:undefined,name:draft.name+' · 副本'}:{})});setDraft(c);return c;}catch{return null;}};
  const choose=(c:Config)=>setDraft(structuredClone(c));
  const savedDraft=state.configs.find(c=>c.id===draft.id);
  const dirty=!savedDraft||(['name','baseModel','reasoning','serviceTier','agentsPrompt','interactiveMode','skills','skillMode','customConstraints','nativeSettings','integrations'] as (keyof Config)[]).some(k=>JSON.stringify(draft[k])!==JSON.stringify(savedDraft[k]));
  const remove=async()=>{try{await act(`/configs/${draft.id}/archive`,{revision:draft.revision,archived:true});choose(state.configs.find(c=>c.id!==draft.id)||newConfig());setDialog(null);}catch{}};
  return <div className="studio-layout"><aside className="studio-library"><header><div><span className="eyebrow">个人 Harness</span><h1 className="page-title">配置库<span className="count-label">{state.configs.length}</span></h1></div><button className="btn-primary" onClick={()=>{setDraft(newConfig());setSection('rules');}}>新建配置</button></header>
    <InitialConfig state={state} act={act}/><input aria-label="搜索配置" placeholder="搜索名称或模型" value={query} onChange={e=>setQuery(e.target.value)}/>
    <div className="studio-list">{state.configs.filter(c=>(c.name+' '+c.baseModel).toLowerCase().includes(query.toLowerCase())).map(c=>{const score=scores.get(`${c.id}:${c.revision}`);return <button key={c.id} className={'list-card '+(draft.id===c.id?'selected':'')} onClick={()=>choose(c)}><strong>{c.name}</strong><span>{c.baseModel} · {c.reasoning} · {c.serviceTier==='fast'?'Fast':'标准/默认速度'}</span><small>v{c.revision} · {c.skills.length} 个 Skills · 参考均分 {score?.score==null?'—':score.score.toFixed(1)}{score?.score!=null?` / ${score.tasks.length} 题`:''}</small></button>;})}{!state.configs.length&&<Empty>还没有配置，点击新建或导入。</Empty>}</div>
    <div className="library-actions"><button className="btn-secondary" onClick={()=>setDialog('import')}>导入配置</button><button className="btn-ghost" onClick={()=>setDialog('trash')}>回收站 · {state.archivedConfigs.length}</button></div>
  </aside><section className="studio-editor"><header className="editor-heading"><div><span className="eyebrow">{draft.id?'已保存 v'+draft.revision:'新配置'}{dirty?' · 有未保存修改':''}</span><h2>{draft.name||'命名你的配置'}</h2></div><div className="editor-actions"><button className="btn-primary" disabled={draft.id.startsWith('initial-')} onClick={()=>void save()}>保存配置</button>{draft.id&&<button className="btn-danger" onClick={()=>setDialog('delete')}>删除配置</button>}</div></header>
    <nav className="section-nav" aria-label="配置编辑分区">{[['rules','模型与规则'],['skills',`Skills · ${draft.skills.length}`],['native','工具与原生设置'],['apply','应用到 Codex']].map(([id,label])=><button type="button" key={id} aria-current={section===id?'page':undefined} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav>
    <div className="editor-body">
      <div hidden={section!=='rules'} className="editor-section"><div className="config-basics"><Field label="配置名称"><input value={draft.name} onChange={e=>change({name:e.target.value})}/></Field><Field label="交互约定"><select value={draft.interactiveMode} onChange={e=>change({interactiveMode:e.target.value})}><option value="adaptive">按任务自行判断</option><option value="one-shot-direct">一次交付</option><option value="step-by-step-confirm">分阶段等我确认</option></select></Field><Field label="模型"><ModelSelect value={draft.baseModel} models={state.models} onChange={baseModel=>{const m=state.models.find(m=>m.id===baseModel);change({baseModel,reasoning:m?.reasoningLevels?.includes(draft.reasoning)?draft.reasoning:m?.defaultReasoning||m?.reasoningLevels?.[0]||'',serviceTier:draft.serviceTier==='fast'&&!m?.fastAvailable?'standard':draft.serviceTier});}}/></Field><Field label="推理档位"><select value={draft.reasoning} onChange={e=>change({reasoning:e.target.value})}><option value="">宿主默认（不写入档位）</option>{!!draft.reasoning&&!efforts.includes(draft.reasoning)&&<option disabled value={draft.reasoning}>{draft.reasoning||'请选择'} · {efforts.length?'不受支持':'能力未知'}</option>}{efforts.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="执行速度"><select value={draft.serviceTier||''} onChange={e=>change({serviceTier:e.target.value as Config['serviceTier']})}><option value="">沿用已有设置</option><option value="standard">标准</option><option value="fast" disabled={!modelInfo?.fastAvailable}>Fast · 当前模型{modelInfo?.fastAvailable?'可用':'未声明支持'}</option></select></Field></div><p className="muted">Fast 写入 Codex 项目配置；创建工作区后需在新的桌面任务中执行。实际速度与额度由当前账号和模型决定。</p>
      <Field label="AGENTS 规则"><textarea className="rules-editor" rows={10} value={draft.agentsPrompt} onChange={e=>change({agentsPrompt:e.target.value})} placeholder="填写模型需要遵守的规则"/></Field>
      <Details title={`个人约束 · ${draft.customConstraints.length} 项`}>{draft.customConstraints.map((c,i)=><div key={c.id} className="panel-subtle p-3 space-y-2"><div className="flex gap-3"><input aria-label="约束名称" value={c.title} onChange={e=>change({customConstraints:draft.customConstraints.map((v,j)=>i===j?{...v,title:e.target.value}:v)})}/><button type="button" className="btn-ghost" onClick={()=>change({customConstraints:draft.customConstraints.filter((_,j)=>j!==i)})}>移除</button></div><textarea aria-label="约束说明" value={c.ruleDesc} onChange={e=>change({customConstraints:draft.customConstraints.map((v,j)=>i===j?{...v,ruleDesc:e.target.value}:v)})}/><label className="check-row"><input type="checkbox" checked={c.isActive} onChange={e=>change({customConstraints:draft.customConstraints.map((v,j)=>i===j?{...v,isActive:e.target.checked}:v)})}/>本配置启用</label></div>)}<button type="button" className="btn-secondary" onClick={()=>change({customConstraints:[...draft.customConstraints,{id:'rule-'+crypto.randomUUID(),title:'',ruleDesc:'',isActive:true}]})}>添加个人约束</button></Details>
      {draft.importSource&&<Details title="导入来源"><p className="break-all">{draft.importSource.root}</p>{draft.importSource.files.map(f=><p className="muted break-all" key={f.path}>{f.path} · {f.sha256.slice(0,12)}</p>)}{draft.importSource.warnings.map(w=><p key={w}>{w}</p>)}<p>{draft.importSource.note}</p></Details>}
      </div>
      <div hidden={section!=='skills'} className="editor-section"><SkillPicker act={act} library={state.skills} value={draft.skills} onChange={skills=>change({skills})}/><Field label="技能调用方式"><select value={draft.skillMode||'auto'} onChange={e=>change({skillMode:e.target.value as 'auto'|'explicit'})}><option value="auto">按任务需要使用</option><option value="explicit">每轮明确请求使用</option></select></Field><p className="muted">选定技能随配置保存。桌面已有的全局技能仍可能被继承。</p></div>
      <div hidden={section!=='native'} className="editor-section"><NativeConfigFields config={draft} change={change}/></div>
      <div hidden={section!=='apply'} className="editor-section"><CodexApply config={draft} act={act} save={async()=>{const c=await act<Config>('/configs/save',draft);setDraft(c);return c;}}/></div>
    </div><footer className="editor-footer"><span>{draft.skills.length} 个 Skills · {draft.customConstraints.filter(c=>c.isActive).length} 条个人约束</span><div className="editor-actions">{draft.id&&<button className="btn-secondary" onClick={()=>void save(true)}>另存副本</button>}<button className="btn-secondary" onClick={async()=>{const c=dirty?await save():draft;if(c)onUse(c.id);}}>用于评测</button></div></footer></section>
    <Dialog title="导入配置" open={dialog==='import'} onClose={()=>setDialog(null)}><button className="btn-primary" onClick={()=>act<Config>('/configs/import-current',{}).then(c=>{choose(c);setDialog(null);}).catch(()=>{})}>读取当前 Codex 配置</button><ProjectConfigImport act={act} onImported={c=>{choose(c);setDialog(null);}}/><p className="muted">导入保存到工作台；“应用到 Codex”才会写入宿主配置。</p></Dialog>
    <Dialog title="配置回收站" open={dialog==='trash'} onClose={()=>setDialog(null)}>{state.archivedConfigs.length?state.archivedConfigs.map(c=><div className="recycle-row" key={c.id}><span>{c.name}</span><div className="source-actions"><button className="btn-secondary" onClick={()=>act<Config>(`/configs/${c.id}/archive`,{revision:c.revision,archived:false}).then(c=>{choose(c);setDialog(null);}).catch(()=>{})}>恢复配置</button><DeleteConfig config={c} act={act}/></div></div>):<p>回收站为空。</p>}</Dialog>
    <Dialog title="删除配置" open={dialog==='delete'} onClose={()=>setDialog(null)}><p>将“{draft.name}”移到回收站？可随时恢复，历史评测和已应用的 Codex 设置保留。</p><div className="editor-actions"><button className="btn-secondary" onClick={()=>setDialog(null)}>取消</button><button className="btn-danger" onClick={()=>void remove()}>移到回收站</button></div></Dialog>
  </div>;
}

const newTask=():Task=>({id:'',revision:0,title:'',difficulty:'medium',taskParadigm:'open-ended-project',channel:'frontend-ui',inputPrompt:'',stages:[{title:'完成需求',prompt:''}],checks:[],hasFrontendUI:true,sourceKind:'user-authored',sourceNote:'本地自定义题',license:'用户自有内容'});
export function TaskManager({state,act,onUse}:{state:State;act:Act;onUse:(id:string)=>void}){
  const [draft,setDraft]=useState<Task>(structuredClone(state.tasks.find(t=>needsBaseline(t)&&canStartTask(t,state.baselines))||newTask()));const [query,setQuery]=useState('');const [kind,setKind]=useState('repository');const [path,setPath]=useState('');
  const [sourcesOpen,setSourcesOpen]=useState(false);
  const [section,setSection]=useState('overview');const [pendingOnly,setPendingOnly]=useState(false);
  const [repoUrl,setRepoUrl]=useState('');const [commit,setCommit]=useState('');const [fetching,setFetching]=useState(false);
  const change=(patch:Partial<Task>)=>setDraft({...draft,...patch});
  const [channel,setChannel]=useState('');const [difficulty,setDifficulty]=useState('');
  const check=(i:number,patch:Partial<Check>)=>change({checks:draft.checks.map((c,j)=>i===j?{...c,...patch}:c)});
  const save=async(copy=false)=>{try{setDraft(await act<Task>('/tasks/save',{...draft,...(copy?{id:undefined,revision:undefined,title:draft.title+' · 副本'}:{})}));}catch{/* App displays error */}};
  const candidates=state.tasks.filter(t=>matchTask(t,kind,query,'',''));
  const matches=candidates.filter(t=>matchTask(t,kind,query,channel,difficulty));
  const dirty=JSON.stringify(draft)!==JSON.stringify(state.tasks.find(t=>t.id===draft.id));
  const list=matches.filter(t=>pendingOnly?!canStartTask(t,state.baselines):canStartTask(t,state.baselines));
  return <div className="studio-layout"><aside className="studio-library"><div className="flex justify-between"><div><span className="eyebrow">任务与环境</span><h1 className="page-title">题库<span className="count-label">{state.tasks.length}</span></h1></div><button className="btn-secondary" onClick={()=>{setDraft({...newTask(),taskParadigm:kind==='repository'?'deterministic-bugfix':kind});setSection('content');}}>新建题目</button></div><input aria-label="搜索题目" placeholder="搜索题目" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="题库类别" value={kind} onChange={e=>{setKind(e.target.value);const first=state.tasks.find(t=>matchTask(t,e.target.value,'','','')&&canStartTask(t,state.baselines));if(first){setDraft(structuredClone(first));setSection('overview');}setPendingOnly(false);}}><option value="open-ended-project">从零构建</option><option value="repository">已有仓库任务</option><option value="deterministic-bugfix">仅 Bug 修复</option></select>
    <TaskFilters tasks={candidates.filter(t=>pendingOnly?!canStartTask(t,state.baselines):canStartTask(t,state.baselines))} channel={channel} difficulty={difficulty} onChannel={setChannel} onDifficulty={setDifficulty}/>
    <div className="catalog-switch"><button className={!pendingOnly?'active':''} onClick={()=>setPendingOnly(false)}>起点就绪 · {matches.filter(t=>canStartTask(t,state.baselines)).length}</button><button className={pendingOnly?'active':''} onClick={()=>setPendingOnly(true)}>待补全 · {matches.filter(t=>!canStartTask(t,state.baselines)).length}</button></div>
    <Details title="恢复归档题目">{state.archivedTasks.map(t=><button key={t.id} className="btn-secondary mr-2" onClick={()=>act<Task>(`/tasks/${t.id}/archive`,{revision:t.revision,archived:false}).then(setDraft).catch(()=>{})}>{t.title} · 恢复</button>)}</Details>
    <div className="studio-list">{list.map(t=><button className={'list-card '+(t.id===draft.id?'selected':'')} key={t.id} onClick={()=>{setDraft(structuredClone(t));setSection('overview');}}><strong>{t.title}</strong><span>{t.difficulty} · {t.sourceKind==='deepswe'?'DeepSWE · 固定仓库':t.sourceKind==='repository-original'?'内置完整题包':'需求题面'}</span><small>{t.baselineId?'源码自动复制':needsBaseline(t)?'缺少源码起点':'从零构建'}</small></button>)}</div>
    {!list.length&&<Empty>{pendingOnly?'没有待补全题面。':'没有符合条件的可开始题目。'}</Empty>}
  <div className="library-actions"><button className="btn-secondary" onClick={()=>setSourcesOpen(true)}>浏览 DeepSWE 题目</button></div><Dialog title="DeepSWE · 选择已有工程题" open={sourcesOpen} onClose={()=>setSourcesOpen(false)}><PublicTaskSources state={state} act={act} onUse={id=>{setSourcesOpen(false);onUse(id);}}/></Dialog></aside><div className="studio-editor"><header className="editor-heading"><div><span className="eyebrow">{draft.sourceKind==='repository-original'?'内置题包':draft.taskParadigm==='deterministic-bugfix'?'工程修复':'项目构建'} · v{draft.revision}</span><h2>{draft.title||'新建题目'}</h2></div><button className="btn-primary" disabled={!draft.id||!canStartTask(draft,state.baselines)} onClick={async()=>{try{const t=dirty?await act<Task>('/tasks/save',draft):draft;setDraft(t);onUse(t.id);}catch{}}}>{dirty?'保存并选用':'选用此题'}</button></header>
    <nav className="section-nav" aria-label="题目分区">{[['overview','题目概览'],['content','编辑需求'],['checks','验收与步骤'],['source','源码与导入']].map(([id,label])=><button type="button" key={id} aria-current={section===id?'page':undefined} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</nav>
    <section hidden={section!=='overview'} className="task-overview editor-body"><div className="reading-copy"><h3>要完成什么</h3><p className="task-prompt">{draft.inputPrompt||'先在“编辑需求”填写题目。'}</p>{draft.projectSpec&&<Details title="项目要求"><ContractView task={draft}/></Details>}</div><TaskEnvironment task={draft} baselines={state.baselines}/></section>
    <form className="editor-body space-y-4" hidden={section==='overview'} onSubmit={e=>{e.preventDefault();void save();}}>
      <fieldset hidden={section!=='content'} disabled={section!=='content'} className="editor-section">
      <Field label="题目名称"><input required value={draft.title} onChange={e=>change({title:e.target.value})}/></Field>
      <div className="grid sm:grid-cols-3 gap-4"><Field label="题目类别"><select value={draft.taskParadigm} onChange={e=>change({taskParadigm:e.target.value})}><option value="open-ended-project">项目构建</option><option value="deterministic-bugfix">Bug 修复</option></select></Field><Field label="难度"><select value={draft.difficulty} onChange={e=>change({difficulty:e.target.value})}>{[...new Set([draft.difficulty,'Easy','Medium','Hard','Nightmare'])].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="任务方向"><select value={draft.channel} onChange={e=>change({channel:e.target.value})}><option value="frontend-ui">应用与界面</option><option value="deepswe-core">功能与工程</option><option value="architecture-constraint">架构与约束</option><option value="interactive-confirm">协作与多轮</option></select></Field></div>
      <Field label="总体需求"><textarea required rows={8} value={draft.inputPrompt} onChange={e=>change({inputPrompt:e.target.value,...(draft.stages.length===1?{stages:[{...draft.stages[0],prompt:e.target.value}]}:{})})}/></Field>
      <ContractEditor task={draft} onChange={change} rubrics={state.rubricCatalog}/>
      </fieldset><fieldset hidden={section!=='checks'} disabled={section!=='checks'} className="editor-section"><label className="check-row"><input type="checkbox" checked={draft.hasFrontendUI} onChange={e=>change({hasFrontendUI:e.target.checked})}/>包含界面，需要交互与视觉证据</label>
      <Details title={`逐轮提示词 · ${draft.stages.length} 阶段`}>
        <p className="muted">默认提供完整需求，不限定对话轮数。选择分阶段评测时，才使用下列步骤提示词。</p>
        {draft.stages.map((s,i)=><div key={i} className="panel-subtle p-3 space-y-2"><Field label={`第 ${i+1} 轮名称`}><input required value={s.title} onChange={e=>change({stages:draft.stages.map((v,j)=>i===j?{...v,title:e.target.value}:v)})}/></Field><Field label="本轮提示词"><textarea required rows={4} value={s.prompt} onChange={e=>change({stages:draft.stages.map((v,j)=>i===j?{...v,prompt:e.target.value}:v)})}/></Field>{draft.stages.length>1&&<button className="btn-ghost" type="button" onClick={()=>change({stages:draft.stages.filter((_,j)=>j!==i)})}>移除此轮</button>}</div>)}
        <button className="btn-secondary" type="button" onClick={()=>change({stages:[...draft.stages,{title:'下一阶段',prompt:''}]})}>增加阶段</button>
      </Details>

      <Details title={`容器验收检查 · ${draft.checks.length} 项`}>
        <p className="muted">镜像必须预先在本机准备；检查在无网络容器的产物副本执行。可用自有测试镜像保护验收逻辑，不把答案放进题目起点。</p>
        <Field label="复用已有题目的检查方案" hint="复用命令和镜像，不复制原题的需求关联；阶段统一设为最终交付。请核对本题目录、依赖与预期后保存。"><select value="" onChange={e=>{const source=state.tasks.find(t=>t.id===e.target.value);if(source)change({checks:[...draft.checks,...source.checks.map(c=>({...c,id:'check-'+crypto.randomUUID(),criterionIds:[],stageIndex:undefined,runOnFinal:false}))]});}}><option value="">选择已配置检查的题目</option>{state.tasks.filter(t=>t.id!==draft.id&&t.checks.length>0).map(t=><option key={t.id} value={t.id}>{t.title} · {t.checks.length} 项</option>)}</select></Field><p className="muted">可复用构建/类型/测试命令。没有专用脚本也可使用机器评分；裁判主动取证，人工按需修正。</p>
        {draft.checks.map((c,i)=><div className="panel-subtle p-3 space-y-3" key={i}><div className="grid sm:grid-cols-2 gap-3"><Field label="检查名称"><input required value={c.label} onChange={e=>check(i,{label:e.target.value})}/></Field><Field label="Docker 镜像"><input required value={c.image} onChange={e=>check(i,{image:e.target.value})}/></Field></div>
        <Field label="命令参数数组（JSON）" hint={'例如 ["python","-I","/tests/verify.py","/app"]。不执行宿主命令。'}><CommandArgs key={draft.id+'-'+draft.revision+'-'+i} label={`检查 ${i+1} 命令参数`} value={c.argv} onChange={argv=>check(i,{argv})}/></Field>
        <div className="grid grid-cols-3 gap-3"><Field label="检查权重（相对份数）"><input type="number" min={1} max={100} value={c.weight} onChange={e=>check(i,{weight:Number(e.target.value)})}/></Field><Field label="超时秒数"><input type="number" min={1} max={600} value={c.timeout||120} onChange={e=>check(i,{timeout:Number(e.target.value)})}/></Field><Field label="验收阶段"><select value={c.stageIndex??'final'} onChange={e=>check(i,{stageIndex:e.target.value==='final'?undefined:Number(e.target.value)})}><option value="final">最终交付</option>{draft.stages.map((s,j)=><option key={j} value={j}>{j+1}. {s.title}</option>)}</select></Field></div><Field label="检查类别"><select value={c.kind||'other'} onChange={e=>check(i,{kind:e.target.value})}><option value="functional">功能</option><option value="build">构建 / 类型</option><option value="rule">规则</option><option value="other">其他（未分类）</option></select></Field><label className="check-row"><input type="checkbox" checked={c.runOnFinal||false} onChange={e=>check(i,{runOnFinal:e.target.checked})}/>最终交付时重新运行此检查</label><Details title="关联验收条目">{draft.criteria?.map(row=><label key={row.id} className="check-row"><input type="checkbox" checked={c.criterionIds?.includes(row.id)||false} onChange={e=>check(i,{criterionIds:e.target.checked?[...(c.criterionIds||[]),row.id]:(c.criterionIds||[]).filter(id=>id!==row.id)})}/>{row.label}</label>)}</Details><button className="btn-ghost" type="button" onClick={()=>change({checks:draft.checks.filter((_,j)=>i!==j)})}>移除检查</button></div>)}
        <button className="btn-secondary" type="button" onClick={()=>change({checks:[...draft.checks,{id:'check-'+crypto.randomUUID(),label:'',image:'',argv:[],weight:1,timeout:120}]})}>添加检查</button>
      </Details>
      </fieldset><fieldset hidden={section!=='source'} disabled={section!=='source'} className="editor-section">
      <label className="check-row"><input type="checkbox" checked={!!needsBaseline(draft)} disabled={draft.taskParadigm==='deterministic-bugfix'} onChange={e=>change({requiresBaseline:e.target.checked})}/>需要已有工程源码（修复、重构或扩展）</label><Field label="运行环境说明"><textarea rows={3} value={draft.environmentNote||''} onChange={e=>change({environmentNote:e.target.value})} placeholder="运行时、依赖与已有测试命令"/></Field><Field label="起点文件快照"><select value={draft.baselineId||''} onChange={e=>change({baselineId:e.target.value||undefined})}><option value="">空工作区</option>{state.baselines.map(b=><option key={b.id} value={b.id}>{b.name} · {b.manifest.sha256.slice(0,8)}</option>)}</select></Field>
      <Details title="来源与许可"><Field label="来源说明"><textarea value={draft.sourceNote||''} onChange={e=>change({sourceNote:e.target.value})}/></Field><Field label="参考链接（不会自动下载）"><input value={draft.referenceUrl||''} onChange={e=>change({referenceUrl:e.target.value})}/></Field><Field label="许可声明"><input value={draft.license||''} onChange={e=>change({license:e.target.value})}/></Field><p className="muted">Gemini 导入题目保留题面；其中参考仓库和测试建议尚未证明可执行。不以题目数量宣称覆盖率。</p></Details>
      </fieldset><div className="editor-footer"><button className="btn-primary">保存题目版本</button><button type="button" className="btn-secondary" onClick={async e=>{if(!e.currentTarget.form?.reportValidity())return;try{const t=await act<Task>('/tasks/save',draft);setDraft(t);onUse(t.id);}catch{/* Global error */}}}>保存并用于评测</button>{draft.id&&<><button type="button" className="btn-secondary" onClick={e=>{if(e.currentTarget.form?.reportValidity())void save(true);}}>另存新题</button><button type="button" className="btn-ghost" onClick={()=>act(`/tasks/${draft.id}/archive`,{revision:draft.revision,archived:true}).then(()=>setDraft(newTask())).catch(()=>{})}>归档题目</button></>}</div>
    </form>
  <div hidden={section!=='source'} className="editor-body space-y-4"><TaskImport act={act} onImported={t=>{setDraft(t);setKind(needsBaseline(t)?'repository':'open-ended-project');setQuery('');setChannel('');setDifficulty('');}}/><Panel title="自定义源码起点"><form className="space-y-3" onSubmit={e=>{e.preventDefault();act<{id:string}>('/baselines/import',{path}).then(b=>{change({baselineId:b.id});setPath('');}).catch(()=>{});}}><Field label="源文件夹绝对路径" hint="导入为新快照，原文件夹不会被修改。凭据、依赖目录及 Git 元数据不会复制。"><input required value={path} onChange={e=>setPath(e.target.value)}/></Field><button className="btn-secondary">导入并选作起点</button></form><Details title="从公开 GitHub 仓库下载起点"><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setFetching(true);try{const b=await act<{id:string;sourceUrl:string;sourceCommit:string}>('/baselines/import-github',{url:repoUrl,commit});setDraft(current=>current.id===draft.id&&current.revision===draft.revision?{...current,baselineId:b.id,referenceUrl:b.sourceUrl,sourceNote:`源码起点 ${b.sourceUrl} @ ${b.sourceCommit}；依赖需在工作区准备。`}:current);}catch{}finally{setFetching(false);}}}><Field label="GitHub 仓库"><input required type="url" value={repoUrl} onChange={e=>setRepoUrl(e.target.value)} placeholder="https://github.com/owner/repository"/></Field><Field label="题目起始提交（40 位 SHA）"><input required pattern="[0-9a-fA-F]{40}" value={commit} onChange={e=>setCommit(e.target.value)}/></Field><button className="btn-secondary" disabled={fetching}>{fetching?'正在下载与冻结…':'下载并选作起点'}</button><p className="muted">固定源码版本，随后保存题目。依赖尚未安装；不会自动执行仓库脚本。</p></form></Details></Panel></div></div></div>;
}

function CommandArgs({label,value,onChange}:{label:string;value:string[];onChange:(argv:string[])=>void}){
  const [raw,setRaw]=useState(JSON.stringify(value));const [error,setError]=useState('');
  useEffect(()=>{setRaw(JSON.stringify(value));setError('');},[value]);
  return <><input aria-label={label} value={raw} required ref={el=>el?.setCustomValidity(error)} onChange={e=>{
    setRaw(e.target.value);let message='';
    try{const argv:unknown=JSON.parse(e.target.value);if(!Array.isArray(argv)||!argv.length||!argv.every(v=>typeof v==='string')||!argv[0].trim())throw new Error();onChange(argv);}
    catch{message='命令需为非空 JSON 字符串数组，请修正后保存。';}
    e.target.setCustomValidity(message);setError(message);
  }}/>{error&&<small role="alert" className="alert-error">{error}</small>}</>;
}
