import {useState} from 'react';
import type {Act,Run} from './types';
import {request} from './api';
import {DeleteEvaluation} from './DeleteEvaluation';
import {Dialog,Field} from './ui';

type Workspace={runId:string;trialId:string;revision:number;title:string;workspacePath:string;canClean:boolean;canDeleteRun:boolean;cleanup?:{status:string}};
type Inventory={workspaces:Workspace[]};

export function EvaluationManagement({run,act}:{run:Run;act:Act}){
  const [open,setOpen]=useState(false),[rows,setRows]=useState<Workspace[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [selected,setSelected]=useState<{row:Workspace;action:'trash'|'restore'|'purge'}|null>(null);
  const [stopped,setStopped]=useState(false),[confirmation,setConfirmation]=useState('');
  const refresh=async()=>{setLoading(true);setError('');try{const data=await request<Inventory>('/storage/status',{});setRows(data.workspaces.filter(row=>row.runId===run.id));}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  const choose=(row:Workspace,action:'trash'|'restore'|'purge')=>{setSelected({row,action});setStopped(false);setConfirmation('');setError('');};
  const apply=async()=>{if(!selected)return;setLoading(true);try{const result=await act<Inventory>('/storage/workspace',{runId:run.id,trialId:selected.row.trialId,revision:selected.row.revision,action:selected.action,desktopStopped:stopped,confirmation});setRows(result.workspaces.filter(row=>row.runId===run.id));setSelected(null);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  return <div className="history-management"><button type="button" className="btn-ghost" aria-expanded={open} onClick={()=>{setOpen(!open);if(!open)void refresh();}}>{open?'收起清理与删除':'清理工作区 / 删除评测'}</button>{open&&<div className="history-management-body"><p className="muted">工作区文件与评测记录分开管理。清理工作区先移入待删除区，可恢复；永久删除工作区后仍保留快照、评分和历史。删除整次评测会连同这些记录及其文件一起删除。</p>{loading&&<p role="status">正在核对本次目录…</p>}{error&&<p role="alert" className="alert-error">{error}</p>}{rows.map(row=><div className="history-workspace" key={row.trialId}><div><strong>{row.title}</strong><small className="break-all">{row.workspacePath}</small><span>{row.cleanup?.status==='deleted'?'工作区已永久删除':row.cleanup?.status==='trashed'?'工作区待删除':row.canClean?'可清理工作区':'需先回收产物并结束交付'}</span></div><div className="source-actions">{row.cleanup?.status==='deleted'?<span className="muted">文件已清理</span>:['trashed','deleting'].includes(row.cleanup?.status||'')?<><button type="button" className="btn-secondary" disabled={loading||row.cleanup?.status==='deleting'} onClick={()=>choose(row,'restore')}>恢复工作区</button><button type="button" className="btn-danger" disabled={loading} onClick={()=>choose(row,'purge')}>永久删除工作区文件</button></>:<button type="button" className="btn-secondary" disabled={loading||!row.canClean} onClick={()=>choose(row,'trash')}>清理工作区文件</button>}</div></div>)}{rows.length>0&&<DeleteEvaluation runId={run.id} revision={rows[0].revision} canDelete={rows.every(row=>row.canDeleteRun)} act={act} onDeleted={()=>setOpen(false)}/>}<p className="muted">本站只能删除项目管理的目录和记录，不能自动删除 Codex 桌面侧栏中的任务、对话或手动导出的 ZIP。</p></div>}
    <Dialog title={selected?.action==='purge'?'永久删除工作区文件':selected?.action==='restore'?'恢复工作区':'清理工作区文件'} open={!!selected} onClose={()=>setSelected(null)}>{selected&&<div className="space-y-4"><strong>{selected.row.title}</strong><p className="break-all">{selected.row.workspacePath}</p><p>{selected.action==='trash'?'整个工作目录移入待删除区，之后可恢复；此时磁盘空间尚未释放。':selected.action==='restore'?'将工作目录移回原位置。':'永久删除待删除区中的整个工作目录。'}评测记录、冻结快照和评分仍保留。</p>{error&&<p role="alert" className="alert-error">{error}</p>}{selected.action==='trash'&&<label className="check-row"><input type="checkbox" checked={stopped} onChange={e=>setStopped(e.target.checked)}/>Codex 桌面已停止写入这个工作区</label>}{selected.action==='purge'&&<Field label="输入“永久删除工作区”确认"><input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></Field>}<button type="button" className={selected.action==='purge'?'btn-danger':'btn-primary'} disabled={loading||selected.action==='trash'&&!stopped||selected.action==='purge'&&confirmation!=='永久删除工作区'} onClick={()=>void apply()}>确认{selected.action==='purge'?'永久删除':selected.action==='restore'?'恢复':'移入待删除区'}</button></div>}</Dialog>
  </div>;
}
