import {useState} from 'react';
import type {State,Act} from './types';
import {Details} from './ui';
import {PublicTaskSources} from './PublicTaskSources';
import {BenchmarkMethods} from './BenchmarkMethods';

export function Guide({state,act,onUse}:{state:State;act:Act;onUse:(id:string)=>void}){
  const [section,setSection]=useState('purpose');
  return <div className="guide-page">
    <header className="guide-heading"><span className="eyebrow">CODEX HARNESS BENCH</span><h1>让模型更好合作，而不只是更会做题。</h1><p>能听懂你的重点，说清有用的答案，把问题解决。你的规则和 Skills，是否真的让这些事变好了？</p></header>
    <nav className="section-nav" aria-label="方法说明分区">{[['purpose','为什么测 Harness'],['workflow','怎样测、怎样看分'],['sources','题库与公开来源'],['methods','方法与证据']].map(([id,label])=><button key={id} className={section===id?'active':''} aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}>{label}</button>)}</nav>
    {section==='purpose'&&<div className="guide-content">
      <section className="guide-intro reading-copy"><h2>为什么它很忙，你却越来越累？</h2><p>你问怎么解决，它解释了半天还没答到点。你纠正了方向，它说“好的”，下一轮又走回原路。一个小功能长出多层架构，一次修复多出几个脚本；你要改善页面，它却把开发要求当成文案摆了上去。</p><p>这些才是我们做这个项目的起因：固定同一个模型，看看个人规则与 Skills 能否减少绕弯、无用工程和重复提醒。模型基础能力在同条件下相对固定，配置有没有帮助，要看改了以后发生什么。即使解决不了，也要指出哪里差、差了几次、额外耗费多少。</p><p>所以评测不能只看代码和截图，还要看你与模型怎样交流。有没有听懂、能否接受纠正、该问时问清、不该打断时推进。产物九十多分，不能替你回答“用起来到底省不省心”。</p></section>
      <div className="harness-layers" aria-label="评测对象三层结构"><section><span>01 · 基础条件</span><h2>Codex 桌面底座</h2><p>桌面提供的执行循环、工具、上下文管理与产品行为。记录版本及宿主条件。</p></section><section><span>02 · 模型条件</span><h2>模型与推理档位</h2><p>比较个人配置时尽量保持相同；换模型时，结果解释为组合差异。</p></section><section className="personal-layer"><span>03 · 主要比较变量</span><h2>你的个人配置</h2><p>AGENTS 规则、Skills、交互约定，以及工作台支持的原生设置和工具开关。</p></section></div>
      <section className="guide-two-column"><div><h2>先问一个具体问题，再开始对照</h2><p>例如：“删去重复的审查规则，能否在不降低交付成功率的前提下减少 Token？”把当前配置作为 A，选择同模型、同档位、同速度的 B，或创建精简副本。冻结题集、预算与重复次数，交错准备 A/B、B/A 工作区。</p></div><div><h2>跑分漂亮，不等于项目好用</h2><p>先看预算内交付成功、失败和未知，再看包括失败尝试的资源开销。源码变多不直接等于过度工程化，AI 高分也不自动等于完整交付成功。合理抽象有没有带来收益，要放在同题对照里判断。</p></div></section>
      <Details title="公开 Benchmark 能不能直接拿来测 Harness？"><p>可以借用题目、固定环境和原题验收器，但要组织成同条件的配对实验。SWE-bench、Terminal-Bench 等 Agent 基准本身也包含 Harness，并不是都在测“裸模型”。本项目关注个人配置的变化，因此要记录全部尝试和预算，不能把本地 AI 分数冒充官方成绩。</p></Details>
      <Details title="人机沟通具体测什么？"><p>每个明确请求算一次观察机会：首次回应有没有解决核心问题？纠正后是否落实，后来有没有复发？追问是必要澄清，还是重复问已经给过的答案？回答是否让指定读者知道结论和下一步？这些都要引用真实回合，不能从交接文档推断。</p><p>过度工程化则看改动是否服务于目标、有没有把一次修复变成多层补丁、验证是否发现并解决了缺陷。代码多不自动判差，测试多不自动加分。内部要求混入产品文案，需要看实际可见页面。</p><p>新回收会封存本题绑定会话的可见文本；已有独立裁判可逐回合检查切题、纠正后的回答与不必要打断，列出次数和双方原话。缺图或截断回合保持未知，代码是否改好仍看产物验收。语义判定尚未完成独立样本校准；范围扩张、复发和匿名表达偏好仍属后续测量。现有“协作与交付”轴混合了旧沟通项、阶段推进和交接，不代表上述人机沟通指标已经测过。详细开源方法见“方法与证据”。</p></Details>
      <Details title="哪些条件会影响比较"><p>模型、推理档位、桌面版本、源码和依赖版本、继承的全局规则与工具、人工介入、裁判及评分标准都会影响结果。独立工作区保存起点和产物，但仍可能继承桌面的全局设置。配置成绩按冻结版本分组；同模型同题、相同评分协议下的差异才更适合解释为个人 Harness 改动。</p></Details>
    </div>}
    {section==='methods'&&<BenchmarkMethods/>}
    {section==='workflow'&&<div className="guide-content">
      <div className="guide-two-column"><section><h2>一次对照，四步完成</h2><ol className="guide-steps"><li><strong>选配置和任务</strong><p>选题后，在配置步骤开启同模型对照，保存 A/B 版本、改动假设、预算与重复次数；题库说明起点和环境要求。</p></li><li><strong>准备并在桌面执行</strong><p>系统交错准备独立工作区。应用对应配置后核对实际模型、档位和速度，再发送完整需求；不会自动替你发送整组桌面对话。</p></li><li><strong>回收并收集验收证据</strong><p>停止写入后回收快照，运行题目支持的程序验收；需要质量意见时另启独立裁判，保存原始报告和证据。</p></li><li><strong>比较收益与代价</strong><p>查看配对结果、失败和资源记录。实际执行条件缺失或不一致时保留观测结果，不把差异贸然归因给 Harness；有异议可按项复核。</p></li></ol></section><section><h2>三类结果，各自回答一个问题</h2><div className="grading-methods"><article><h3>程序验收 · 它真的做到了吗？</h3><p>运行已有测试或题包验收器，记录通过、失败和输出。用于确认具体行为，不能单独代表完整质量。</p></article><article><h3>独立 AI · 交付质量怎么样？</h3><p>默认 GPT-6-Luna / max，另启 CLI 裁判，不恢复解题会话，也不由当前开发对话代评。读取需求、产物副本及本次回收的对话文本，按冻结量表取证；每次调用会消耗所用账号额度。</p></article><article><h3>人工复核 · 实际体验是否吻合？</h3><p>评分页选择“人工复核”，浏览文件和图片，创建独立副本运行界面，再记录人工参考分。即使 AI 未成功也可评价；对机器分有异议仍可按项修正。</p></article></div></section></div>
      <section className="guide-two-column"><div><h2>基准验证</h2><p>固定题目、源码和验收条件，以原题程序或公开判分协议为主。AI 质量意见单列；没接通原验收器时不生成原榜单成绩。</p></div><div><h2>真实项目交付</h2><p>只带一个想法也能开始，让 AI 逐步把它做成可用作品；不要求你先写完整规格。按实际需求、运行证据和体验评价，接受多种合理实现。当前按公开题源 / 程序验收识别基准验证，其余采用项目质量视角；这是判分依据分类，不是 Bug 与新建项目的分类。</p></div></section><p className="score-notice">评分仅供参考，不代表模型的全部能力或你的每次真实体验。基准表现与使用感受可能不同；AI 及人工判定有主观性，需要重复任务与证据复核。</p>
      <Details title="总分与评分证据怎么看"><p>“结果总览”直接列单题总分及计算。已接通连续评分卡的 SWE 题，程序贡献最多 90 分、AI 可维护性贡献最多 10 分；原题通过 / 未通过另列。开放项目由 AI 分项按冻结权重汇总，程序失败会限制对应验证项，不把脚本均分与 AI 均分再平均。</p><p>“配置成绩”先平均同题重复，再对不同题等权平均。题集未齐时显示已评分题均分及 n/m 题覆盖，打开配置卡能看到每道题是否参与计算。只有原题结果而没有本地连续卡的记录，进入单独的原题通过率统计。</p><p>对话材料在“AI 评分 → 标准与验收 → AI 裁判使用的对话证据”查看，由同一次 AI 裁判判定。沟通维度只有在本题冻结方案中有权重时才参与总分和对应雷达轴；逐回合记录供其引用，不另加一个沟通总分。</p></Details>
      <Details title="分数、权重与未验证项"><p>新建评测按题型自动选评分卡，一题一个本地综合分。开放项目分为目标与范围 60、实际使用与可靠性 25、交付可维护性 15；具体项随网页、工程、业务、长期或协作题变化。已接通连续评分卡的 DeepSWE 题按目标语义组 70、回归 20、可维护性 10 计算；目前有五道固定题卡。原题通过/未通过另列，无连续卡的题不臆造100分总分。准备页可查看所选题目的实际项与权重；只有特殊任务才在高级区改用自定义方案。</p><div className="guide-weights"><div><span>目标与范围</span><strong>60%</strong></div><div><span>实际使用与可靠性</span><strong>25%</strong></div><div><span>交付与可维护性</span><strong>15%</strong></div></div><p>新 AI 审查逐条核对原题需求，按覆盖、质量、韧性等细项给 0–4 等级，由程序算分，不再追加 extra；最高等级需要反例检查证据。未验证不补零，引用存在也不保证裁判理解正确。适用项和必要检查齐全即可显示单题参考分，未结束交付标“暂定”，多阶段仍需最终验收。人工修正保留机器原分；六轴只归类证据，不生成第二个总分。</p></Details>
      <Details title="只选几道题，怎样看SWE与Harness？"><p>SWE每道题先看原验收器的0/1，以及目标测试和旧功能回归的通过比例。失败是有效结果；缺环境或没运行才是未测。这些数字不需要AI再判断，可维护性等质量意见另列。已有五道本地连续卡按原冻结权重保留，其余题不会套用这五道的公式。</p><p>你可以选一组与你日常场景有关的小项目，在同模型、同题、同预算下比较规则变动，不需要跑完整题库。选题前明确要看切题、纠正、打断还是资源负担；SWE提供工程结果的底线，不能仅凭解题分说Harness好用。总览把这些使用记录放在一起，真实对话没有判定就显示未知。</p><p>开发题缺项时显示已评分贡献、剩余权重和按现有分项计算的范围。例如已确认70分、还有10分权重未知，只能显示70–80分，不能把已有项目放大为满分。范围不是AI准确率或统计误差；缺项旁的入口分别去程序验收或裁判补查。没有验收器的题会明确写明，已有源码不等于已有程序验收。</p></Details>
      <Details title="评分缺项时会怎样处理？"><p>新审查会把格式、引用和可补查的缺项反馈给同一裁判一次，沿用原来的剩余时间预算。裁判自己补取证，或把等级调整到证据实际支持的程度；平台不代填分数，也不替它修作品。</p><p>两次原报告、命令和用量都保留，补查可能再开一次CLI并消耗额度，启动处会说明。预算用完、账号变化或环境确实不支持时仍保留未知，合法低分不触发重试。旧报告不自动重评；保存原报告的本地重新校验仍不调用模型。查看“AI评分 → 评分结果 → 本次自动补查回执”可知道补查了什么。</p></Details>
      <Details title="怎么面对前端高分和裁判的随意性？"><p>只读源码或挑两三个按钮检查，都不足以证明整个页面好用。功能要核对需求和状态变化，视觉要看实际截图，动态体验要有操作证据。部分网页有专项行为检查，其余仍有覆盖缺口，AI 高分不会自动转成完整交付成功。</p><p>统一量表与证据校验是第一步，不是准确率证明。目前还没有完成的真实 A/B 校准样本，也没有跨题库的视觉实测误差。需要冻结好、坏和合理替代作品，做匿名复评、提示词扰动与保留样本验证，观察漏检和误判。最高模型的作品可以供盲评参考，不能自动设为满分；更不能因为 Luna 得分高就人为压分。</p></Details>
      <Details title="实际使用中需要知道的事"><ul className="guide-facts"><li><strong>配置应用：</strong>导入到工作台只保存副本；点击应用到 Codex 才备份并写入设置，新任务中仍需核对实际模型及覆盖关系。</li><li><strong>Docker：</strong>网站、桌面工作区和本机裁判不要求 Docker。外部题包若依赖 Linux 镜像和独立验收器，则按它的环境要求准备。</li><li><strong>界面评分：</strong>交互与视觉需要实际操作和截图证据。当前 Docker 与本机的取证能力不同，无法验证时留空；创建人工审查副本后可按说明自行启动体验。</li><li><strong>资源统计：</strong>从匹配工作区的原生日志读取 Token、缓存和活动时间；活动时间不是纯推理时间，缺失数据留空。对照预算目前按结果判断，不自动终止桌面对话。</li><li><strong>中断与数据：</strong>环境错误、额度不足不记为任务得零分。记录保存在本机，导出可能包含个人配置与产物。</li></ul></Details>
    </div>}
    {section==='sources'&&<div className="guide-content"><section className="guide-two-column"><div><h2>题目要有区别，起点要能复现</h2><p>默认32题跨类型精选只为减少重复浏览，不是正式跑分题集。从零构建与已有工程分开选择；DeepSWE 创建时只下载所选题目的固定源码，失败不会生成空工程让你做题。</p></div><div><h2>题目数量，不等于环境已就绪</h2><p>新增8道社区机制项目含77个固定核心用例，页面连接另验；HumanEval+有163道扩展测试题，1道导出有问题的题未加入可运行集合。程序验收完成即可显示，不依赖AI或结束交付。5 套内置完整题有独立验收；51 道创意网页共用基础烟检，其中 5 道另有专项检查；12 道跨类型开放题有独立起点。DeepSWE 接入 113 条定义，3 道有 Windows 原测试适配；WebGen 接入 101 题及 647 条原 UI 条件，尚未接官方 WebVoyager 验收器。具体可用性以每题声明为准。</p></div></section>
      <Details title="同一道题重复做，会不会混在一起？"><p>同一仓库和提交校验后复用缓存，不重复下载。每次评测复制到新的 run / trial / workspace，拥有自己的 Git 起点；你的修改不会写回缓存。回收快照、评分与日志独立保留，结束后可在“评测历史”清理工作区。全部位于本项目 .local/arena。</p></Details>
      <PublicTaskSources state={state} act={act} onUse={onUse}/>
      <Details title="其他公开方案与用途"><ul className="guide-facts"><li><a href="https://github.com/SWE-bench/SWE-bench" target="_blank" rel="noreferrer">SWE-bench ↗</a>：已有工程修复，按任务测试验证修复与回归。</li><li><a href="https://github.com/harbor-framework/harbor" target="_blank" rel="noreferrer">Harbor / Terminal-Bench ↗</a>：复用任务、环境和验收器格式。</li><li><a href="https://github.com/WebPAI/DesignBench" target="_blank" rel="noreferrer">DesignBench ↗</a>：前端生成、编辑和修复的专项评测参考。</li><li><a href="https://github.com/metauto-ai/agent-as-a-judge" target="_blank" rel="noreferrer">Agent-as-a-Judge ↗</a>：开放需求的工具取证与判定参考。</li></ul></Details>
    </div>}
  </div>;
}
