import {useState} from 'react';
import {JudgeProgress} from './JudgeProgress';
import type {Trial,Run,State} from './types';
import {Panel,Details,Dialog,Field,ScoreSlider,num,date,ModelSelect} from './ui';
import {ScoreRing,ScoreBar} from './AssessmentCharts';
import {verdicts} from './Contracts';
import {isBenchmark} from './EvaluationTrack';
import {scoredDimensions,scoreRubrics} from './autoScorecard';
import {request} from './api';

function ReviewScreenshots({runId,trialId,reviewId}:{runId:string;trialId:string;reviewId?:string}){
  const [names,setNames]=useState<string[]|null>(null);
  const [selected,setSelected]=useState('');
  const [image,setImage]=useState('');
  const [error,setError]=useState('');
  const [loading,setLoading]=useState(false);
  const route=`/runs/${runId}/trials/${trialId}/judge-screenshots`;
  const list=async()=>{setLoading(true);setError('');try{const result=await request<{images:string[]}>(route,{reviewId});setNames(result.images);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  const show=async(path:string)=>{setSelected(path);setImage('');setLoading(true);setError('');try{const result=await request<{image:string}>(route,{reviewId,path});setImage(result.image);}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  return <Details title="裁判保存的页面截图 · 人工核对"><p className="muted">截图来自本次隔离审查，可直接核对页面布局、中文显示和窄屏效果。截图存在只证明浏览器保存了画面，不证明 AI 实际看过图片或审美判断正确。</p>{names===null?<button type="button" className="btn-secondary" disabled={loading} onClick={()=>void list()}>{loading?'读取中…':'查看保存的截图'}</button>:names.length===0?<p className="muted">这份裁判报告没有保存可预览的截图。</p>:<><Field label={`截图 · ${names.length} 张`}><select value={selected} disabled={loading} onChange={e=>void show(e.target.value)}><option value="">选择一张截图</option>{names.map(name=><option key={name} value={name}>{name.split('/').pop()}</option>)}</select></Field>{image&&<img className="review-screenshot" src={image} alt={`裁判保存的页面截图：${selected.split('/').pop()}`}/>}</>}{error&&<p role="alert" className="alert-error">{error}</p>}</Details>;
}

export function MachineScore({run,trial:t,state,act,disabled}:{run:Run;trial:Trial;state:State;act:(name:string,data?:unknown)=>Promise<unknown>;disabled:boolean}){
  const latest=t.captures[t.captures.length-1];
  const task=run.tasks.find(task=>task.id===t.taskId)!;
  const defaultJudgeModel='gpt-6-luna';
  const [model,setModel]=useState(defaultJudgeModel);
  const [reasoning,setReasoning]=useState('max');
  const [serviceTier,setServiceTier]=useState<'standard'|'fast'>('standard');
  const [minutes,setMinutes]=useState(60);
  const [usageAcknowledged,setUsageAcknowledged]=useState(false);
  const modelInfo=state.models.find(m=>m.id===model);
  const [environment,setEnvironment]=useState(task.hasFrontendUI?'docker':'local');
  const efforts=(modelInfo?.reasoningLevels||[]).filter(level=>environment!=='docker'||level!=='ultra');
  const judgeSupported=!!model&&(!reasoning||efforts.includes(reasoning))&&(serviceTier!=='fast'||(environment==='local'&&!!modelInfo?.fastAvailable));
  const [editing,setEditing]=useState<string|null>(null);const [value,setValue]=useState('');const [reason,setReason]=useState('');
  const [editingEvidence,setEditingEvidence]=useState<{reviewId?:string|null;evidenceKey?:string|null}>({});
  const report=t.reviews.find(r=>r.id===t.score.machineReviewId);
  const [view,setView]=useState<'result'|'review'|'standards'>(report?'result':'review');
  const busy=['checking','judging'].includes(t.state);
  const judging=t.state==='judging';
  const judgeError=t.lastJobError?.kind==='judge'?t.lastJobError:null;
  const ratings=t.score.machineRatings||{};
  const rated=Object.values(ratings).filter(rating=>rating.score!=null);
  const runtimeRated=rated.filter(rating=>rating.method==='runtime').length;
  const intermediate=latest.stageIndex+1<task.stages.length&&t.finalCaptureId!==latest.id;
  const correct=async(withdraw=false)=>{if(!editing)return;await act('machine-correction',{...editingEvidence,changes:{[editing]:{score:withdraw?null:Number(value),reason}}});setEditing(null);};
  const weights=scoredDimensions(run.policy,task);
  const rubrics=scoreRubrics(run.policy,task);
  const dimensions=Object.entries(rubrics).filter(([key])=>key in weights);
  return <Panel title={intermediate?'阶段检查（可选）':isBenchmark(task)?'AI 质量参考 · 不计原题通过率':t.score.taskScorecard?'本地单题评分 · AI 取证':'AI 交付质量参考'} aside={<span className="muted">回收版本 {t.captures.length} · {judging?'正在评分':report?'已生成评分':judgeError?'评分未完成':'尚未评分'}</span>}>
    <p className="muted mb-3">{intermediate?`只检查第 ${latest.stageIndex+1} 阶段的已回收版本，不计整题最终成绩。整题已完成时，可直接在下方结束交付，再按完整需求评分。`:task.publicSource?'AI 审查提供工程质量补充，不决定原题通过或未通过。本地连续分还需要当前快照的原题验收报告；已有本地连续卡的题，可维护性占 10 分；尚无卡的题只保留质量意见。历史或自定义方案按冻结规则保留。':'按完整需求检查当前回收版本。对话次数不限；各适用项有分即可显示暂定单题分，交付结束且有独立任务验收支撑时，才可能计入配置对比。'}</p>
    <nav className="review-navigation" aria-label="AI 评分分区">{([['result','评分结果'],['review','启动与过程'],['standards','标准与验收']] as const).map(([id,label])=><button type="button" key={id} aria-pressed={view===id} className={view===id?'selected':''} onClick={()=>setView(id)}>{label}</button>)}</nav>
    <div className="review-section space-y-4" hidden={view!=='review'}>
    <div className="judge-toolbar">
      <Field label="裁判模型"><ModelSelect label="裁判模型" disabled={busy||disabled} value={model} onChange={id=>{setModel(id);const next=state.models.find(m=>m.id===id);setReasoning(next?.reasoningLevels?.includes(reasoning)?reasoning:next?.reasoningLevels?.includes('medium')?'medium':'');if(!next?.fastAvailable)setServiceTier('standard');}} models={state.models}/></Field>
      <Field label="裁判思考档位"><select disabled={busy||disabled} value={reasoning} onChange={e=>setReasoning(e.target.value)}><option value="">模型默认（不强制档位）</option>{efforts.map(level=><option key={level}>{level}</option>)}</select></Field>
      <Field label="裁判速度"><select disabled={busy||disabled} value={serviceTier} onChange={e=>setServiceTier(e.target.value as 'standard'|'fast')}><option value="standard">标准</option><option value="fast" disabled={environment!=='local'||!modelInfo?.fastAvailable}>Fast · {environment!=='local'?'仅本机 CLI':modelInfo?.fastAvailable?'当前模型可用':'模型未声明支持'}</option></select></Field>
      <Field label="审查时间预算"><select disabled={busy||disabled} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{[15,30,60,120,240,480].map(n=><option key={n} value={n}>{n<60?n+' 分钟':n/60+' 小时'}</option>)}</select></Field>
      <Field label="裁判环境"><select aria-label="裁判环境" value={environment} disabled={busy||disabled} onChange={e=>{setEnvironment(e.target.value);if(e.target.value==='docker'){if(reasoning==='ultra')setReasoning('');setServiceTier('standard');}}}><option value="local">本机 · 无需 Docker</option><option value="docker">Docker · Harbor 隔离</option></select></Field>
      <button className="btn-primary" disabled={disabled||busy||!judgeSupported||!usageAcknowledged} onClick={()=>{setUsageAcknowledged(false);void act('judge',{captureId:latest.id,model,reasoningEffort:reasoning,serviceTier,timeoutSeconds:minutes*60,environment,usageAcknowledged:true}).catch(()=>{});}}>{judging?'检查中…':intermediate?`检查第 ${latest.stageIndex+1} 阶段`:report?'重新评分':judgeError?'重试评分':'评估最终产物'}</button>
      {judging&&<button disabled={disabled} className="btn-secondary" onClick={()=>void act('stop').catch(()=>{})}>停止</button>}
    </div>
    <label className="judge-usage-consent"><input type="checkbox" checked={usageAcknowledged} disabled={disabled||busy} onChange={e=>setUsageAcknowledged(e.target.checked)}/><span>我确认本次将新开 Codex CLI 裁判并消耗当前登录账号额度；同一时间预算内最多自动补查一次，可能再开一次 CLI 并消耗额度；时间预算不是 Token 或额度上限。</span></label>
    <p className="muted">缺项或引用问题会自动反馈给裁判补查；平台不代填分数。预算用完保留未完成项。</p>
    {task.hasFrontendUI&&environment==='local'&&<p className="score-notice">此题需要实际打开界面取证；当前 Windows 本机裁判不能启动浏览器，网页体验项会保持未验证。请选择 Docker 裁判并先准备专用镜像。</p>}
    <Details title="裁判、账号与检查范围"><p>默认使用 {defaultJudgeModel} · max。模型目录只说明客户端认识该模型，不保证当前登录账号有调用权限；更换裁判模型或档位会改变可比条件。</p><p>当前连接：{state.reviewConnection?.provider||'待读取'} · {state.reviewConnection?.billing||'请核对 Codex CLI 登录'}。新审查读取启动时的凭据；运行中不换号。</p><ol className="storage-flow"><li>读取原始需求、适用评分标准与当前回收快照。</li><li>查看代码，尝试构建与测试，收集命令和文件证据。</li><li>按本站版本化的 AI 评分提示词打质量参考分；DeepSWE 官方成绩由其隔离程序验证器产生，不是这个 AI 分数。</li><li>返回结构化报告，工作台核对引用后保存。实际提示词见“评分过程”。</li></ol><p>每次独立 CLI 会话不继承开发对话；新版裁判副本也不包含工作区根目录的 AGENTS 指令和 .codex 配置。产物本身仍可能带有身份线索，AI 分数仍会受提示词和模型影响，不能称为客观盲评分。</p><p>{environment==='local'?'本机使用 Codex 原生沙箱，需先安装 CLI 并检查 codex login status。Windows 浏览器取证暂不可用，交互与视觉项保留未验证。':'容器使用 Harbor 固定镜像，需准备 Docker；当前仅支持官方连接。'}</p><p>预算是本次审查允许的运行时间，不是 Token 上限。环境阻断、账号不支持所选模型、额度不足和预算用尽均不能当作产物失败。网页质量还需实际浏览器截图和交互证据；AI 意见可辅助复核，不能代替人的视觉判断。</p></Details>
    {!judgeSupported&&<p className="alert-error">当前模型档位不匹配，请重新选择；不会自动换模型。</p>}
    <JudgeProgress runId={run.id} trialId={t.id} busy={judging}/>
    {judgeError&&<><div role="alert" className="alert-error"><strong>本次评分未完成{report?'，保留上次结果':''}</strong><p className="mt-2">{judgeError.message}</p>{judgeError.message.includes('评分报告未通过校验')&&<button type="button" className="btn-secondary mt-3" disabled={disabled||busy} onClick={()=>void act('judge-revalidate').catch(()=>{})}>重新校验已保存报告 · 不调用模型</button>}</div>{!report&&t.judgeExecution?.jobId&&<ReviewScreenshots runId={run.id} trialId={t.id}/>}</>}
    {!!report?.validationWarnings?.length&&<Details title={`引用校验 · ${report.validationWarnings.length} 条待复核`}><p className="muted">未通过校验的引用已剔除。若同一评分项仍有其他有效证据，其分数会保留；没有足够证据的项目保持未评。可重新校验已保存的原文和日志，不调用模型。引用存在也不保证 AI 判断正确。</p>{report.validationWarnings.map((w,i)=><p key={i} className="text-sm">{rubrics[w.key]?.label||task.criteria?.find(c=>c.id===w.key)?.label||w.key}：{w.message}</p>)}{!disabled&&!busy&&<button type="button" className="btn-secondary" onClick={()=>void act('judge-revalidate').catch(()=>{})}>重新校验已保存报告 · 不调用模型</button>}</Details>}
    {report&&<button type="button" className="btn-secondary" onClick={()=>setView('result')}>查看已保存的评分结果</button>}
    </div><div className="review-section space-y-4" hidden={view!=='result'}>
    {report?.automaticRepair&&<Details title="本次自动补查回执"><p>{report.automaticRepair.note}</p><p>这是一次授权审查内的反馈流程，不计作多个独立复评样本；沿用原模型、档位和剩余时间预算。</p>{report.automaticRepair.attempts?.map((attempt,index)=><section key={attempt.jobId||index}><h4>取证尝试 {index+1} · {attempt.seconds} 秒</h4><p>{attempt.issues.length?`${attempt.issues.length} 项反馈`:'报告已通过校验'}</p>{attempt.issues.map((issue,i)=><p key={i}>{issue.dimension?(rubrics[issue.dimension]?.label||issue.dimension):issue.requirement||'报告'}{issue.facet?' · '+({coverage:'覆盖',quality:'质量',resilience:'反例检查'}[issue.facet]||issue.facet):''}：{issue.reason}</p>)}<p className="muted">{attempt.jobId} · 输入 {attempt.usage?.inputTokens.toLocaleString()||'未记录'} Token · 输出 {attempt.usage?.outputTokens.toLocaleString()||'未记录'} Token</p></section>)}</Details>}
    {report?<><div className="score-overview"><ScoreRing value={t.score.overall} label={intermediate?'阶段无总分':t.score.overall==null?'综合分未形成':task.publicSource||t.state==='completed'?'本地单题参考分':'本地单题暂定分'} detail={task.publicSource?(t.score.overall==null?'当前快照的原题验收或本地质量证据尚未齐全；AI均值不能代替总分。':'本地评分卡已有完整结果；原题通过状态单独保留。'):t.score.overall==null?'适用项未全部验证；当前没有整题总分':t.state==='completed'?'各适用项有分，交付已结束':'各适用项已有分；再次回收或修正会重新计算，交付结束后仍须核对任务验收资格'}/><dl className="run-stats"><div><dt>{task.publicSource?'AI 质量均值':'已评分项均值'}</dt><dd>{num(task.publicSource?t.score.machine:t.score.partialScore??null)}</dd></div><div><dt>{task.publicSource?'AI 质量项有分权重':'AI 有分权重'}</dt><dd>{t.score.machineCoverage||0}%</dd></div></dl></div>{t.score.overall!=null&&t.score.overall>=90&&<p className="score-notice"><strong>高分仍需核验：</strong>本次 {num(t.score.overall,' 分')} 是 AI 按冻结评分卡给出的参考值；{rated.length} 项有分，其中 {runtimeRated} 项引用了运行证据，当前快照有 {latest.checks.filter(check=>check.status==='passed'||check.status==='failed').length} 项程序检查结果。引用存在与通用检查通过不等于需求、交互或视觉均正确。可展开下方逐项依据，并打开产物人工复核。</p>}{t.score.taskScorecard&&<section className="native-scorecard" aria-label="本地逐项评分"><p className="muted">{t.score.taskScorecard.version} · 总权重 100 分。下面是当前单题分的组成。</p><div className="native-scorecard-items">{t.score.taskScorecard.items.map(item=><Details key={item.label} title={<span className="contribution-title"><strong>{item.label}</strong><span>权重 {item.weight} · 得 {item.points==null?'待补证据':item.points.toFixed(1)} 分</span></span>}><p>{item.evidence}</p></Details>)}</div></section>}{t.score.overall==null&&<p className="score-notice">已评分项均值只概括目前有证据的项目，不是整题分数；{intermediate?'当前仍是中间阶段。':task.publicSource?'本地总分仍待原题验收或质量证据。':'仍有适用评分项未验证。'} 切换到“程序验收”查看程序结果。引用校验只确认材料存在，不证明 AI 结论正确。</p>}{t.score.overall!=null&&!task.publicSource&&t.state!=='completed'&&<p className="score-notice">当前 {num(t.score.overall,' 分')} 为完整评分项的暂定单题分；交付未结束，后续快照或修正会重算，暂不进入配置对比。</p>}<Details title="本次报告、用量与判断限制"><p className="muted">本次裁判：{report.model||'未知模型'} · 推理 {report.reasoningEffort||'模型默认'} · 提示词 {report.judgePromptVersion||'旧版未记录'}{report.judgePromptSha256?` · SHA-256 ${report.judgePromptSha256.slice(0,12)}`:''} · {report.serviceTier==='fast'?'请求 Fast':'标准/原速度'} · {report.reviewEnvironment==='local'?'本机 CLI':'Docker/Harbor'} · {report.judgeIsolation?'新进程/临时配置':'旧记录未记录隔离标记'} · {report.judgeBlinding?'已剔除工作区指令和模型配置':'旧协议未剔除工作区指令和模型配置'}{report.revalidatedFrom?' · 使用已保存报告重新校验':''}</p>
      {t.score.overall!=null&&!task.publicSource&&t.score.assurance!=='task-check-pass'&&<p className="score-notice"><strong>仅供参考，不能用于配置对比：</strong>{t.score.assurance==='task-check-fail'?'当前快照的任务专属程序验收失败。':'当前快照缺少合格的任务专属程序验收；通用网页烟检和 AI 引用不能证明题目要求已经实现。'}原始 AI 分数与证据保留，可逐项复核。</p>}
      {report.judgeUsage&&<p className="muted">本次 CLI 裁判累计：输入 {report.judgeUsage.inputTokens.toLocaleString()} Token（其中缓存读取 {report.judgeUsage.cachedInputTokens.toLocaleString()}），输出 {report.judgeUsage.outputTokens.toLocaleString()}（其中推理 {report.judgeUsage.reasoningOutputTokens.toLocaleString()}）。这些是作业日志计数，不等于订阅额度扣除或实际账单；失败重试另计。</p>}
      {report.reportNormalization&&<p className="muted">原始报告末尾多出一个右花括号；重新解析时仅忽略该字符。原文已保留，评分项和引用仍逐项校验。</p>}
      <p className="muted">此连续分是一次裁判按冻结权重计算的参考值；小数位来自加权公式，不表示 0.1 分差有可重复的辨别力。前端视觉请打开原截图复核；接近的作品需同条件重复审查或盲评。</p>
</Details>
      {t.score.judgeReliability&&<Details title={`评分稳定性 · 同条件独立审查 ${t.score.judgeReliability.sameProtocolRuns} 次`}>
        <p>仅统计同一快照、需求、量表、验收器、模型、档位、提示词和执行环境的独立 CLI 作业。重新解析同一报告不算复评；不同裁判不混算。</p>
        {t.score.judgeReliability.sameProtocolRuns<2?<p className="score-notice">尚无足够同条件重复，无法判断分数是否稳定。当前高分不等于经过正确性校准。</p>:<p>下面是已观察到的逐项最小值与最大值，不是误差上限或置信区间。重复一致也可能一致地误判。</p>}
        {t.score.judgeReliability.ranges.map(row=><p key={row.dimension}>{rubrics[row.dimension]?.label||row.dimension}：{row.min}–{row.max} 分 · 极差 {row.spread} · {row.samples} 次有分</p>)}
        {!!t.score.judgeReliability.missingProtocol.length&&<p className="muted">旧报告缺少可比条件：{t.score.judgeReliability.missingProtocol.join('、')}。</p>}
        <p className="muted">尚未完成与独立标注样本的盲评校准；系统不会因重复一致而自动认证裁判，也不会自动发起额外付费复评。</p>
      </Details>}
      {t.score.overall==null&&!intermediate&&<p className="muted">{task.publicSource?'原题验收与本地质量证据齐全后，才能计算本地综合分。':'仍有未验证的适用项，可查看依据并人工复核；全项有分时即可看到暂定总分。'}</p>}
      <Details title={report.scoringProtocol?'统一评分标准 · 无额外加分':'旧版直接评分 · 未采用统一等级'}><p>所有题型共用覆盖、质量、反例检查三项：0 核心失败，1 重大缺口，2 部分成立，3 基本满足但有次要问题，4 要求完整成立且有反例检查证据。每项等级乘25，三项取均值，再按冻结权重汇总。未验证留空，额外功能不加分。</p><p className="muted">{report.scoringProtocol?`${report.scoringProtocol} · 分数由程序计算；模型对等级和证据的解释仍需校准。`:'此报告保留原始分数；下次重评使用统一协议，旧记录不追溯改写。'}</p></Details>{report.requirementChecks&&<Details title={`原题逐条验收 · ${Object.keys(report.requirementChecks).length} 条`}>{Object.entries(report.requirementChecks).map(([id,item])=><div key={id} className="machine-rating"><div><strong>{id} · {verdicts[item.status]||item.status}</strong><p>{item.source}</p><p className="muted">{item.notes}</p>{item.evidence?.map((e,i)=><pre className="source" key={i}>{e.quote}</pre>)}</div></div>)}</Details>}<div className="machine-ratings">{dimensions.map(([key,item])=>{const rating=ratings[key];const override=t.score.machineOverrides?.[key];return <div key={key} className="machine-rating"><Details title={<span className="rating-title"><strong>{item.label}</strong><ScoreBar value={t.score.effectiveScores?.[key]}/><span>{rating?({static:'静态判断',runtime:'运行证据',unverified:'未验证'}[rating.method]||rating.method):'未验证'}</span></span>}>{rating&&<><p className="text-sm">{rating.reason}</p>{rating.checks&&<div className="anchored-facets">{Object.entries(rating.checks).map(([id,check])=><section className="anchored-facet" key={id}><strong>{{coverage:'覆盖',quality:'质量',resilience:'反例检查'}[id]} · {check.score==null?'未验证':`${num(check.score)} 分`}</strong><p>{check.reason}</p>{check.constraint&&<p className="score-notice">{check.constraint}</p>}{check.evidence.map((e,i)=><pre key={i} className="source">{e.quote}</pre>)}{check.counterEvidence.length>0&&<Details title="反例证据">{check.counterEvidence.map((e,i)=><pre className="source" key={i}>{e.quote}</pre>)}</Details>}</section>)}</div>}{rating.evidence.map((e,i)=><div key={i}><small>{e.path?`${e.path}:${e.line}`:e.turnId?`${e.turnId} · ${e.speaker==='user'?'用户':'助手'}`:e.command||e.checkId}{e.reportedLine!=null?`（原报 ${e.reportedLine} 行，按唯一原文定位）`:null}</small><pre className="source">{e.quote}</pre></div>)}</>}{override&&<p className="text-sm">人工修正：{override.reason}</p>}</Details><div className="rating-actions"><span>{num(rating?.score??null)}{override&&<> → <strong>{override.score}</strong></>}</span><button className="btn-secondary" disabled={disabled||busy} onClick={()=>{setEditing(key);setEditingEvidence({reviewId:t.score.machineReviewId,evidenceKey:t.score.machineEvidenceKey});setValue(String(t.score.effectiveScores?.[key]??''));setReason('');}}>修正</button></div></div>;})}</div>
      {report.summary&&<Details title="裁判结论"><p className="text-sm whitespace-pre-wrap">{report.summary}</p></Details>}
      <ReviewScreenshots runId={run.id} trialId={t.id} reviewId={report.id}/>
    </>:!judging&&!judgeError?<div className="score-empty"><p>回收已就绪，可以开始评分。</p><p className="muted">机器按本题要求检查产物；有结果后可逐项人工修正。</p></div>:judging?<p role="status" className="muted">正在检查产物并收集评分证据，可以切换页签查看记录。</p>:null}
    </div><div className="review-section space-y-4" hidden={view!=='standards'}>
    <Details title={`评分标准 · ${dimensions.length} 项`}><dl className="score-rules">{dimensions.map(([key,item])=><div key={key}><dt>{item.label}<span>{task.publicSource?'质量审查项':`本题权重 ${weights[key]}%`}</span></dt><dd>{item.description}</dd></div>)}</dl><p className="muted">本题按冻结题型选择适用项；未知项不当作0。人工修正保留机器原分。脚本结果与 AI 判断分别保留。</p></Details>
    {!!task.criteria?.length&&<Details title={t.score.acceptance.required?`需求验收 · ${t.score.acceptance.met}/${t.score.acceptance.required} 必要项满足`:`需求对照 · ${task.criteria.length} 项（未设必要项）`}><div className="requirement-list">{task.criteria.map(c=><article key={c.id}><div><strong>{c.label}</strong>{report?.criteria?.[c.id]?.notes&&<p>{report.criteria[c.id].notes}</p>}</div><span className="badge">{verdicts[report?.criteria?.[c.id]?.status||'unverified']}</span></article>)}</div><p className="muted">人工调分不会改写需求验收和程序通过状态。</p></Details>}
    {(!!latest.checks.length||!!report?.commands?.length)&&<Details title={`执行证据 · ${latest.checks.length} 项检查 / ${report?.commands?.length||0} 条裁判命令`}><p className="muted">脚本检查分 {num(t.score.objective)}，不重复加权。</p>{latest.checks.map(c=><Details key={c.id} title={`${c.label} · ${c.status}`}><pre className="source">{c.output}</pre></Details>)}{report?.commands?.map((c,i)=><Details key={i} title={`裁判命令 ${i+1} · 退出码 ${c.exitCode??'未知'}`}><pre className="source">{c.command}</pre><pre className="source">{c.output}</pre></Details>)}</Details>}
    {!!t.machineCorrections?.length&&<Details title="人工修正历史">{t.machineCorrections.slice().reverse().map(c=><div key={c.id}><p>{date(c.at)} · {c.reviewId===t.score.machineReviewId?'当前评分版本':'历史评分版本'}</p>{Object.entries(c.changes).map(([k,v])=><p key={k}>{rubrics[k]?.label}：{v.score??'撤回修正'} · {v.reason}</p>)}</div>)}</Details>}
    </div>
    <Dialog title={'修正：'+(editing?rubrics[editing]?.label:'')} open={!!editing} onClose={()=>setEditing(null)}><form className="space-y-4" onSubmit={e=>{e.preventDefault();void correct().catch(()=>{});}}><fieldset disabled={disabled||busy} className="space-y-4"><ScoreSlider label="修正后分数" value={value} onChange={setValue}/><Field label="理由与复核证据"><textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明实际结果及机器误判之处"/></Field><div className="flex gap-3"><button className="btn-primary">保存修正</button>{editing&&t.score.machineOverrides?.[editing]&&<button type="button" disabled={!reason.trim()} className="btn-secondary" onClick={()=>void correct(true).catch(()=>{})}>恢复机器原分</button>}</div></fieldset></form></Dialog>
  </Panel>;
}
