import {useState} from 'react';
import source from '../../../catalog/public-task-sources.json';
import benchmarkFamilies from '../../../catalog/benchmark-families.json';
import type {State,Act} from './types';
import {Field,Details} from './ui';
import {nativeTaskIds} from './PublicCatalog';
const categories:Record<string,string>={bugfix:'修复 Bug',feature_request:'已有工程增加功能',enhancement:'已有工程改进'};
export function PublicTaskSources({state,act,onUse}:{state?:State;act?:Act;onUse?:(id:string)=>void}){
  const [importing,setImporting]=useState(false);
  const [sourceNotice,setSourceNotice]=useState('');
  const importWeb=async()=>{if(!act)return;setImporting(true);setError('');try{const result=await act<{added:number;total:number;shortCandidates:number}>('/sources/webgen',{});setSourceNotice(`已导入 ${result.added} 道，固定题库 ${result.total} 道，其中 ${result.shortCandidates} 道通过短项目筛选。`);}catch(e){setError((e as Error).message);}finally{setImporting(false);}};
  const importEval=async()=>{if(!act)return;setImporting(true);setError('');try{const r=await act<{added:number;total:number}>('/sources/evalplus',{});setSourceNotice(`HumanEval+ 已导入 ${r.added} 道，固定题库 ${r.total} 道；首次程序检查准备镜像。`);}catch(e){setError((e as Error).message);}finally{setImporting(false);}};
  const [expanded,setExpanded]=useState<string|null>(null);
  const [error,setError]=useState('');const [query,setQuery]=useState('');const [language,setLanguage]=useState('');const [category,setCategory]=useState('');
  const rows=source.tasks.filter(t=>(!language||t.language===language)&&(!category||t.category===category)&&[t.id,t.title,t.repositoryUrl].some(s=>s.toLowerCase().includes(query.trim().toLowerCase())));
  const job=state?.sourceJobs?.find(j=>j.id==='deepswe-download');const running=job?.status==='running';
  const prepare=(taskIds:string[],prepareEnvironment=false)=>{setError('');return act?.('/sources/prepare',{taskIds,prepareEnvironment}).catch(e=>setError((e as Error).message));};
  return <section className="public-sources space-y-4" aria-label="公开题源"><section className="panel p-4"><div className="source-heading"><div><h3>WebGen-Bench · 101 道网页应用题</h3><p>保留上游题面和逐项UI操作、预期结果，包含工具、游戏、数据与交互应用。</p></div>{act&&<button className="btn-primary" disabled={importing} onClick={()=>void importWeb()}>{importing?'下载并校验题目…':'导入网页题库'}</button>}</div><p className="muted">本地桌面适配，采用本项目统一裁判；未运行原版WebVoyager，不生成官方成绩。长项目不进入默认快速组卷。数据仅下载到本机，重复导入不覆盖编辑或恢复归档题。</p><a href="https://github.com/mnluzimu/WebGen-Bench" target="_blank" rel="noreferrer">上游题目与评分方法 ↗</a></section>
    <section className="panel p-4"><div className="source-heading"><div><h3>HumanEval+ · 163 道已验证扩展测试题</h3><p>原题函数签名与扩展断言固定，隐藏测试和参考解不放进工作区。</p></div>{act&&<button className="btn-primary" disabled={importing} onClick={()=>void importEval()}>{importing?'下载并校验…':'导入函数题库'}</button>}</div><p className="muted">隔离程序判通过或失败，不依赖 AI 打分。上游164题中第32题导出验收有错误，未加入可运行题库。适合短任务的 Harness 开销对照；不加入默认项目随机组卷，不称官方 pass@k。</p><a href="https://github.com/evalplus/evalplus" target="_blank" rel="noreferrer">上游与扩展测试方法 ↗</a></section>
    <section className="panel p-4"><h3>社区实践 · 8 道有功能核心验收的新项目</h3><p>旋转墙碰撞、三维轨道、分形、排序、寻路、落块、贪吃蛇、生命游戏。77个固定核心用例和页面连接检查，已直接加入任务库；不同实现共用同一接口。视觉意见与程序结果分开。</p></section>
    {sourceNotice&&<p role="status">{sourceNotice}</p>}
    <div className="source-heading"><div><h3>DeepSWE · {source.tasks.length} 道已有仓库任务</h3><p>4 道 Bug 修复，109 道工程扩展。选题后创建评测，自动准备该题固定源码。</p></div><a href={source.repository} target="_blank" rel="noreferrer">上游 ↗</a></div>
    <div className="source-filters"><Field label="搜索公开题目"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="任务、编号或仓库"/></Field><Field label="任务类型"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部类型</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="项目语言"><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">全部语言</option>{[...new Set(source.tasks.map(t=>t.language))].sort().map(l=><option key={l}>{l}</option>)}</select></Field></div>

    {error&&<p className="alert-error" role="alert">{error}</p>}
    {job&&(running||job.errors.length>0)&&<div className="source-progress" role="status"><strong>{running?'正在准备':job.status==='completed'?'下载完成':'准备结果'}</strong><span>{job.phase}</span>{!!job.taskIds.length&&<span>{job.completed.length} / {job.taskIds.length} 份源码已保存</span>}{job.errors.map(e=><p className="alert-error" key={e.taskId}>{e.taskId}：{e.message}</p>)}</div>}
    <p className="muted">显示 {rows.length} 道 · 固定题包 {source.revision.slice(0,12)}</p>
    <div className="public-source-list">{rows.map(t=>{const installed=state?.tasks.find(x=>x.id==='deepswe-'+t.id);const archived=state?.archivedTasks.find(x=>x.id==='deepswe-'+t.id);return <article key={t.id}><div><h4>{t.title}</h4><p>{categories[t.category]} · {t.language} · {t.repositoryUrl.replace('https://github.com/','')}</p><code title={t.baseCommit}>源码 {t.baseCommit.slice(0,12)}</code><p className="muted">{installed?(installed.publicSource?.environmentStatus==='ready-windows'?'本机环境已验证 · 支持免 Docker 测试验收':'源码已下载 · 依赖待验证'):archived?'已归档；请从题库恢复':'创建工作区时下载源码'}</p></div><div className="source-links">{onUse&&<button className="btn-primary" disabled={!!archived} onClick={()=>onUse('deepswe-'+t.id)}>选用此题</button>}<button className="btn-secondary" aria-expanded={expanded===t.id} onClick={()=>setExpanded(expanded===t.id?null:t.id)}>来源与缓存</button></div>{expanded===t.id&&<div className="source-cache-panel"><p>创建评测会自动准备此题，无需提前缓存。相同仓库与提交复用一份源码，每次评测复制到新的独立工作区。</p><div className="source-cache-actions">{act&&<><button className="btn-secondary" disabled={running||!!archived} onClick={()=>prepare([t.id])}>{installed?'校验并复用源码':'提前缓存此题源码'}</button>{nativeTaskIds.includes(t.id)&&<button className="btn-secondary" disabled={running||!!archived} onClick={()=>prepare([t.id],true)}>核对本机环境</button>}</>}<a href={t.instructionUrl} target="_blank" rel="noreferrer">题面 ↗</a><a href={t.environmentUrl} target="_blank" rel="noreferrer">环境 ↗</a><a href={t.verifierUrl} target="_blank" rel="noreferrer">验收器 ↗</a></div></div>}</article>})}{!rows.length&&<p>没有匹配的公开题目。</p>}</div>
    <Details title="源码缓存和运行环境"><p>创建时只准备所选题目的定义、隐藏验收和固定源码；已缓存且校验通过的内容直接复用。参考解不解包，隐藏测试不进入开发目录。启动网站和下载源码不需要 Docker。</p><p>下载不等于依赖已安装。Tengo 两题与 Yaegi Embed 已支持 Windows 本机工具链与测试适配；既有五题的固定 Linux 上游验收已有真实回执。其余题仍须逐题准备依赖和验证原生测试，113 条来源索引不等于 113 题环境就绪。原题结果与本地 AI 质量参考分分别记录，不能冒称全库官方榜单通过率。</p><p>题包采用 Apache-2.0，目标工程沿用各自许可。文件保存在项目 .local/arena，不写入公共源码仓库。</p></Details>
    <section className="benchmark-family-research" aria-label="其他公开基准接入评估"><header><h3>其他公开基准 · 接入评估</h3><p>这些是已核对的上游方向，尚未下载或接入本机执行，不能当作可选题目或已测分数。不同基准的任务和判分协议分别保留。</p></header><div>{benchmarkFamilies.families.map(family=><article key={family.id}><div><h4>{family.name}</h4><small>{family.domain}</small></div><p>{family.fit}</p><p><strong>接入前需完成：</strong>{family.gate}</p><p className="muted">{family.scoreBoundary}</p><a href={family.url} target="_blank" rel="noreferrer">查看官方仓库 ↗</a></article>)}</div></section>
  </section>;
}
