import {HarnessReport} from './HarnessExperiment';
import {ArrowUpRight,Archive,Download,Search,RotateCcw} from 'lucide-react';
import {useState,useEffect} from 'react';
import {apiEquivalent,runProgress} from './presentation';
import type {State,Act} from './types';
import {Details,Empty,num,date} from './ui';
import {downloadRun} from './api';
import {configResults,entryScore} from './configResults';
import {nativeTestProgress} from './scoreExplanation';
import type {ConfigResult,ConfigResultEntry,TaskResult} from './configResults';
import {DeleteEvaluation} from './DeleteEvaluation';
import {CapabilityRadar} from './CapabilityRadar';
const suiteUsage=(group:ReturnType<typeof configResults>[number])=>{
  const entries=group.tasks.flatMap(task=>task.entries),usages=entries.map(entry=>entry.trial.usage);
  if(!entries.length)return '本题集用量：尚无完整分';
  const tokens=usages.map(usage=>usage?.totalTokens).filter((value):value is number=>typeof value==='number');
  const seconds=usages.map(usage=>usage?.activeSeconds).filter((value):value is number=>typeof value==='number');
  const costs=usages.map(usage=>usage?apiEquivalent(usage):null);
  const cost=costs.length&&costs.every(value=>value&&typeof value.low==='number'&&typeof value.high==='number')?
    ` · API 等值约 $${costs.reduce((sum,value)=>sum+(value?.low||0),0).toFixed(2)}–$${costs.reduce((sum,value)=>sum+(value?.high||0),0).toFixed(2)}`:' · API 等值暂不可估';
  return `本题集用量：${tokens.length===entries.length?tokens.reduce((a,b)=>a+b,0).toLocaleString('zh-CN')+' Token':`${tokens.length}/${entries.length} 题有 Token`} · ${seconds.length===entries.length?Math.round(seconds.reduce((a,b)=>a+b,0)/60)+' 分钟活动':`${seconds.length}/${entries.length} 题有时长`}${cost}`;
};
const suiteEvidence=(group:ReturnType<typeof configResults>[number])=>{
  const selected=group.tasks.flatMap(task=>task.entries);
  if(!selected.length)return `${group.recorded} 次已有质量分${group.nativeScored?`；原题已验收 ${group.nativeScored} 次：${group.nativePassed} 通过、${group.nativeScored-group.nativePassed} 失败`:'；原题尚未取得结果'}，尚无完整题集质量分`;
  const publicTrials=selected.filter(entry=>entry.task.publicSource);
  const passed=publicTrials.filter(entry=>entry.trial.score.nativeReward===1).length;
  const history=Math.max(0,group.recorded-selected.length);
  return `${publicTrials.length?`当前题集原题通过 ${passed}/${publicTrials.length}`:'当前题集无公开原题'}${history?` · 历史另有 ${history} 次逐题分`:''}`;
};
type ResultItem={key:string;kind:'current'|'history'|'pending';title:string;revision:number;score:number|null;count:number;note:string;entries:ConfigResultEntry[]};
function ConfigResultTasks({group,onOpen}:{group:ConfigResult;onOpen:(id:string)=>void}){
  const [filter,setFilter]=useState<'current'|'history'|'pending'|'all'>(group.tasks.length?'current':'pending');
  const [page,setPage]=useState(1);
  const current:ResultItem[]=group.tasks.map((task:TaskResult)=>({key:'current:'+task.protocolKey,kind:'current',title:task.task.title,revision:task.task.revision,score:task.mean,count:task.entries.length,note:group.collections.find(source=>source.tasks.includes(task))?.label||'当前题集',entries:task.entries}));
  const history:ResultItem[]=group.suiteRunId?group.entries.filter(entry=>entry.eligible&&entry.run.id!==group.suiteRunId).map(entry=>({key:'history:'+entry.trial.id,kind:'history',title:entry.task.title,revision:entry.task.revision,score:entryScore(entry),count:1,note:'历史题集，不纳入当前成绩',entries:[entry]})):[];
  const pending:ResultItem[]=group.entries.filter(entry=>!entry.eligible).map(entry=>({key:'pending:'+entry.trial.id,kind:'pending',title:entry.task.title,revision:entry.task.revision,score:entryScore(entry),count:1,note:entry.exclusion||'尚未纳入配置成绩',entries:[entry]}));
  const items=[...current,...history,...pending].filter(item=>filter==='all'||item.kind===filter);
  const pageSize=8,pages=Math.max(1,Math.ceil(items.length/pageSize)),visible=items.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize);
  const changeFilter=(next:typeof filter)=>{setFilter(next);setPage(1);};
  return <section className="config-task-browser" aria-label="题目成绩"><header><div><h3>题目成绩</h3><p>当前题集、历史与待补记录分开查看；每页最多 8 项。</p></div><span>{group.entries.length} 次评测记录</span></header><div className="config-task-filters" role="group" aria-label="筛选题目成绩">{([['current','当前题集',current.length],['history','历史',history.length],['pending','待补',pending.length],['all','全部',current.length+history.length+pending.length]] as const).map(([key,label,count])=><button key={key} type="button" className={filter===key?'active':''} aria-pressed={filter===key} onClick={()=>changeFilter(key)}>{label} <span>{count}</span></button>)}</div>{visible.length?<div className="config-task-grid">{visible.map(item=>{const entry=item.entries[item.entries.length-1],native=nativeTestProgress(entry.trial),progress=entry.trial.score.scoreProgress;return <article className={'config-task-card '+(item.kind==='pending'?'is-pending':'')} key={item.key}><div className="config-task-card-top"><span>{item.kind==='current'?'当前成绩':item.kind==='history'?'历史记录':native?(native.result.reward?'原题通过':'原题未通过'):'待补证据'}</span><strong>{item.score!=null?item.score.toFixed(1):native?`${native.result.reward} / 1`:progress?.coverage?`${num(progress.minimum)}–${num(progress.maximum)}`:'—'}<small>{item.score!=null?' 分':native?' 原题结果':progress?.coverage?' 分项范围':''}</small></strong></div><h4>{item.title} <small>v{item.revision}</small></h4><p>{item.note}{item.kind==='pending'&&item.score!=null?' · 现有分数仅供预览':''}</p>{native&&<p>最近一份目标测试 {num(native.target)}% · 回归 {num(native.regression)}%。程序结果无需AI复核，连续质量分另列。</p>}<footer><span>{item.count} 次 · {date(item.entries[item.entries.length-1].run.createdAt)}</span>{item.entries.length===1?<button type="button" onClick={()=>onOpen(item.entries[0].run.id)}>查看证据 ↗</button>:<details><summary>查看 {item.entries.length} 次证据</summary>{item.entries.map((entry,index)=><button type="button" key={entry.trial.id} onClick={()=>onOpen(entry.run.id)}>第 {index+1} 次 · {num(entryScore(entry),' 分')} ↗</button>)}</details>}</footer></article>;})}</div>:<p className="muted config-task-empty">这里还没有记录。</p>}{pages>1&&<nav className="config-task-pages" aria-label="题目成绩翻页"><button type="button" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span>第 {Math.min(page,pages)} / {pages} 页 · 共 {items.length} 项</span><button type="button" disabled={page>=pages} onClick={()=>setPage(page+1)}>下一页</button></nav>}</section>;
}
export function History({state,act,onOpen,onError}:{state:State;act:Act;onOpen:(id:string)=>void;onError:(s:string)=>void}){
  const [scope,setScope]=useState<'active'|'archived'>('active');const [query,setQuery]=useState('');
  const all=[...state.runs,...state.archivedRuns];
  const runs=all.filter(r=>scope==='archived'?state.archivedRuns.some(a=>a.id===r.id):state.runs.some(a=>a.id===r.id)).filter(r=>(r.id+r.notes+r.tasks.map(t=>t.title).join()+r.configs.map(c=>c.name).join()).toLowerCase().includes(query.toLowerCase()));
  const active=state.runs,archived=state.archivedRuns;
  const completed=active.filter(r=>r.state==='completed').length;
  return <><header className="page-heading"><div><span className="eyebrow">实验档案</span><h1 className="page-title">每次交付，都有迹可循。</h1><p>保留当时的配置、产物和验收结果。评分项齐全时可查看暂定单题分；交付结束后仍须有独立任务验收，才能进入配置对比。</p></div><div className="history-count"><strong>{active.length}</strong><span>次评测 · {completed} 次交付结束</span></div></header>
    <div className="history-toolbar"><div className="catalog-switch"><button className={scope==='active'?'active':''} onClick={()=>setScope('active')}>活动记录 <span className="tab-count">{active.length}</span></button><button className={scope==='archived'?'active':''} onClick={()=>setScope('archived')}>已归档 <span className="tab-count">{archived.length}</span></button></div><label className="search-field"><Search size={17}/><input aria-label="搜索历史" placeholder="搜索题目、配置或备注" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
    {runs.length?<section className="history-list" aria-label="评测记录"><div className="history-table-head"><span>任务 / 配置</span><span>状态与证据</span><span>创建时间</span><span>操作</span></div>{runs.map(r=><article className="history-row" key={r.id}><div className="history-task"><button onClick={()=>onOpen(r.id)}>{r.tasks.map(t=>t.title).join('、')}<ArrowUpRight size={16}/></button><p>{r.configs.map(c=>`${c.name} v${c.revision} · ${c.baseModel} / ${c.reasoning}${c.preparationOverride?' · 技能已调整':''}`).join('；')}</p>{r.notes&&<small>{r.notes}</small>}</div><div className="history-state"><span className={'status-pill '+(r.state==='completed'?'done':'pending')}><span/>{runProgress(r)}</span><small>{r.trials.length} 个工作区 · {r.trials.reduce((n,t)=>n+t.captures.length,0)} 份回收 · {r.trials.filter(t=>t.score.overall!=null).length}/{r.trials.length} 道已计分</small></div><time title={r.id}>{date(r.createdAt)}</time><div className="history-actions"><button className="icon-button" aria-label={'导出 '+r.tasks.map(t=>t.title).join('、')} title="导出 ZIP" onClick={()=>downloadRun(r.id).catch(e=>onError(e.message))}><Download size={17}/></button><button className="icon-button" aria-label={(state.archivedRuns.some(a=>a.id===r.id)?'恢复 ':'归档 ')+r.tasks.map(t=>t.title).join('、')} title={state.archivedRuns.some(a=>a.id===r.id)?'恢复记录':'归档记录'} onClick={()=>act(`/runs/${r.id}/archive`,{archived:!state.archivedRuns.some(a=>a.id===r.id),revision:r.revision}).catch(()=>{})}>{state.archivedRuns.some(a=>a.id===r.id)?<RotateCcw size={17}/>:<Archive size={17}/>}</button></div><div className="history-direct-actions"><DeleteEvaluation runId={r.id} revision={r.revision} workspaceDeletion={r.workspaceDeletion} canDelete={!r.trials.some(t=>['checking','judging'].includes(t.state))} act={act} onDeleted={()=>{}}/></div></article>)}</section>:<Empty><strong>{query?'没有匹配的记录':scope==='archived'?'归档为空':'从第一次评测开始'}</strong><p>{query?'试试其他题目、配置名称或备注。':scope==='archived'?'归档的评测可以随时恢复。':'在工作台完成一次评测，产物与过程将保留在这里。'}</p></Empty>}
    <Details title={`CLI 实验档案 · ${state.legacyExperiments} 次`}><p className="muted">CLI 实验单独保存在 runs/，使用 chb report 或 chb analyze 查看，不混入桌面评测。</p></Details></>;

}
export function Comparison({state,onOpen,initialKey=null}:{state:State;onOpen:(id:string)=>void;initialKey?:string|null}){
  const [opened,setOpened]=useState<string|null>(initialKey);
  const [model,setModel]=useState('');
  const [scope,setScope]=useState<'all'|'current'|'history'|'archived'>(initialKey?'all':'current');
  useEffect(()=>{if(initialKey)document.getElementById('config-result-'+initialKey)?.scrollIntoView({block:'start'});},[initialKey]);
  const experiments=state.runs.filter(r=>r.experiment&&!r.historyHidden);
  const [experimentId,setExperimentId]=useState(experiments[0]?.id||'');
  const experimentRun=experiments.find(r=>r.id===experimentId)||experiments[0];
  const all=configResults(state);
  const models=[...new Set(all.map(g=>g.config.baseModel))].sort();
  const counts={current:all.filter(g=>g.current).length,history:all.filter(g=>!g.current&&!g.archivedConfig).length,archived:all.filter(g=>g.archivedConfig).length};
  const groups=all.filter(g=>(!model||g.config.baseModel===model)&&(scope==='all'||(scope==='current'&&g.current)||(scope==='history'&&!g.current&&!g.archivedConfig)||(scope==='archived'&&g.archivedConfig)));
  return <><header className="page-heading"><div><span className="eyebrow">配置成绩</span><h1 className="page-title">这套 Harness，是否值得用。</h1><p>固定模型，对比同题交付、失败与资源消耗；单题质量参考分保留在下方档案。</p></div><div className="history-count"><strong>{all.length}</strong><span>个配置版本</span></div></header>
    {experimentRun?<><label className="harness-experiment-select">查看对照实验<select value={experimentRun.id} onChange={e=>setExperimentId(e.target.value)}>{experiments.map(r=><option key={r.id} value={r.id}>{r.configs.map(c=>c.name).join(" / ")} · {date(r.createdAt)}</option>)}</select></label><HarnessReport key={experimentRun.id} run={experimentRun}/><button className="btn-secondary" onClick={()=>onOpen(experimentRun.id)}>继续执行与验收</button></>:<div className="score-notice">在评测工作台选题后，进入配置步骤，启用“比较两套 Harness 的交付与效率”。支持从现有配置创建精简对照；固定题目与模型，交错执行独立重复。</div>}
    <div className="config-results-intro"><p>同题重复先求均值，不同题再等权汇总。原题验收或已核对的任务专属程序验收是配置对照的最低证据门槛；综合分中的 AI 质量项仍需校准，不能仅凭分差宣布胜负。通用网页烟检和单次 AI 审查只显示参考均值；验收失败也不能冒充已通过。分数不是官方模型榜单。</p><div className="config-results-controls"><label>配置状态<select aria-label="配置状态" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="all">全部版本 · {all.length}</option><option value="current">当前版本 · {counts.current}</option><option value="history">历史版本 · {counts.history}</option><option value="archived">已归档配置 · {counts.archived}</option></select></label><label>模型<select aria-label="按模型查看" value={model} onChange={e=>setModel(e.target.value)}><option value="">全部模型</option>{models.map(id=><option key={id} value={id}>{id}</option>)}</select></label></div></div>
    {groups.length?<div className="config-results-grid">{groups.map(group=><article id={'config-result-'+group.key} key={group.key} className={'config-result-card '+(opened===group.key?'is-open':'')}><button className="config-result-summary" type="button" aria-expanded={opened===group.key} onClick={()=>setOpened(opened===group.key?null:group.key)}><span className="config-result-identity"><small>{group.current?'当前版本':group.archivedConfig?'已归档配置':'历史版本'} · v{group.config.revision}</small><strong>{group.config.name}</strong><em>{group.config.baseModel} · {group.config.reasoning||'默认思考'} · {group.config.serviceTier==='fast'?'Fast':group.config.serviceTier==='standard'?'标准速度':'沿用速度'} · {group.config.skills.length} 个 Skills</em></span><span className="config-result-metric"><strong>{group.score!=null?group.score.toFixed(1):group.nativeScored?`${group.nativePassed} / ${group.nativeScored}`:'—'}</strong><small>{group.referenceOnly&&group.referenceScore!=null?`AI 参考均值 ${group.referenceScore.toFixed(1)} · 不用于配置对比`:group.score==null?(group.nativeScored?'原题已验收试测的通过数 · 不是质量总分':group.recorded?`${group.recorded} 次已有逐题分，题集未完整`:'尚无最终分'):`${group.suiteRunId?"最近完整批次":"当前记录题集"}综合分 · ${group.tasks.length} 道 / 100`}</small></span><span className="config-result-count">{suiteEvidence(group)}<br/>{group.reason||`${group.tasks.length} 道题参与当前分${group.tasks.some(task=>task.entries.some(entry=>entry.trial.captures.some(c=>!c.harnessUnchanged||!c.hostUnchanged)))?" · 运行条件有变动，跨配置比较受限":""}`}{group.archivedRuns>0?` · ${group.archivedRuns} 次归档`:''}<br/>{suiteUsage(group)}</span><span aria-hidden="true" className="config-result-arrow">{opened===group.key?'−':'＋'}</span></button>
      {opened===group.key&&<div className="config-result-detail"><p className="muted">{group.reason||'同题重复先取均值，不同题等权；逐题原始证据可查。'} 比较两套配置需对齐同题同版本、模型和验收协议。</p><CapabilityRadar group={group} all={all} onOpen={onOpen}/><ConfigResultTasks group={group} onOpen={onOpen}/></div>}</article>)}</div>:<Empty>{scope==='archived'?'没有符合条件的已归档配置。归档后的配置会留在这里。':'没有符合筛选条件的配置版本。'}</Empty>}
    <Details title="怎样比较两套 Harness"><p>先对齐题目、模型、思考档位、速度、源码、评分方案和桌面环境。只比较规则或 Skills 时，尽量固定其余条件。换模型后的成绩属于另一套组合，不能只归因于 Harness。同题重复测试仍有随机波动，不自动宣布胜者。</p></Details></>;
}
export {Guide} from './Guide';
