import {ArrowUpRight,Archive,Download,Search,RotateCcw} from 'lucide-react';
import {useState} from 'react';
import {runProgress} from './presentation';
import type {State,Act} from './types';
import {Panel,Details,Empty,num,date} from './ui';
import {downloadRun} from './api';
import {configResults,matchedComparison} from './configResults';
import {DeleteConfig} from './DeleteConfig';
import {EvaluationManagement} from './EvaluationManagement';
export function History({state,act,onOpen,onError}:{state:State;act:Act;onOpen:(id:string)=>void;onError:(s:string)=>void}){
  const [archived,setArchived]=useState(false);const [query,setQuery]=useState('');
  const runs=(archived?state.archivedRuns:state.runs).filter(r=>(r.id+r.notes+r.tasks.map(t=>t.title).join()+r.configs.map(c=>c.name).join()).toLowerCase().includes(query.toLowerCase()));
  const completed=state.runs.filter(r=>r.state==='completed').length;
  return <><header className="page-heading"><div><span className="eyebrow">实验档案</span><h1 className="page-title">每次交付，都有迹可循。</h1><p>保留当时的配置，回看产物与评分证据。</p></div><div className="history-count"><strong>{state.runs.length}</strong><span>次评测 · {completed} 次交付结束</span></div></header>
    <div className="history-toolbar"><div className="catalog-switch"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>活动记录 <span className="tab-count">{state.runs.length}</span></button><button className={archived?'active':''} onClick={()=>setArchived(true)}>已归档 <span className="tab-count">{state.archivedRuns.length}</span></button></div><label className="search-field"><Search size={17}/><input aria-label="搜索历史" placeholder="搜索题目、配置或备注" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
    {runs.length?<section className="history-list" aria-label="评测记录"><div className="history-table-head"><span>任务 / 配置</span><span>状态与证据</span><span>创建时间</span><span>操作</span></div>{runs.map(r=><article className="history-row" key={r.id}><div className="history-task"><button onClick={()=>onOpen(r.id)}>{r.tasks.map(t=>t.title).join('、')}<ArrowUpRight size={16}/></button><p>{r.configs.map(c=>`${c.name} v${c.revision} · ${c.baseModel} / ${c.reasoning}${c.preparationOverride?' · 技能已调整':''}`).join('；')}</p>{r.notes&&<small>{r.notes}</small>}</div><div className="history-state"><span className={'status-pill '+(r.state==='completed'?'done':'pending')}><span/>{runProgress(r)}</span><small>{r.trials.length} 个工作区 · {r.trials.reduce((n,t)=>n+t.captures.length,0)} 份回收</small></div><time title={r.id}>{date(r.createdAt)}</time><div className="history-actions"><button className="icon-button" aria-label={'导出 '+r.tasks.map(t=>t.title).join('、')} title="导出 ZIP" onClick={()=>downloadRun(r.id).catch(e=>onError(e.message))}><Download size={17}/></button><button className="icon-button" aria-label={(archived?'恢复 ':'归档 ')+r.tasks.map(t=>t.title).join('、')} title={archived?'恢复记录':'归档记录'} onClick={()=>act(`/runs/${r.id}/archive`,{archived:!archived,revision:r.revision}).catch(()=>{})}>{archived?<RotateCcw size={17}/>:<Archive size={17}/>}</button></div><EvaluationManagement run={r} act={act}/></article>)}</section>:<Empty><strong>{query?'没有匹配的记录':archived?'归档为空':'从第一次评测开始'}</strong><p>{query?'试试其他题目、配置名称或备注。':archived?'归档的评测可以随时恢复。':'在工作台完成一次评测，产物与过程将保留在这里。'}</p></Empty>}
    <Details title={`CLI 实验档案 · ${state.legacyExperiments} 次`}><p className="muted">CLI 实验单独保存在 runs/，使用 chb report 或 chb analyze 查看，不混入桌面评测。</p></Details></>;

}
export function Comparison({state,act,onOpen}:{state:State;act:Act;onOpen:(id:string)=>void}){
  const [opened,setOpened]=useState<string|null>(null);
  const [model,setModel]=useState('');
  const [scope,setScope]=useState<'all'|'current'|'history'|'archived'>('current');
  const [baselineKey,setBaselineKey]=useState(''),[candidateKey,setCandidateKey]=useState('');
  const all=configResults(state);
  const models=[...new Set(all.map(g=>g.config.baseModel))].sort();
  const counts={current:all.filter(g=>g.current).length,history:all.filter(g=>!g.current&&!g.archivedConfig).length,archived:all.filter(g=>g.archivedConfig).length};
  const groups=all.filter(g=>(!model||g.config.baseModel===model)&&(scope==='all'||(scope==='current'&&g.current)||(scope==='history'&&!g.current&&!g.archivedConfig)||(scope==='archived'&&g.archivedConfig)));
  const baseline=all.find(g=>g.key===baselineKey)||all.find(g=>g.current)||all[0];
  const candidate=all.find(g=>g.key===candidateKey)||all.find(g=>g.current&&g.key!==baseline?.key)||all.find(g=>g.key!==baseline?.key);
  const paired=baseline&&candidate?matchedComparison(baseline,candidate):null;
  return <><header className="page-heading"><div><span className="eyebrow">配置成绩</span><h1 className="page-title">一套配置，一份成绩档案。</h1><p>先看配置版本的参考均分，再查看每道题及重复测试的原始记录。</p></div><div className="history-count"><strong>{all.length}</strong><span>个配置版本</span></div></header>
    <div className="config-results-intro"><p>默认只看当前配置。每次保存后的版本单独统计；同题多次成绩先平均，再让每道题等权。归档配置在“已归档配置”中查看，归档评测仍计入对应配置。题目覆盖或裁判条件不同的均分不可直接比较；不同评分方案或裁判协议不合算。</p><div className="config-results-controls"><label>配置状态<select aria-label="配置状态" value={scope} onChange={e=>setScope(e.target.value as typeof scope)}><option value="all">全部版本 · {all.length}</option><option value="current">当前版本 · {counts.current}</option><option value="history">历史版本 · {counts.history}</option><option value="archived">已归档配置 · {counts.archived}</option></select></label><label>模型<select aria-label="按模型查看" value={model} onChange={e=>setModel(e.target.value)}><option value="">全部模型</option>{models.map(id=><option key={id} value={id}>{id}</option>)}</select></label></div></div>
    {all.length>1&&<section className="matched-comparison"><div><span className="eyebrow">同题对照</span><h2>比较共同题目，避开题目难度差异</h2><p className="muted">仅按两套配置都完成的相同题目版本计算差值；各题等权，重复测试先取均值。样本少时只作线索。</p></div><div className="config-results-controls"><label>基准配置<select aria-label="对照基准配置" value={baseline?.key||''} onChange={e=>setBaselineKey(e.target.value)}>{all.map(g=><option value={g.key} key={g.key}>{g.config.name} · v{g.config.revision}</option>)}</select></label><label>对照配置<select aria-label="对照配置" value={candidate?.key||''} onChange={e=>setCandidateKey(e.target.value)}>{all.map(g=><option value={g.key} key={g.key}>{g.config.name} · v{g.config.revision}</option>)}</select></label></div>{paired?.reason?<p className="score-notice">{paired.reason}</p>:paired?.tasks&&<div><strong>{paired.tasks.length} 道共同题 · 基准 {paired.baselineScore?.toFixed(1)} / 对照 {paired.candidateScore?.toFixed(1)} · 差值 {paired.delta!>=0?'+':''}{paired.delta?.toFixed(1)}</strong><p className="muted">{paired.tasks.map(t=>`${t.task.title} v${t.task.revision}：${t.baseline.toFixed(1)} → ${t.candidate.toFixed(1)}`).join('；')}</p></div>}</section>}
    {groups.length?<div className="config-results-grid">{groups.map(group=><article key={group.key} className={'config-result-card '+(opened===group.key?'is-open':'')}><button className="config-result-summary" type="button" aria-expanded={opened===group.key} onClick={()=>setOpened(opened===group.key?null:group.key)}><span className="config-result-identity"><small>{group.current?'当前版本':group.archivedConfig?'已归档配置':'历史版本'} · v{group.config.revision}</small><strong>{group.config.name}</strong><em>{group.config.baseModel} · {group.config.reasoning||'默认思考'} · {group.config.serviceTier==='fast'?'Fast':group.config.serviceTier==='standard'?'标准速度':'沿用速度'} · {group.config.skills.length} 个 Skills</em></span><span className="config-result-metric"><strong>{group.score==null?'—':group.score.toFixed(1)}</strong><small>{group.score==null?group.reason:'参考均分 / 100'}</small></span><span className="config-result-count">{group.policyCount>1?'评分方案待统一':group.judgeCount>1?'裁判协议待统一':`${group.tasks.length} 道计分题 · ${group.collections.length} 类来源`}<br/>{group.completed} 次可核对 · {group.pending} 次待核对 · {group.archivedRuns} 次已归档</span><span aria-hidden="true" className="config-result-arrow">{opened===group.key?'−':'＋'}</span></button>
      {opened===group.key&&<div className="config-result-detail"><p className="muted">{group.score==null?group.reason:'各题等权；同题重复测试先取算术平均。'} 不同配置若题目覆盖不同，参考均分不可直接用来排高低；分数只代表本机条件下的参考结果。</p><div className="source-actions">{group.current&&<button type="button" className="btn-secondary" onClick={()=>void act('/configs/'+group.config.id+'/archive',{revision:group.config.revision,archived:true})}>归档此配置</button>}{group.archivedConfig&&<DeleteConfig config={state.archivedConfigs.find(c=>c.id===group.config.id)||group.config} act={act} onDeleted={()=>setOpened(null)}/>}<small className="muted">删除配置会移除该配置的所有成绩版本卡；既有评测仍独立保留。评测文件与记录在“评测历史”管理。</small></div>{group.collections.map(source=><section className="config-collection" key={source.key}><header className="config-collection-heading"><h3>{source.label}</h3><span>{source.tasks.length} 道题 · {source.trials} 次评测 · 来源均分 {source.mean.toFixed(1)}</span></header>{source.tasks.map(task=><section className="config-task-results" key={task.task.id+':'+task.task.revision}><header><h3>{task.task.title} <small>v{task.task.revision}</small></h3><strong>{task.mean.toFixed(1)} 分 · {task.entries.length} 次</strong></header>{task.entries.map(entry=><div className="config-trial-row" key={entry.trial.id}><span>{date(entry.run.createdAt)}{entry.archived?' · 已归档':''}</span><span>{num(entry.trial.score.overall,' 分')}</span><button className="btn-ghost" onClick={()=>onOpen(entry.run.id)}>查看评测与证据</button></div>)}</section>)}</section>)}
        {group.entries.filter(e=>!e.eligible||group.policyCount>1||group.judgeCount>1).map(entry=><div className="config-trial-row is-excluded" key={entry.trial.id}><span>{entry.task.title} · {date(entry.run.createdAt)}{entry.archived?' · 已归档':''}</span><span>{entry.exclusion||'评分方案或裁判协议不同'}</span><button className="btn-ghost" onClick={()=>onOpen(entry.run.id)}>查看记录</button></div>)}
        {(group.policyCount>1||group.judgeCount>1)&&<p className="score-notice">这个版本使用了不同评分方案或裁判协议；各次原分可查，汇总分保持空白。</p>}</div>}</article>)}</div>:<Empty>{scope==='archived'?'没有符合条件的已归档配置。归档后的配置会留在这里。':'没有符合筛选条件的配置版本。'}</Empty>}
    <Details title="怎样比较两套 Harness"><p>先对齐题目覆盖，再对齐模型、思考档位、速度、源码、评分方案和桌面环境。只比较规则或 Skills 时，最好固定其余条件。换模型后的成绩属于另一套组合，不能只归因于 Harness。参考均分没有统计置信区间，不自动宣布胜者。</p></Details></>;
}
export {Guide} from './Guide';
