import {ScoreSummary} from './ScoreSummary';
import {HarnessReport} from './HarnessExperiment';
import {NativeVerification} from './NativeVerification';
import {HumanInspection} from './HumanInspection';
import {EvaluationTrack,hasProgramVerifier} from './EvaluationTrack';
import {UsageChart} from './AssessmentCharts';
import {MachineScore} from './MachineScore';
import {EvaluationMetrics} from './Scoring';
import {ObjectivePlan,RatingGuide} from './ScorePlan';
import {ObjectiveReview} from './ObjectiveReview';
import {useState,useId} from 'react';
import type {State,Act,Run,Trial,Task,Config,Capture,Review,CriterionReview} from './types';
import {Field,Panel,Details,Empty,Json,labels,num,date,ScoreSlider,Dialog,ModelSelect,usePanelPosition} from './ui';
import {request,downloadRun} from './api';
import {ContractView,verdicts,ReviewItems} from './Contracts';
import {uiRubricKeys} from './rubricCatalog';
import {CodexApply} from './Codex';
import {trialResultLabel} from './scoreExplanation';
export {Prepare} from './Prepare';

export function RunDetail({run,state,act,onBack,onResults,onError,archived}:{run:Run;state:State;act:Act;onBack:()=>void;onResults:(key:string)=>void;onError:(s:string)=>void;archived:boolean}){
  const [tid,setTid]=useState(run.trials[0].id);const [batchMessage,setBatchMessage]=useState('');const [batchOpening,setBatchOpening]=useState(false);const t=run.trials.find(x=>x.id===tid)||run.trials[0];
  const task=run.tasks.find(x=>x.id===t.taskId)!;const config=run.configs.find(c=>c.id===t.configId)!;
  const scored=run.trials.filter(v=>v.score.overall!=null);
  const batchScore=scored.length?scored.reduce((sum,v)=>sum+v.score.overall!,0)/scored.length:null;
  const batchReferenceOnly=scored.some(v=>!['native','task-check-pass'].includes(v.score.assurance||''));
  const judgeImages=new Set(scored.map(v=>v.reviews.find(review=>review.id===v.score.machineReviewId)?.imageId).filter((image):image is string=>!!image));
  const pendingDraft=run.trials.find(v=>v.state==='prepared'&&!v.sessionId&&v.draftOpenedAt&&(v.draftRequestStatus||'requested')==='requested');
  const unrequestedDrafts=run.trials.filter(v=>v.state==='prepared'&&!v.sessionId&&(!v.draftOpenedAt||v.draftRequestStatus==='cancelled'));
  const openBatch=async()=>{const next=unrequestedDrafts[0];if(!next||pendingDraft)return;setBatchOpening(true);setBatchMessage('');try{const result=await act<{openedTrialIds:string[];failedTrialId:string|null;error:string|null}>(`/runs/${run.id}/open-batch`,{trialId:next.id},{localError:true,silentSuccess:true});if(result.error){setBatchMessage(result.error);}else{setTid(next.id);setBatchMessage('已请求打开本题草稿；请在 Codex 处理目录信任和预填提示词，再回这里确认结果。');}}catch(e){setBatchMessage((e as Error).message);}finally{setBatchOpening(false);}};
  const confirmBatch=async(confirmed:boolean)=>{if(!pendingDraft)return;setBatchOpening(true);setBatchMessage('');try{await act(`/runs/${run.id}/confirm-batch-draft`,{trialId:pendingDraft.id,confirmed},{localError:true,silentSuccess:true});setBatchMessage(confirmed?'已记录你的确认；现在可以请求下一道。':'已记录未打开；同一道题保留在待重试队列，不会自动跳过。');}catch(e){setBatchMessage((e as Error).message);}finally{setBatchOpening(false);}};
  return <div className="run-detail space-y-5"><div className="run-toolbar"><button className="btn-ghost" onClick={onBack}>返回选题与配置（新评测）</button><span className="muted">{date(run.createdAt)}{archived?' · 已归档':''}</span><button className="btn-secondary" onClick={()=>downloadRun(run.id).catch(e=>onError(e.message))}>导出 ZIP</button></div>
    {archived&&<section className="score-notice space-y-2"><strong>这次评测已归档，当前不能打开新题。</strong><p>工作区和记录仍在；恢复后可以打开每题的独立对话，并核对桌面实际配置。</p><button type="button" className="btn-primary" onClick={()=>void act(`/runs/${run.id}/archive`,{archived:false,revision:run.revision}).catch(()=>{})}>恢复这批评测并继续</button></section>}
    {run.comparisonWarnings.map(w=><p className="alert-error" key={w}>{w}</p>)}
    {judgeImages.size>1&&<p className="alert-error" role="alert">本批 AI 裁判使用了不同镜像。综合分可用于查看这次交付，细微分差不宜归因于被测模型或配置；请逐题核对评分过程中的镜像和截图。</p>}
    {run.experiment&&<HarnessReport run={run} onSelect={setTid}/> }
    {run.trials.length>1&&<section className={'batch-queue '+(run.experiment?'harness-queue':'')} aria-label="批量评测待办队列"><header><div><span className="eyebrow">独立工作区队列</span><h2>{run.experiment?'对照执行队列':`本批参考均值：${batchScore==null?'尚无百分制结果':batchScore.toFixed(1)+' / 100'}`}</h2><p>已有 {scored.length}/{run.trials.length} 道题形成可查看的分数</p></div>{!archived&&!pendingDraft&&unrequestedDrafts.length>0&&<button type="button" className="btn-primary" disabled={batchOpening} onClick={()=>void openBatch()}>{batchOpening?'正在打开…':unrequestedDrafts[0].draftRequestStatus==='cancelled'?'重试未打开的这道题':`打开下一道草稿（剩余 ${unrequestedDrafts.length} 道）`}</button>}</header><div className="batch-instructions">{!archived&&pendingDraft&&<div className="batch-draft-confirm" role="status"><strong>等待你确认：{run.tasks.find(item=>item.id===pendingDraft.taskId)?.title||'本题'}</strong><p>请在 Codex 检查本题工作区和预填草稿。保留成功后点确认；若取消了信任或没有草稿，点“草稿未保留”重试本题。</p><div className="run-actions"><button type="button" className="btn-secondary" disabled={batchOpening} onClick={()=>void confirmBatch(false)}>草稿未保留</button><button type="button" className="btn-primary" disabled={batchOpening} onClick={()=>void confirmBatch(true)}>确认草稿已保留</button></div></div>}{batchMessage&&<p role="status">{batchMessage}</p>}<Details title="队列说明与成绩口径"><p>{run.experiment?'每个工作区是一次独立尝试，请按队列顺序执行并回收；A、B 分开统计。':<>各题按适用方式验收，全部有分后等权汇总。{batchReferenceOnly?'题集中含通用烟检、缺少最新快照有效的任务验收或检查失败的项目；此均值不能用作配置胜负。':'专属验收通过也不能单独校准 AI 质量分；交付未结束时仅预览，配置对比还须核对其他条件；'}缺失结果不算零分。</>}</p><p role="alert" className="run-warning">打开草稿不会设置 Codex 桌面当前的模型、思考档位或速度。每道题发送前请按冻结配置核对这三项；未核实条件的成绩不宜用于配置比较。</p><p>每次只请求一道。确认工作区和草稿保留后再打开下一道；取消会保留本题供重试，不会替你发送提示词。这里的确认是你的手动反馈。</p></Details></div><div className="batch-queue-list">{run.trials.map((v,index)=><button type="button" key={v.id} className={'batch-queue-item '+(t.id===v.id?'selected':'')} aria-current={t.id===v.id?'true':undefined} onClick={()=>setTid(v.id)}><span className="batch-queue-index">{String(index+1).padStart(2,'0')}</span><span className="batch-queue-name"><strong>{run.tasks.find(x=>x.id===v.taskId)?.title}</strong><small>{v.experimentArm?`${v.experimentArm} · 第 ${v.repeat} 次 · `:''}{run.configs.find(c=>c.id===v.configId)?.name} · {v.id} · {archived?'已归档 · ':''}{labels[v.state]||v.state}{v.draftOpenedAt?` · ${v.draftRequestStatus==='cancelled'?'未保留，待重试':v.draftRequestStatus==='confirmed'?'已手动确认草稿':'草稿待确认'}`:''}</small></span><span className="batch-queue-score">{trialResultLabel(v,run.tasks.find(task=>task.id===v.taskId)!)}</span></button>)}</div></section>}

    <TrialView key={t.id+'-'+t.stageIndex} run={run} trial={t} task={task} config={config} state={state} act={act} onResults={()=>onResults(config.id+':'+config.revision)} onError={onError} archived={archived}/>
  </div>;
}
function TrialView({run,trial:t,task,config,state,act,onResults,onError,archived}:{run:Run;trial:Trial;task:Task;config:Config;state:State;act:Act;onResults:()=>void;onError:(s:string)=>void;archived:boolean}){
  const [scoreSection,setScoreSection]=useState('overview');
  const [reviewRequest,setReviewRequest]=useState(0);
  const [confirmed,setConfirmed]=useState(false);const [response,setResponse]=useState('');const [reason,setReason]=useState('');const [model,setModel]=useState(config.baseModel);const [copied,setCopied]=useState('');
  const latest=t.captures[t.captures.length-1];const busy=['checking','judging'].includes(t.state);
  const programAvailable=hasProgramVerifier(task,t),checksLabel=programAvailable?'程序验收':'程序验收：无';
  const scoreSections=[['overview','结果总览'],...(programAvailable?[['checks',checksLabel],['quality','AI 评分']]:[['quality','AI 评分'],['checks',checksLabel]]),['human','人工复核']];
  const [panelRef,preservePosition]=usePanelPosition();
  const staged=task.deliveryMode!=='single-delivery'&&task.stages.length>1;
  const intermediate=staged&&t.stageIndex+1<task.stages.length&&!t.finalCaptureId;
  const [tab,setTab]=useState(intermediate||['prepared','working','waiting_confirmation'].includes(t.state)?'execute':latest?'score':'execute');const [preview,setPreview]=useState<'config'|'task'|null>(null);const tabId=useId();
  const tabs=[['execute','执行'],['score','评分'],['records','产物与记录']];
  const selectTab=(key:string)=>{preservePosition(document.getElementById(tabId+tab)?.parentElement,true);setTab(key);};
  const selectScoreSection=(section:string)=>{preservePosition(document.getElementById(tabId+'score-navigation'));if(section==='review')setReviewRequest(value=>value+1);setScoreSection(section==='review'?'quality':section);};
  const action=(name:string,data:unknown={})=>act(`/runs/${run.id}/trials/${t.id}/${name}`,data).catch(()=>{});
  const prompt=t.currentStage.executionPrompt;
  const targetSpeed=config.serviceTier==='fast'?'Fast':config.serviceTier==='standard'?'标准速度':'沿用宿主速度（未固定）';
  const loggedModelMatches=!!t.usage&&t.usage.models.length===1&&t.usage.models[0]===config.baseModel;
  const loggedReasoningMatches=!!t.usage&&t.usage.reasoningLevels.length===1&&t.usage.reasoningLevels[0]===config.reasoning;
  const dataRoot=t.workspacePath.replace(/[\\/]runs[\\/][^\\/]+[\\/][^\\/]+[\\/]workspace$/,'');
  const copy=(value:string,label:string)=>navigator.clipboard.writeText(value).then(()=>setCopied(label+'已复制')).catch(()=>onError('复制失败，请在文本框中手动复制。'));
  const next=t.state==='captured'&&<>{(!intermediate||run.policy.version==='arena-machine-v1')&&<button className="btn-secondary" disabled={archived||busy} onClick={()=>void action('complete').then(result=>{if(result)setTab('score');})}>整题交付结束</button>}{intermediate&&<button className="btn-ghost" disabled={archived||busy} onClick={()=>void action('continue')}>使用第 {t.stageIndex+2} 步提示词</button>}</>;
  return <><header className="trial-heading"><div><h1 className="page-title">{task.title}</h1><div className="trial-meta"><span className="badge">{labels[t.state]}</span><span>{staged?`预设步骤 ${t.stageIndex+1}/${task.stages.length}`:'完整需求 · 不限定对话轮数'} · 已回收 {t.captures.length} 个版本</span><button className="btn-ghost" onClick={()=>setPreview('config')}>{config.name} v{config.revision} · 预览</button></div></div></header>
    {latest&&(!latest.harnessUnchanged||!latest.hostUnchanged)&&<div className="run-warning"><span>{!latest.harnessUnchanged?'回收时工作区规则文件变了。':'这份回收的宿主配置检查未通过。旧记录只比较文件指纹，可能把 Codex 自动登记项目当作变更；新回收会检查实际应用设置。'}请在条件记录中核对。</span><button className="btn-ghost" onClick={()=>setTab('records')}>查看条件记录</button></div>}
    <div className="run-tabs" role="tablist" aria-label="本次评测内容">{tabs.map(([key,label],index)=><button key={key} id={tabId+key} role="tab" aria-selected={tab===key} aria-controls={tabId+key+'-panel'} tabIndex={tab===key?0:-1} onClick={()=>selectTab(key)} onKeyDown={e=>{const offset=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0;const at=e.key==='Home'?0:e.key==='End'?tabs.length-1:offset?(index+offset+tabs.length)%tabs.length:-1;if(at<0)return;e.preventDefault();selectTab(tabs[at][0]);(e.currentTarget.parentElement?.children[at] as HTMLButtonElement)?.focus();}}>{label}</button>)}</div>
    <div ref={panelRef} className="run-panels"><section role="tabpanel" id={tabId+'execute-panel'} aria-labelledby={tabId+'execute'} hidden={tab!=='execute'} className="run-tab-panel space-y-5">
      {t.state==='prepared'&&!archived&&<section className="run-apply-step" aria-label="本批 Codex 配置"><div><span className="eyebrow">执行前核对</span><h2>本题配置</h2><p>项目配置已写入独立工作区。下方可应用全局默认值；同一配置的其他题无需重复写入。</p></div><CodexApply config={config} act={act} trialRoute={`/runs/${run.id}/trials/${t.id}/apply-config`} disabled={archived}/></section>}
      {staged&&<Details title="原题预设步骤（可选）"><ol className="space-y-2">{task.stages.map((stage,i)=><li key={i} className={i===t.stageIndex?'text-sm font-semibold':'muted'}>{i+1}. {stage.title.replace(/^Step \d+:\s*/,'')} · {i<t.stageIndex?'已进入后续阶段':i===t.stageIndex?'当前阶段':'待继续'}</li>)}</ol><p className="muted mt-3">这些是题目预设步骤，不是模型必须对话的次数。已经完成全部需求时，回收后直接选择“整题交付结束”。</p></Details>}
      <Panel title="在 Codex 执行"><section className="execution-conditions" aria-label="本题运行条件"><h3>发送前核对桌面选择</h3><dl className="config-facts"><dt>模型</dt><dd>{config.baseModel}</dd><dt>思考档位</dt><dd>{config.reasoning||'模型默认（未固定）'}</dd><dt>速度</dt><dd>{targetSpeed}</dd></dl><p>有不同请在 Codex 手动调整；打开工作区和写入文件不能保证当前对话已采用。</p>{t.usage&&<p role="status" className={loggedModelMatches&&loggedReasoningMatches?'runtime-match':'run-warning'}>本题日志：{t.usage.models.join('、')||'模型未记录'} · {t.usage.reasoningLevels.join('、')||'档位未记录'}。{loggedModelMatches&&loggedReasoningMatches?'模型与档位已核实一致；速度仍需桌面核对。':'与冻结值不同或记录不全，请核对后再比较成绩；速度仍需桌面核对。'}</p>}</section><div className="run-actions"><button className="btn-primary" disabled={archived||busy} onClick={()=>void action('open',{draft:t.stageIndex===0&&!t.sessionId})}>{t.stageIndex===0&&!t.sessionId?'新建 Codex 对话并预填':'打开 Codex 工作区'}</button><button className="btn-secondary" onClick={()=>void copy(prompt,'提示词')}>复制提示词</button><button className="btn-ghost" onClick={()=>setPreview('task')}>查看任务与提示词</button></div>
        {t.state==='prepared'&&archived&&<p className="score-notice">这次评测已归档；先点击页面顶部的“恢复这批评测并继续”。</p>}
        {t.state==='waiting_confirmation'&&<div className="panel-subtle p-4 space-y-3"><strong>把下面的提示词发到原 Codex 对话</strong><pre className="source">{prompt}</pre><button className="btn-secondary" onClick={()=>void copy(prompt,'下一步提示词')}>复制下一步提示词</button><p className="muted">若这些需求已经完成，无需重复开发，回收现有产物并结束交付即可。</p></div>}
        {copied&&<p role="status" className="muted">{copied}</p>}
        <Details title="工作区与打开说明"><Field label="工作区路径"><input readOnly value={t.workspacePath}/></Field><button className="btn-secondary" onClick={()=>void copy(t.workspacePath,'路径')}>复制路径</button>{task.baselineId&&<Field label="共享源码缓存（本次不在这里修改）"><input readOnly value={`${dataRoot}/baselines/${task.baselineId}/files`}/></Field>}<p>每次测试使用上面的独立工作区。相同源码从缓存复制，不为每个工作区重新联网下载；结束后在数据管理清理工作区，保留回收与评分。</p><p className="muted">目录已创建。首次打开需确认信任，核对模型与档位后手动发送；预填草稿不会自动执行。后续轮次沿用原对话，不保证已有侧栏分组归属。</p></Details>
        <section className="execution-capture" aria-label="回收产物"><div><h3>{t.usage?.activity==='running'?'桌面正在执行':t.usage?.activity==='completed'?'本轮回复已结束':'等待本题执行记录'}</h3><p>{t.usage?.activity==='running'?'等本轮回复结束后，回收当前产物。':'完成或修改后点击回收，保存一个产物版本并进入评分。'}</p></div><button className="btn-primary" disabled={archived||busy||t.usage?.activity==='running'} onClick={()=>void action('capture',{response}).then(result=>{if(result){setResponse('');setTab('score');}})}>{latest?'再次回收产物':'回收产物'}</button>{next}</section>
        <section className="execution-usage"><h3>本题用量</h3><UsageChart usage={t.usage}/></section><fieldset disabled={archived||busy} className="space-y-4">
        <Details title="会话关联与回收说明"><p>{t.telemetryStatus||'自动关联此工作区的 Codex 会话；无需回来点击开始。'}</p><p>回收同时封存本题绑定会话的可见文本；评分前可查看，下次 AI 审查会一并读取。没有绑定日志时保持未知，不影响产物回收。</p><p>需要补充或修改时继续原对话。一次回收是一个版本，不是一次模型回复；未核实运行条件的成绩不宜用于配置比较。</p></Details><Details title="附加本轮回复或说明（可选）"><Field label="本轮回复或说明"><textarea rows={3} value={response} onChange={e=>setResponse(e.target.value)} placeholder="交付说明、澄清或异常"/></Field></Details>
        {['prepared','waiting_confirmation'].includes(t.state)&&<Details title="无法关联会话时手动记录"><label className="check-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>已在桌面核对工作区、模型、思考档位和速度；若不一致已调整</label><button className="btn-secondary" disabled={!confirmed} onClick={()=>void action('start',{settingsConfirmed:confirmed})}>手动标记开始（不影响用量统计）</button></Details>}

        <Details title="记录中断"><Field label="中断原因"><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="额度不足、需要澄清或手工停止"/></Field><button disabled={!reason.trim()} className="btn-secondary" onClick={()=>void action('interrupt',{reason})}>保存中断记录</button><p className="muted">仅记录状态，不停止桌面 Codex。</p></Details></fieldset>
      </Panel>
    </section>
    <section role="tabpanel" id={tabId+'score-panel'} aria-labelledby={tabId+'score'} hidden={tab!=='score'} className="run-tab-panel space-y-5">
      <nav id={tabId+'score-navigation'} className="assessment-navigation" aria-label="评分内容分区">{scoreSections.map(([id,label])=><button type="button" key={id} aria-pressed={scoreSection===id} className={scoreSection===id?'selected':''} onClick={()=>selectScoreSection(id)}>{label}{id==='quality'&&t.state==='judging'&&<span className="badge">进行中</span>}</button>)}</nav>
      <div className="assessment-section" hidden={scoreSection!=='overview'}><ScoreSummary run={run} trial={t} task={task} onResults={onResults} onSection={selectScoreSection}/></div>
      <div className="assessment-section space-y-5" hidden={scoreSection!=='checks'}><EvaluationTrack task={task} trial={t} runId={run.id} disabled={archived} action={action} onReview={()=>selectScoreSection('review')}/>{latest&&<NativeVerification task={task} trial={t} route={`/runs/${run.id}/trials/${t.id}`} disabled={archived} action={action}/>}</div>
      <div className="assessment-section" hidden={scoreSection!=='human'}>{latest?<HumanInspection key={t.id+'-'+latest.id} run={run} trial={t} disabled={archived} act={act}/>:<Empty>回收产物后可以人工复核。</Empty>}</div>
      <div className="assessment-section" hidden={scoreSection!=='quality'}>
      {latest?<>{run.policy.version==='arena-machine-v1'?<MachineScore key={latest.id} run={run} trial={t} state={state} reviewRequest={reviewRequest} onChecks={()=>selectScoreSection('checks')} act={(name,data)=>act(`/runs/${run.id}/trials/${t.id}/${name}`,data)} disabled={archived}/>:<><Panel title={`验收与评分 · 最近回收为第 ${latest.stageIndex+1} 轮`}><p className="score-notice">此记录保留创建时的旧评分算法。新建评测已默认使用机器评分与人工修正。</p><div className="metric-grid"><Metric label="客观检查" value={num(t.score.objective)}/><Metric label="人工复审" value={num(t.score.human)}/><Metric label="综合分" value={num(t.score.overall)}/></div><p className="muted">评分策略：{run.policy.objectiveWeight===0?'纯人工':run.policy.humanWeight===0?'仅客观检查':'客观检查 + 人工复审'}（客观 {run.policy.objectiveWeight}% / 人工 {run.policy.humanWeight}%）。</p><p className="muted">综合分需完成交付并补齐策略要求的证据。各分项有各自依据，个人约束另列；空值不是零分。</p>
    {(!latest.harnessUnchanged||!latest.hostUnchanged)&&<p className="alert-error">规则文件或宿主配置指纹发生变化，需核对；本结果不能视作条件保持一致。</p>}
    {t.lastJobError&&t.lastJobError.kind!=='native'&&<p role="alert" className="alert-error">{t.lastJobError.message}</p>}
    <div className="flex gap-3 flex-wrap"><button className="btn-secondary" disabled={archived||busy||!latest.checksConfigured} onClick={()=>void action('check',{captureId:latest.id})}>检查此快照 ({latest.checksConfigured})</button>{busy&&t.nativeExecution?.status!=='running'&&<button className="btn-secondary" disabled={archived} onClick={()=>void action('stop')}>停止后台检查 / 审查</button>}</div>
    {!latest.checksConfigured&&<p className="muted">本阶段未配置脚本验收；可以人工复审，也可以由 AI 辅助定位问题。</p>}
    {latest.checks.map(c=><Details key={c.id} title={`${c.label} · ${labels[c.status]||c.status} · ${c.seconds}s`}><p className="muted">退出码 {c.exitCode??'未知'} · 镜像 {c.imageId}</p><pre className="source">{c.output||'没有输出'}</pre></Details>)}
    <Details title="独立 AI 复审"><p className="muted">点击后使用所选模型额度，在 Harbor 容器运行 CLI 审查器。只审查封存的材料，结果归为辅助意见，不是桌面任务的分数或用量。意见必须引用实际文件与行。</p><Field label="审查模型"><ModelSelect label="审查模型" value={model} onChange={setModel} models={state.models}/></Field><button disabled={archived||busy} className="btn-secondary" onClick={()=>void action('judge',{captureId:latest.id,model})}>使用模型额度启动复审</button></Details>
    <p className={['not_met','needs_review'].includes(t.score.acceptance.status)?'alert-error':'muted'}>必要条目验收：{verdicts[t.score.acceptance.status]} · {t.score.acceptance.met}/{t.score.acceptance.required} 项。此结论与数值分数分开。</p>
    <ObjectiveReview trial={t} act={data=>action('objective-review',data)} disabled={archived||busy}/>
    <ManualReview key={latest.id+'-'+t.reviews.filter(r=>r.captureId===latest.id&&r.kind==='human').slice(-1)[0]?.id} previous={t.reviews.filter(r=>r.captureId===latest.id&&r.kind==='human').slice(-1)[0]} capture={latest} config={config} task={task} requireEvidence={run.policy.requireDimensionEvidence} rubrics={run.policy.rubrics} dimensions={run.policy.rubrics?Object.fromEntries(Object.entries(run.policy.rubrics).filter(([k])=>run.policy.dimensions[k]>0).map(([k,v])=>[k,v.label])):state.dimensions} act={data=>action('review',data)} disabled={archived||busy}/>
  </Panel><Details title="本题检查方案"><ObjectivePlan tasks={[task]}/></Details></>}
      </>:<Empty><p>先回收产物，再开始评分。</p><button className="btn-secondary mt-3" onClick={()=>setTab('execute')}>去执行与回收</button></Empty>}
      </div>{latest&&next&&<div className="assessment-delivery run-actions justify-end">{next}</div>}
    </section>
    <section role="tabpanel" id={tabId+'records-panel'} aria-labelledby={tabId+'records'} hidden={tab!=='records'} className="run-tab-panel space-y-5">
      {latest?<Evidence key={t.id} run={run} trial={t} onError={onError} disabled={archived||busy} check={captureId=>action('check',{captureId})}/>:<Empty>回收后可在这里查看文件和历史证据。</Empty>}
      <Panel title="用量与过程" aside={<span className="muted">{t.usage?'原生日志':'等待日志'}</span>}>
        <UsageChart usage={t.usage}/>
        {t.observations.map(s=><p className="alert-error" key={s}>{s}</p>)}
        <Field label="导入本题 JSONL 日志"><input type="file" accept=".jsonl,.json" disabled={archived||busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>15_000_000){onError('日志超过 15 MB。');return;}await action('trace',{raw:await f.text()});e.target.value='';}}/></Field>
        <Details title="完整指标与日志说明"><EvaluationMetrics trial={t}/><p className="muted">核对日志的工作区与会话，读取最终累计用量，不扫描其他会话。未获取的用量和费用保持未知。</p>{t.usage&&<Json value={t.usage}/>}</Details>
      </Panel>
      <Details title="冻结条件与配置副本"><p className="muted break-all">{run.id} · {t.id}</p><Json value={{mode:run.executionMode,policy:run.policy,hostFingerprint:run.hostFingerprint}}/><p className="muted">宿主指纹只覆盖已记录文件，不代表全局技能和插件完全隔离。</p><pre className="source">{config.agentsPrompt}</pre><Json value={config}/><button className="btn-secondary" disabled={archived||busy} onClick={()=>void act(`/runs/${run.id}/restore-config`,{configId:config.id}).catch(()=>{})}>恢复为新的配置副本</button></Details>
      <Details title={`活动记录 · ${run.events.length} 条`}><ol className="space-y-3">{[...run.events].reverse().map((e,i)=><li className="text-sm" key={i}><time className="muted mr-3">{date(e.at)}</time>{e.message}</li>)}</ol></Details>
    </section></div>
    <Dialog title="本题配置" open={preview==='config'} onClose={()=>setPreview(null)}><dl className="config-facts"><dt>配置</dt><dd>{config.name} v{config.revision}{config.preparationOverride?' · 本次技能已调整':''}</dd><dt>模型与档位</dt><dd>{config.baseModel} · {config.reasoning}</dd><dt>Skills</dt><dd>{config.skills.length} 个 · {t.skillMode==='explicit'?'每轮明确请求':'按任务需要'}</dd></dl><pre className="source">{config.agentsPrompt||'未附加规则'}</pre>{t.skills?.map(s=><div key={s.id}><strong>{s.name}</strong><p className="muted break-all">{s.sourceLabel||'手动导入'} · {s.sourcePath}</p><p className="muted break-all">.agents/skills/{s.name}/SKILL.md · {s.manifest.sha256.slice(0,12)}</p></div>)}<Details title="完整配置"><Json value={config}/><p className="muted">文件已装载不代表实际调用；以桌面执行记录为准。</p></Details></Dialog>
    <Dialog title={staged?`步骤 ${t.stageIndex+1}：${t.currentStage.title}`:'完整任务提示词'} open={preview==='task'} onClose={()=>setPreview(null)}><div className="prompt-actions"><span>发送到本题 Codex 对话</span><button className="btn-secondary" onClick={()=>void copy(prompt,'提示词')}>复制提示词</button></div><pre className="prompt-reading">{prompt}</pre><Details title="题目约定与版本信息"><ContractView task={task}/><p className="muted break-all">{t.currentStage.promptSource} · SHA-256 {t.currentStage.promptSha256}</p></Details></Dialog>
  </>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="panel-subtle p-3"><p className="muted mb-2">{label}</p><strong className="text-xl font-semibold">{value}</strong></div>;}
function ManualReview({capture,task,config,dimensions,act,disabled,previous,rubrics,requireEvidence}:{capture:Capture;task:Task;config:Config;dimensions:Record<string,string>;act:(data:unknown)=>Promise<unknown>;disabled:boolean;previous?:Review;rubrics?:Record<string,{description:string}>;requireEvidence?:boolean}){
  const [dimensionEvidence,setDimensionEvidence]=useState<Record<string,string>>(previous?.dimensionEvidence||{});
  const [scores,setScores]=useState<Record<string,string>>(Object.fromEntries(Object.entries(previous?.scores||{}).map(([k,v])=>[k,String(v)])));
  const [notes,setNotes]=useState(previous?.notes||'');const [readiness,setReadiness]=useState(previous?.readiness||'');const [reason,setReason]=useState('');
  const [constraints,setConstraints]=useState<Record<string,string>>(previous?.constraints||Object.fromEntries(config.customConstraints.filter(c=>c.isActive).map(c=>[c.id,'unverified'])));
  const [constraintNotes,setConstraintNotes]=useState<Record<string,string>>(previous?.constraintNotes||{});
  const [criteria,setCriteria]=useState<Record<string,CriterionReview>>(Object.fromEntries((task.criteria||[]).map(c=>[c.id,previous?.criteria?.[c.id]||{status:'unverified',notes:''}])));
  const criterion=(id:string,patch:Partial<CriterionReview>)=>setCriteria({...criteria,[id]:{...criteria[id],...patch}});
  const dims=Object.entries(dimensions).filter(([k])=>!uiRubricKeys.has(k)||task.hasFrontendUI);
  return <Details title="人工验收与细粒度评分"><form className="space-y-4" onSubmit={e=>{e.preventDefault();void act({captureId:capture.id,scores:Object.fromEntries(dims.map(([k])=>[k,Number(scores[k])])),notes,readiness,constraints,constraintNotes,criteria,dimensionEvidence,revisionReason:reason});}}><fieldset disabled={disabled} className="space-y-4">
    <p className="muted">先实际查看交付物与检查记录。每条要求从未核实开始；选择其他结论需写依据。必要条目与数值分数分开，AI 意见不会自动填入。</p>
    {task.criteria?.map(c=><div key={c.id} className="panel-subtle p-3 space-y-3"><h3 className="text-sm font-semibold">{c.required?'必要项':'观察项'} · {c.label}</h3>{c.description&&<p className="muted">{c.description}</p>}<Field label={`${c.label}：验收状态`}><select value={criteria[c.id].status} onChange={e=>criterion(c.id,{status:e.target.value})}>{['unverified','met','partial','unmet','not_applicable'].map(v=><option value={v} key={v}>{verdicts[v]}</option>)}</select></Field><Field label={`${c.label}：验收依据`} hint="记录实际操作、预期与实际结果；未满足和不适用也需说明。"><textarea required={criteria[c.id].status!=='unverified'} value={criteria[c.id].notes} onChange={e=>criterion(c.id,{notes:e.target.value})}/></Field><div className="grid sm:grid-cols-2 gap-3"><Field label={`${c.label}：证据文件（可选）`}><select value={criteria[c.id].filePath||''} onChange={e=>criterion(c.id,{filePath:e.target.value||undefined})}><option value="">无文件引用</option>{Object.keys(capture.manifest.files).sort().map(path=><option key={path}>{path}</option>)}</select></Field><Field label={`${c.label}：已运行检查（可选）`}><select value={criteria[c.id].checkId||''} onChange={e=>criterion(c.id,{checkId:e.target.value||undefined})}><option value="">无检查引用</option>{capture.checks.map(check=><option value={check.id} key={check.id}>{check.label} · {labels[check.status]}</option>)}</select></Field></div></div>)}
    <RatingGuide/>
    <div className="grid sm:grid-cols-2 gap-4">{dims.map(([k,label])=><div key={k} className="space-y-2"><ScoreSlider label={label} value={scores[k]??''} onChange={v=>setScores({...scores,[k]:v})}/>{rubrics?.[k]?.description&&<p className="muted">{rubrics[k].description}</p>}{requireEvidence&&<Field label={label+'：实际评分依据'}><textarea required value={dimensionEvidence[k]||''} onChange={e=>setDimensionEvidence({...dimensionEvidence,[k]:e.target.value})} placeholder="实际操作、预期与结果、文件或检查证据"/></Field>}</div>)}</div>
    <Field label="交付可用程度"><select required value={readiness} onChange={e=>setReadiness(e.target.value)}><option value="">请选择</option><option value="ready_to_merge">可以采用</option><option value="minor_polish">少量修改后可用</option><option value="major_rework">需要较大修改</option><option value="rejected">当前不可用</option></select></Field>
    {config.customConstraints.filter(c=>c.isActive).map(c=><div key={c.id}><Field label={c.title} hint={c.ruleDesc}><select value={constraints[c.id]} onChange={e=>setConstraints({...constraints,[c.id]:e.target.value})}><option value="unverified">未核实</option><option value="met">已满足</option><option value="unmet">未满足</option><option value="not_applicable">本题不适用</option></select></Field>{task.schemaVersion===2&&<Field label={c.title+'：约束依据'}><textarea required={constraints[c.id]!=='unverified'} value={constraintNotes[c.id]||''} onChange={e=>setConstraintNotes({...constraintNotes,[c.id]:e.target.value})}/></Field>}</div>)}
    <Field label="评分依据" hint="说明实际体验、文件位置、未满足项。视觉评分需实际查看页面，不依据源码猜测。"><textarea required rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></Field>
    {previous&&task.schemaVersion===2&&<Field label="本次复审修订原因"><textarea required value={reason} onChange={e=>setReason(e.target.value)}/></Field>}<button className="btn-primary">保存人工复审版本</button>
  </fieldset></form></Details>;
}
function Evidence({run,trial:t,onError,disabled,check}:{run:Run;trial:Trial;onError:(s:string)=>void;disabled:boolean;check:(id:string)=>Promise<unknown>}){
  const [selected,setSelected]=useState('');const [file,setFile]=useState<{path:string;content:string}|null>(null);
  const c=t.captures.find(c=>c.id===selected)||t.captures[t.captures.length-1];
  const read=async(path:string)=>{try{setFile(await request(`/runs/${run.id}/trials/${t.id}/files/${c.id}/${path.split('/').map(encodeURIComponent).join('/')}`));}catch(e){onError((e as Error).message);}};
  return <Panel title="产物与证据"><Field label="回收版本"><select value={c.id} onChange={e=>{setSelected(e.target.value);setFile(null);}}>{[...t.captures].reverse().map(c=><option key={c.id} value={c.id}>回收于 {date(c.at)} · {c.id}</option>)}</select></Field>
    <Details title="快照校验信息"><p className="muted break-all">SHA-256 {c.manifest.sha256}</p></Details><Details title={`此版本的客观检查 · ${c.checks.length}/${c.checksConfigured}`}>
    {c.checks.map(check=><div key={check.id}><p className="text-sm">{check.label} · {labels[check.status]} · {check.seconds}s</p><pre className="source">{check.output}</pre></div>)}
    {!c.checks.length&&<p className="muted">此版本尚无已执行检查。</p>}{!!c.checksConfigured&&<><button className="btn-secondary" disabled={disabled} onClick={()=>void check(c.id)}>运行所选版本的检查</button><p className="muted">可补验前一轮已封存的文件。每轮只有最新回收版本的检查参与总分。</p></>}</Details>
    {!!c.nativeVerifications?.length&&<Details title={`项目测试验收 · ${c.nativeVerifications.length} 次`}>{c.nativeVerifications.map(r=><div key={r.id}><p>{date(r.at)} · 目标 {r.f2p_passed}/{r.f2p_total} · 回归 {r.p2p_passed}/{r.p2p_total} · {r.reward?'通过':'未通过'}</p><p className="muted break-all">{r.logDirectory}</p></div>)}</Details>}
    <Details title={`文件列表 · ${Object.keys(c.manifest.files).length} 个`}><div className="max-h-64 overflow-auto space-y-1">{Object.keys(c.manifest.files).sort().map(name=><button key={name} className="block text-left text-sm underline break-all" onClick={()=>void read(name)}>{name}</button>)}</div>{file&&<><h3 className="text-sm font-medium">{file.path}</h3><pre className="source">{file.content}</pre></>}{!!c.manifest.excluded.length&&<p className="muted">已排除：{c.manifest.excluded.join('、')}</p>}</Details>
    <Details title={`相对起点的变更 · ${c.facts.changes.length} 个文件`}><p className="muted">{c.facts.note}</p><pre className="source">{c.facts.diffPatch||'没有文本变更'}</pre>{c.facts.diffTruncated&&<p className="muted">差异显示已截断；导出包含完整文件。</p>}</Details>
    {c.response&&<Details title="本轮回复记录"><pre className="source">{c.response}</pre></Details>}
    <Details title="此快照的历次复审">{t.reviews.filter(r=>r.captureId===c.id).length?t.reviews.filter(r=>r.captureId===c.id).slice().reverse().map(r=><div key={r.id} className="panel p-4 space-y-3"><h3 className="text-sm font-medium">{r.kind==='ai'?(r.scoreSchema==='arena-machine-v1'?'机器评分':'AI 辅助审查'):'人工复审'} · {date(r.at)}</h3>{r.kind==='ai'?<><p className="text-sm whitespace-pre-wrap">{r.summary}</p>{r.scoreSchema==='arena-machine-v1'&&Object.entries(r.ratings||{}).map(([key,item])=><div key={key} className="panel-subtle p-3 text-sm"><strong>{run.policy.rubrics?.[key]?.label||key} · {num(item.score)}</strong><p>{item.reason}</p>{item.evidence.map((e,i)=><pre key={i} className="source">{e.path?`${e.path}:${e.line}`:e.command||e.checkId}{'\n'}{e.quote}</pre>)}</div>)}{r.findings?.map((f,i)=><div key={i} className="panel-subtle p-3 text-sm"><button className="underline" onClick={()=>void read(f.path)}>{f.path}:{f.line}</button><pre className="source">{f.quote}</pre><p>{f.comment}</p></div>)}<p className="muted">引用不成立的意见已排除 {r.rejectedFindings||0} 项；未覆盖文件 {r.omittedFiles?.length||0} 个。引用成立不代表意见必然正确。</p></>:<ReviewItems task={run.tasks.find(task=>task.id===t.taskId)!} review={r}/>}</div>):<p className="muted">此版本尚无复审。</p>}</Details>
  </Panel>;
}
