import type {Policy,State,Trial} from './types';
import {verdicts} from './Contracts';
import {Field} from './ui';
export function ScoringSettings({state,policy,onChange}:{state:State;policy:Policy;onChange:(p:Policy)=>void}){
  const items=policy.rubrics||{};
  const add=(key:string,label:string,description:string)=>onChange({...policy,version:'arena-review-v2',dimensions:{...policy.dimensions,[key]:1},rubrics:{...items,[key]:{label,description}}});
  return <section className="space-y-4"><h3 className="font-semibold">评分方案与依据</h3><p className="muted">任务成功、客观检查、人工质量与效率分别记录。下列是可编辑的人工量表，不是行业统一标准；默认启用项等权。创建后冻结，旧记录保持原方案。</p>
    <div className="grid sm:grid-cols-2 gap-4"><Field label="客观检查权重"><input type="number" min={0} max={100} value={policy.objectiveWeight} onChange={e=>onChange({...policy,objectiveWeight:Number(e.target.value),humanWeight:100-Number(e.target.value)})}/></Field><p className="muted self-center">人工质量 {policy.humanWeight}%。没有可执行检查的题目可将客观权重设为 0。</p></div>
    <div className="rubric-list">{Object.entries(items).map(([key,item])=><div className="rubric-row" key={key}><div><strong className="text-sm">{item.label}</strong><p className="muted">{item.description}</p></div><Field label={item.label+'权重'}><input type="number" min={0} max={100} value={policy.dimensions[key]??0} onChange={e=>onChange({...policy,dimensions:{...policy.dimensions,[key]:Number(e.target.value)}})}/></Field><button type="button" className="btn-ghost" aria-label={'移除评分项 '+item.label} disabled={Object.keys(items).length<=1} onClick={()=>{const dims={...policy.dimensions};const rubrics={...items};delete dims[key];delete rubrics[key];onChange({...policy,dimensions:dims,rubrics});}}>移除</button></div>)}</div>
    <div className="flex gap-3 flex-wrap"><Field label="添加评分项"><select disabled={Object.keys(items).length>=16} value="" onChange={e=>{const item=state.rubricCatalog[e.target.value];if(item)add(e.target.value,item.label,item.description);}}><option value="">选择适用维度</option>{Object.entries(state.rubricCatalog).filter(([k])=>!items[k]).map(([k,v])=><option value={k} key={k}>{v.label}</option>)}</select></Field><button type="button" className="btn-secondary" disabled={Object.keys(items).length>=16} onClick={()=>add('custom-'+crypto.randomUUID().slice(0,8),'自定义评分项','按本题的实际证据评分；请在创建前修改名称和依据。')}>添加自定义项</button></div>
    {Object.entries(items).filter(([k])=>k.startsWith('custom-')).map(([key,item])=><div className="grid sm:grid-cols-2 gap-3" key={key}><Field label="自定义评分名称"><input value={item.label} onChange={e=>onChange({...policy,rubrics:{...items,[key]:{...item,label:e.target.value}}})}/></Field><Field label="自定义评分依据"><input value={item.description} onChange={e=>onChange({...policy,rubrics:{...items,[key]:{...item,description:e.target.value}}})}/></Field></div>)}
    <p className="muted">依据：SWE-bench / Terminal-Bench 重视可执行结果；τ-bench 强调重复可靠性；Inspect 支持按任务选择评分器；OSWorld 检查桌面任务结果。Token、耗时、人工介入和重复成功率不混入人工质量分。</p>
  </section>;
}
export function EvaluationMetrics({trial:t}:{trial:Trial}){
  const latest=t.captures[t.captures.length-1];const review=t.reviews.filter(r=>r.kind==='human'&&r.captureId===latest?.id).slice(-1)[0];
  const rows=[['必要需求',`${t.score.acceptance.met}/${t.score.acceptance.required} 已满足（${verdicts[t.score.acceptance.status]||t.score.acceptance.status}）`],['本次快照检查',latest?`${latest.checks.filter(c=>c.status==='passed').length} 通过 / ${latest.checks.length} 已执行 / ${latest.checksConfigured} 已配置`:'尚无回收'],['规则与宿主条件',latest?(latest.harnessUnchanged&&latest.hostUnchanged?'已检查的文件指纹一致':'已检查的文件指纹发生变化'):'尚未核对'],['个人约束',review?`${Object.values(review.constraints||{}).filter(v=>v==='met').length} 已满足 / ${Object.keys(review.constraints||{}).length} 项`:'未复审'],['总 Token',t.usage?.totalTokens??'缺少有效原生日志'],['日志活动时长（秒）',t.usage?.activeSeconds??'未知'],['重复可靠性 / 每次成功成本','需要同条件独立重复与成本证据；当前不估算'],['人工介入次数','当前尚未完整采集，不用轮数代替']];
  return <section className="space-y-3"><h3 className="font-semibold">评测指标全貌</h3><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{rows.map(([label,value])=><tr className="border-b border-slate-200 dark:border-zinc-800" key={label}><th className="text-left p-3 font-medium">{label}</th><td className="p-3">{value}</td></tr>)}</tbody></table></div></section>;
}
