import type {Run,Task,Trial} from './types';
import {Details} from './ui';
import {dialogueResult} from './presentation';
import {ScoreCoverage} from './ScoreCoverage';
import {batchScoreSummary,currentTrialAxes,nativeTestProgress,programScoreExplanation,totalScoreExplanation} from './scoreExplanation';

const display=(value:number|null|undefined)=>value==null?'—':Number.isInteger(value)?String(value):value.toFixed(1);

export function ScoreSummary({run,trial,task,onSection,onResults}:{run:Run;trial:Trial;task:Task;onSection:(section:string)=>void;onResults?:()=>void}){
  const total=totalScoreExplanation(run,trial,task),program=programScoreExplanation(trial,task);
  const batch=batchScoreSummary(run),axes=currentTrialAxes(run,trial,task),card=trial.score.taskScorecard;
  const corrections=Object.keys(trial.score.machineOverrides||{}).length;
  const programFailed=program.value==='未通过'||!!trial.score.programAcceptance?.failed;
  const progress=trial.score.scoreProgress,native=nativeTestProgress(trial);
  const partial=!!progress&&progress.coverage>0&&progress.unknownWeight>0;
  const dialogue=trial.captures[trial.captures.length-1]?.interactionEvidence;
  const report=trial.reviews.find(row=>row.id===trial.score.machineReviewId);
  const interaction=dialogue?.sha256&&report?.interaction?.evidenceSha256===dialogue.sha256?report.interaction:null;
  return <section className="score-summary" aria-label="评分总览">
    <header className="score-summary-heading"><div><h2>本题评分总览</h2><p>{trial.captures.length?`回收版本 ${trial.captures.length}`:'尚未回收'} · {trial.state==='completed'?'交付结束':'交付进行中'}</p></div><div className="run-actions"><button type="button" className="btn-secondary" onClick={()=>onSection('checks')}>{program.value==='无'?'程序验收：无':'查看程序验收'}</button>{onResults&&<button type="button" className="btn-primary" onClick={onResults}>查看配置总评</button>}</div></header>
    <div className="score-summary-metrics">
      <article className="score-summary-total"><h3>{task.publicSource?'目标测试完成比例':trial.score.overall==null?(partial?'已评分部分的范围':'单题总分待形成'):trial.state==='completed'?'本地单题总分':'暂定单题总分'}</h3><p className="score-summary-number">{task.publicSource?display(native?.target):trial.score.overall==null&&partial?`${display(progress.minimum)}–${display(progress.maximum)}`:display(trial.score.overall)}<span>{task.publicSource?' %':' / 100'}</span></p><p>{task.publicSource?(native?'来自这道题的目标测试。原题通过/失败独立保留，本地连续质量分在下方展开。':'原题尚未取得有效结果；先运行程序验收。'):trial.score.overall==null&&partial?`已确认 ${display(progress.knownPoints)} 分，剩余 ${display(progress.unknownWeight)} 分权重待核实；不把已测项放大成完整分。`:total.status}</p></article>
      <article className={programFailed?'score-summary-failed':undefined}><h3>{program.label}</h3><p className="score-summary-number">{program.value}</p><p>{program.detail}</p></article>
      <article><h3>AI原始均值</h3><p className="score-summary-number">{display(trial.score.machine)}<span> / 100</span></p><p>已评分项的加权均值，缺项不填0。{corrections?`另有 ${corrections} 项人工修正；总分使用修正后的有效分项。`:'程序结果与AI评价分别保存。'}</p><button type="button" className="btn-text" onClick={()=>onSection('quality')}>查看逐项分数与依据 →</button></article>
    </div>
    {programFailed&&<p className="alert-error" role="status">程序验收已发现失败。质量参考分不能把程序失败改成通过；请在“程序验收”查看失败项。</p>}
    {native&&<section className="score-native-progress" aria-label="SWE单题程序进展"><h3>SWE 单题程序结果 · 不需要 AI 再判一次</h3><dl><div><dt>目标测试完成比例</dt><dd>{display(native.target)}%<span>{native.result.f2p_passed} / {native.result.f2p_total} 通过</span></dd></div><div><dt>旧功能回归通过比例</dt><dd>{display(native.regression)}%<span>{native.result.p2p_passed} / {native.result.p2p_total} 通过</span></dd></div><div><dt>原题结果</dt><dd>{native.result.reward} / 1<span>{native.result.reward?'整题通过':'整题未通过，失败记录仍计入统计'}</span></dd></div></dl><p>这些比例只描述这道题的测试，不代表所有要求已完成，也不把回归的许多简单通过项混成一个高分。可维护性等 AI 质量意见另列；没有本地连续卡，也能查看上述结果。</p></section>}
    <ScoreCoverage trial={trial} task={task} onSection={section=>onSection(section==='quality'?'review':section)}/>
    <Details title={task.publicSource?'本地连续质量分与冻结公式':'单题总分怎么计算'}>{task.publicSource&&<p>本地连续质量分：{display(trial.score.overall)} / 100。{total.status}此分数独立于原题通过状态，失败不会被质量分改成通过。</p>}<p>{total.formula}</p>{card&&<table className="score-summary-contributions"><thead><tr><th scope="col">冻结评分组</th><th scope="col">权重</th><th scope="col">本次贡献</th></tr></thead><tbody>{card.items.map((row,index)=><tr key={row.key||`${row.label}:${index}`}><th scope="row">{row.label}</th><td>{row.weight}%</td><td>{row.points==null?'待验证':`${display(row.points)} 分`}</td></tr>)}</tbody></table>}<p>评分版本：{total.version}。高分是本地参考值；已评分不代表原题程序验收通过，AI引用存在也不证明判断正确。</p>{trial.score.human!=null&&<p>独立人工参考分：{display(trial.score.human)} / 100。按本记录冻结方案决定是否计入总分。</p>}<button type="button" className="btn-text" onClick={()=>onSection('human')}>打开作品并人工复核 →</button></Details>
    <section className="harness-use-record" aria-label="Harness使用记录"><h3>这次 Harness 用起来怎么样</h3><dl><div><dt>执行用量（包含失败）</dt><dd>{trial.usage?.totalTokens==null?'未记录':`${trial.usage.totalTokens.toLocaleString()} Token`}</dd></div><div><dt>执行活动时间</dt><dd>{trial.usage?.activeSeconds==null?'未记录':`${(trial.usage.activeSeconds/60).toFixed(1)} 分钟`}</dd></div>{(['request','correction','interruption'] as const).map((key,index)=>{const counts=interaction?.counts[key],result=dialogueResult(counts);return <div key={key}><dt>{['切题率','纠正响应率','必要追问率'][index]}</dt><dd>{result.rate==null?'未判定':`${result.rate}% · ${counts!.met}/${result.judged} 符合`}</dd>{counts&&<p>{counts.unknown} 次未知 · {counts.not_applicable} 次不适用</p>}</div>;})}</dl><p>SWE用于检查工程结果的底线；Harness是否有帮助，还要在同模型、同题下看纠正、打断与资源差异。可以只选一组相关任务对照，不必跑完整题库；一份记录不能单独证明配置更好。</p><button type="button" className="btn-text" onClick={()=>onSection('dialogue')}>查看沟通指标、标准与原话 →</button></section>
    <Details title="这道题如何进入雷达图"><p>下列是本题有证据的轴分；配置雷达会先平均同题重复，再按题等权。雷达不另算综合总分。</p><ul className="score-axis-sources">{axes.map(axis=><li key={axis.id}><div><strong>{axis.label}</strong><span>{axis.score==null?'未测':`${display(axis.score)} / 100`}</span></div><p>{axis.samples[0]?.runs[0]?.basis||'当前快照没有此轴对应的有效评分证据，不按0分处理。'}</p></li>)}</ul>{task.publicSource&&<p>原题通过或未通过不会复制到六个轴。当前公开题评分卡只可能提供目标功能、工程可维护性和旧功能回归；网页体验、推理决策、协作与交付保持未测。</p>}<p>逐回合对话观察不自动计入本题总分或雷达。只有冻结评分卡中的相关评分项，才可能映射到对应轴。</p></Details>
    <Details title="整批、SWE通过率与配置综合分怎么看">{batch.total>1&&<p>本批参考均值：{batch.mean==null?'待全部形成单题分':`${display(batch.mean)} / 100`}，已有 {batch.scored}/{batch.total} 次试测形成单题分。这里按本批每次试测等权；含多配置时不代表某套配置的成绩。</p>}{batch.nativeTotal>0&&<p>本批公开题原题通过率：{batch.nativeRate==null?'待验收':`${display(batch.nativeRate)}%`}（{batch.nativePassed}/{batch.nativeVerified} 次已验收通过）；另有 {batch.nativeTotal-batch.nativeVerified} 次待验收。分母不包含未验收记录，待验收不会填0。</p>}<p>SWE原题看验收器的reward（0或1）和F2P/P2P明细。跨题通过率 = 通过的试测数 ÷ 已取得有效原题结果的试测数；这是测试通过率，不能直接变成六轴能力分。</p><p>“配置成绩”页的综合分 = 同题、同版本、同协议的重复试测先求均值，再对各题均值等权平均。完整批次优先，缺失、协议混用、临时改技能或只有AI参考证据时，综合分可能暂不发布。</p><p>开放项目须结束交付，并核对当前快照的任务验收证据；公开题须有绑定当前快照的原题报告与本地连续评分卡。单题分可先查看，配置对比还要同模型、同档位、同速度、共同题目与协议。</p></Details>
  </section>;
}
