import {useEffect,useState} from 'react';
import {Database,FolderArchive,RefreshCw} from 'lucide-react';
import type {Act} from './types';
import {request} from './api';
import {Dialog,Field,Details,labels} from './ui';
type Workspace={runId:string;trialId:string;revision:number;title:string;state:string;workspaceBytes:number;reviewBytes:number;snapshotBytes:number;captures:number;reviews:number;workspacePath:string;canClean:boolean;cleanup?:{status:string}};
type Inventory={root:string;categories:{name:string;path:string;bytes:number;purpose:string}[];workspaces:Workspace[];tools:Record<string,boolean>};
const bytes=(n:number)=>n<1024*1024?(n/1024).toFixed(1)+' KB':(n/1024/1024).toFixed(1)+' MB';
export function Storage({act,onOpen}:{act:Act;onOpen:(id:string)=>void}){
  const [data,setData]=useState<Inventory|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [focused,setFocused]=useState('');
  const [selected,setSelected]=useState<{row:Workspace;action:string}|null>(null);const [stopped,setStopped]=useState(false);const [confirmation,setConfirmation]=useState('');
  const refresh=async()=>{setLoading(true);setError('');try{setData(await request<Inventory>('/storage/status',{}));}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const open=(row:Workspace,action:string)=>{setError('');setStopped(false);setConfirmation('');setSelected({row,action});};
  const apply=async()=>{if(!selected)return;try{setData(await act<Inventory>('/storage/workspace',{runId:selected.row.runId,trialId:selected.row.trialId,revision:selected.row.revision,action:selected.action,desktopStopped:stopped,confirmation}));setSelected(null);}catch(e){setError((e as Error).message);}};
  const rows=(data?.workspaces||[]).filter(r=>(!query||[r.title,r.runId,r.trialId].some(v=>v.toLowerCase().includes(query.toLowerCase())))&&(filter==='all'||filter==='cleanable'&&r.canClean||filter==='trash'&&['trashed','deleting'].includes(r.cleanup?.status||'')));
  const current=rows.find(r=>r.trialId===focused)||rows[0];
  const cleanupLabel=(r:Workspace)=>({trashed:'待删除',deleting:'删除待重试',deleted:'已清理'}[r.cleanup?.status||'']||labels[r.state]||r.state);
  return <><header className="page-heading"><div><span className="eyebrow">本机数据</span><h1 className="page-title">数据放在哪，清理到哪。</h1><p>源码起点、工作区、产物与评分分别保留，按评测查看。</p></div><button className="btn-secondary" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={16}/>{loading?'正在统计…':'刷新占用'}</button></header>
    {error&&<p role="alert" className="alert-error">{error}</p>}
    {data&&<><div className="storage-summary"><div><Database size={20}/><strong>{bytes(data.workspaces.reduce((s,r)=>s+r.snapshotBytes+r.reviewBytes,0))}</strong><span>快照与验收文件</span></div><div><FolderArchive size={20}/><strong>{bytes(data.workspaces.reduce((s,r)=>s+r.workspaceBytes,0))}</strong><span>开发工作目录</span></div><div><strong>{data.workspaces.length}</strong><span>可追踪工作区</span></div></div>
    <Details title="启动与存放位置"><p className="break-all">本机数据根：{data.root}</p><p>网站使用 Python 与已构建的前端；打开网站不需要 Docker。首次运行需要安装依赖，下载过的题包与源码可离线复用。模型登录、模型调用和各题开发依赖分别准备。</p><p>Git {data.tools.git?'已找到':'未找到'} · Codex CLI {data.tools.codex?'已找到':'未找到'} · Docker {data.tools.dockerInstalled?'已安装，未检查运行状态':'未安装（不影响浏览和准备源码）'}</p><p>本工具只管理项目内目录；不删除宿主 Codex 会话、凭据或全局配置。数据与下载缓存不进入 Git。</p></Details>
    <section className="storage-browser"><div className="storage-toolbar"><input aria-label="搜索评测数据" placeholder="搜索题目或记录编号" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="筛选工作目录" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部记录 · {data.workspaces.length}</option><option value="cleanable">可清理</option><option value="trash">待删除</option></select></div><div className="storage-master-detail"><div className="storage-records" aria-label="评测数据列表">{rows.map(row=><button className={'storage-record '+(row.trialId===current?.trialId?'is-selected':'')} aria-pressed={row.trialId===current?.trialId} key={row.trialId} onClick={()=>setFocused(row.trialId)}><strong>{row.title}</strong><span>{cleanupLabel(row)} · {row.captures} 份快照 · {row.reviews} 次复查</span><small>{row.runId.slice(-8)} / {row.trialId.slice(-6)}</small><b>{bytes(row.workspaceBytes)}</b></button>)}{!rows.length&&<p className="muted">没有匹配的评测记录。</p>}</div>{current?<article className="storage-detail"><span className="eyebrow">{cleanupLabel(current)}</span><h2>{current.title}</h2><dl><dt>工作目录</dt><dd>{bytes(current.workspaceBytes)}</dd><dt>冻结快照 · {current.captures} 份</dt><dd>{bytes(current.snapshotBytes)}</dd><dt>测试与 AI 复查文件 · {current.reviews} 次</dt><dd>{bytes(current.reviewBytes)}</dd></dl><div className="source-actions"><button className="btn-primary" onClick={()=>onOpen(current.runId)}>查看产物与评分</button>{['trashed','deleting'].includes(current.cleanup?.status||'')?<><button className="btn-secondary" disabled={current.cleanup?.status==='deleting'} onClick={()=>open(current,'restore')}>恢复工作区</button><button className="btn-danger" onClick={()=>open(current,'purge')}>彻底删除工作区</button></>:<button className="btn-secondary" disabled={!current.canClean} onClick={()=>open(current,'trash')}>清理工作目录</button>}</div><p className="muted">{current.canClean?'清理工作目录可恢复；快照、评分与复查记录保留。':['trashed','deleting','deleted'].includes(current.cleanup?.status||'')?'工作目录与历史证据分别管理。':'回收产物并标记交付结束后，才能清理。'}</p><Details title="目录与记录编号"><p className="break-all">{current.workspacePath}</p><p className="break-all">{current.runId} / {current.trialId}</p></Details></article>:<div className="storage-detail muted">选择一条记录查看占用与操作。</div>}</div></section>
    <Details title="存储分区与文件位置"><div className="storage-categories">{data.categories.map(c=><article className="storage-category" key={c.path}><strong>{c.name}</strong><span>{bytes(c.bytes)}</span><code>{c.path}</code><p>{c.purpose}</p></article>)}</div></Details></>}
    <Dialog title={selected?.action==='purge'?'永久删除工作区':selected?.action==='restore'?'恢复工作区':'清理工作目录'} open={!!selected} onClose={()=>setSelected(null)}>{selected&&<div className="space-y-4">{error&&<p role="alert" className="alert-error">{error}</p>}<strong>{selected.row.title}</strong><p className="break-all">{selected.row.workspacePath}</p><p>{selected.action==='trash'?'完整工作目录（含依赖和 Git）移入待删除区，可以恢复；此步骤尚不释放磁盘。':selected.action==='restore'?'恢复到原来的目录位置。':'删除待删除区中的完整工作目录；无法恢复其中依赖和 Git。'}冻结快照、AI 复查、评分与历史记录保留。</p>{selected.action==='trash'&&<label className="check-row"><input type="checkbox" checked={stopped} onChange={e=>setStopped(e.target.checked)}/>Codex 桌面已停止写入这个工作区</label>}{selected.action==='purge'&&<Field label="输入“永久删除工作区”确认"><input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></Field>}<button className={selected.action==='purge'?'btn-danger':'btn-primary'} disabled={selected.action==='trash'?!stopped:selected.action==='purge'?confirmation!=='永久删除工作区':false} onClick={()=>void apply()}>确认{selected.action==='purge'?'永久删除':selected.action==='restore'?'恢复':'移入待删除区'}</button></div>}</Dialog>
  </>;
}
