import {useEffect,useState} from 'react';
import {Database,FolderArchive,RefreshCw} from 'lucide-react';
import type {Act} from './types';
import {request} from './api';
import {DeleteEvaluation} from './DeleteEvaluation';
import {Details,Field,labels} from './ui';

type Workspace={runId:string;trialId:string;revision:number;title:string;state:string;workspaceBytes:number;reviewBytes:number;snapshotBytes:number;captures:number;reviews:number;workspacePath:string;canDeleteRun:boolean;reviewPath:string;humanPath:string;humanBytes:number;deletionPending:boolean;workspaceDeletion?:{status:string}|null};
type Inventory={root:string;publicSourcesRoot:string;categories:{name:string;path:string;absolutePath:string;bytes:number;purpose:string}[];workspaces:Workspace[];tools:Record<string,boolean>;migration?:{files:number;leftoverPath:string|null}};
const bytes=(n:number)=>n<1024*1024?(n/1024).toFixed(1)+' KB':(n/1024/1024).toFixed(1)+' MB';

export function Storage({act,onOpen}:{act:Act;onOpen:(id:string)=>void}){
  const [data,setData]=useState<Inventory|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const [query,setQuery]=useState(''),[focused,setFocused]=useState('');
  const [cacheDestination,setCacheDestination]=useState(''),[cacheConfirmed,setCacheConfirmed]=useState(false),[movingCache,setMovingCache]=useState(false),[cacheMessage,setCacheMessage]=useState('');
  const refresh=async()=>{setLoading(true);setError('');try{setData(await request<Inventory>('/storage/status',{}));}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const moveCache=async()=>{setMovingCache(true);setError('');setCacheMessage('');try{const result=await act<Inventory>('/storage/move-public-cache',{destination:cacheDestination,confirmation:cacheConfirmed?'迁移题包缓存':''});setData(result);setCacheMessage(`已校验并迁移 ${result.migration?.files||0} 个题包缓存文件。${result.migration?.leftoverPath?`旧目录未能自动清除：${result.migration.leftoverPath}`:''}`);setCacheDestination('');setCacheConfirmed(false);}catch(e){setError((e as Error).message);}finally{setMovingCache(false);}};
  const rows=(data?.workspaces||[]).filter(row=>!query||[row.title,row.runId,row.trialId].some(value=>value.toLowerCase().includes(query.toLowerCase())));
  const current=rows.find(row=>row.trialId===focused)||rows[0];
  const cleanupLabel=(row:Workspace)=>row.workspaceDeletion?.status==='deleted'?'工作区已删除':['deleting','recheck'].includes(row.workspaceDeletion?.status||'')?'删除待继续':labels[row.state]||row.state;
  return <><header className="page-heading"><div><span className="eyebrow">本机数据</span><h1 className="page-title">数据放在哪，清理到哪。</h1><p>按评测查看工作区、快照与记录；删除分两步完成。</p></div><button className="btn-secondary" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={16}/>{loading?'正在统计…':'刷新占用'}</button></header>
    {error&&<p role="alert" className="alert-error">{error}</p>}
    {data&&<><div className="storage-summary"><div><Database size={20}/><strong>{bytes(data.workspaces.reduce((sum,row)=>sum+row.snapshotBytes+row.reviewBytes,0))}</strong><span>快照与验收文件</span></div><div><FolderArchive size={20}/><strong>{bytes(data.workspaces.reduce((sum,row)=>sum+row.workspaceBytes,0))}</strong><span>开发工作目录</span></div><div><strong>{data.workspaces.length}</strong><span>可追踪工作区</span></div></div>
      <Details title="启动与存放位置"><p className="break-all">本机数据根：{data.root}</p><p>打开网站不需要 Docker。模型登录、模型调用和各题开发依赖分别准备。</p><p>Git {data.tools.git?'已找到':'未找到'} · Codex CLI {data.tools.codex?'已找到':'未找到'} · Docker {data.tools.dockerInstalled?'已安装':'未安装'}</p><p>整评测删除的第一步同步删除精确关联的 Codex 对话；第二步删除剩余评测证据。共享题包与配置备份保留。</p></Details>
      <section className="storage-browser"><div className="storage-toolbar"><input aria-label="搜索评测数据" placeholder="搜索题目或记录编号" value={query} onChange={event=>setQuery(event.target.value)}/></div><div className="storage-master-detail"><div className="storage-records" aria-label="评测数据列表">{rows.map(row=><button className={'storage-record '+(row.trialId===current?.trialId?'is-selected':'')} aria-pressed={row.trialId===current?.trialId} key={row.trialId} onClick={()=>setFocused(row.trialId)}><strong>{row.title}</strong><span>{cleanupLabel(row)} · {row.captures} 份快照 · {row.reviews} 次复查</span><small>{row.runId.slice(-8)} / {row.trialId.slice(-6)}</small><b>{bytes(row.workspaceBytes)}</b></button>)}{!rows.length&&<p className="muted">没有匹配的评测记录。</p>}</div>
        {current?<article className="storage-detail"><span className="eyebrow">{cleanupLabel(current)}</span><h2>{current.title}</h2><dl><dt>人工审查副本</dt><dd>{bytes(current.humanBytes||0)}</dd><dt>工作目录</dt><dd>{bytes(current.workspaceBytes)}</dd><dt>冻结快照 · {current.captures} 份</dt><dd>{bytes(current.snapshotBytes)}</dd><dt>测试与 AI 复查文件 · {current.reviews} 次</dt><dd>{bytes(current.reviewBytes)}</dd></dl><div className="source-actions"><button className="btn-primary" onClick={()=>onOpen(current.runId)}>查看产物与评分</button><DeleteEvaluation runId={current.runId} revision={current.revision} workspaceDeletion={current.workspaceDeletion} canDelete={current.canDeleteRun} act={act} onDeleted={()=>{void refresh();}}/></div>{current.workspaceDeletion?.status==='deleting'&&<p className="muted">工作区删除尚未完成，可继续。</p>}<Details title="目录与记录编号"><p className="break-all">{current.workspacePath}</p><p className="break-all">裁判日志与报告：{current.reviewPath}</p><p className="break-all">人工审查副本：{current.humanPath}</p><p className="break-all">{current.runId} / {current.trialId}</p></Details></article>:<div className="storage-detail muted">选择一条记录查看占用与操作。</div>}</div></section>
      <Details title="存储分区与文件位置"><div className="storage-categories">{data.categories.map(category=><article className="storage-category" key={category.path}><strong>{category.name}</strong><span>{bytes(category.bytes)}</span><code className="break-all">{category.absolutePath}</code><p>{category.purpose}</p></article>)}</div><div className="space-y-4"><h3>迁移公开题包缓存</h3><p>当前路径：<code className="break-all">{data.publicSourcesRoot}</code>。可将已下载题包复制到新位置，逐文件校验后切换。</p><Field label="新缓存文件夹的完整路径（必须尚不存在）"><input value={cacheDestination} onChange={event=>setCacheDestination(event.target.value)} placeholder="D:\Codex-Harness-Cache\public-sources"/></Field><label className="check-row"><input type="checkbox" checked={cacheConfirmed} onChange={event=>setCacheConfirmed(event.target.checked)}/>已核对目标路径并确认迁移</label><button className="btn-secondary" disabled={!cacheDestination.trim()||!cacheConfirmed||movingCache} onClick={()=>void moveCache()}>{movingCache?'正在复制和校验…':'迁移题包缓存'}</button>{cacheMessage&&<p role="status">{cacheMessage}</p>}</div></Details></>}
  </>;
}
